### ISSUE TITLE
Add PoW options to torcc

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1000]
This issue requests adding PoW configuration to torcc and testing, per the guidelines: https://community.torproject.org/onion-services/advanced/dos/

@preland Maybe you'd want to take a look?

**Comment by preland** [comment]
I can look into this (won’t be able to do anything today, my “home base” has been without power for the last couple days)

**Comment by shortwavesurfer2009** [comment]
There is also something about IntroDoS that should prob be enabled if its not already either.

**Comment by preland** [comment]
Looking into this further, it appears that PoW is [enabled by default](https://community.torproject.org/onion-services/ecosystem/technology/pow/#how-to-enable-this-as-a-user) on tor versions past 0.4.8.1-alpha, and is fully functional in GPL-licensed builds (which is what we currently use).

As far as IntroDoS goes, we could enable that; it's technically out of scope for this issue (happy 1000th issue/PR Haveno! :confetti_ball: ), but it is a valid concern nonetheless.

**Comment by nahuhh** [comment]
You have to edit torrc 

https://community.torproject.org/onion-services/ecosystem/technology/pow/#example-configuration

**Comment by shortwavesurfer2009** [comment]
> Looking into this further, it appears that PoW is [enabled by default](https://community.torproject.org/onion-services/ecosystem/technology/pow/#how-to-enable-this-as-a-user) on tor versions past 0.4.8.1-alpha, and is fully functional in GPL-licensed builds (which is what we currently use).
> 
> As far as IntroDoS goes, we could enable that; it's technically out of scope for this issue (happy 1000th issue/PR Haveno! 🎊 ), but it is a valid concern nonetheless.

From what I understood, it is enabled by default for users since then, but is not enabled by default for onion services and actually must be enabled. There was a forum post asking onion service operators to enable it.

**Comment by woodser** [comment]
Enabled in https://github.com/haveno-dex/haveno/pull/1012
