### ISSUE TITLE
Deposited funds to Haveno, funds went straight to reserved and are locked, can't trade, can't empty wallet...SOLVED

### ISSUE THREAD

**Issue by Goodtenks** [haveno-dex/haveno#1016]
We recently decided to start trading on Haveno retro at the time with only 2 other traders in our country.
Set everything up, sent 2.7xxx xmr to Haveno wallet and created an ad, ad didn't appear live and our funds appeared in a RESERVED wallet in Haveno, no trades were accepted, we cant post an ad and we can't access our xmr!

SOLVED; For some reason we just had to delete an offer we had first made that wasn't showing up as active but was holding our funds in reserve, we managed to delete the offer, make a new one and complete a successful trade on Haveno!

**Comment by woodser** [comment]
If you go to Portfolio > My Open Offers, do you have any offers created there?

If so, you can click the trash icon to remove your offer and make your funds available again. For example:

<img width="1219" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/73e67962-4f50-4484-b0c6-533814b354e6">

If not, have you tried restarting your application?

**Comment by Goodtenks** [comment]
That did the trick! How did we miss that!
So we found the created trade, completely scrapped it, once it was deleted we were able to access the funds so we thought we'd try again, successfully completed a trade! 
Thanks for your help really appreciate it
