### ISSUE TITLE
Support Haveno on Tails [2 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1017]
This issue requests supporting Haveno on Tails.

Any custom steps should be clearly documented.

**Comment by nihilist001** [comment]
steps to recreate the issue:
tails os usb image setup in qemu https://tails.net/doc/advanced_topics/virtualization/virt-manager/index.en.html
then once in there, you make sure there is a root password upon launching
then enable persistant storage (otherwise the haveno package wont install due to lack of space)

then install it as usual (latest zipfile amd64 from the reto repo) 1.0.7-1, dpkg -i haveno.deb
THEN to launch it:

 torsocks /opt/haveno/bin/Haveno --socks5ProxyHttpAddress=localhost:9050 --socks5ProxyXmrAddress=localhost:9050 --useTorForXmr=on

(yes for some reason i need torsocks)
then it fails, you get tor bridges from torproject and restart haveno, and then you get that error upon successful connection:

 torsocks /opt/haveno/bin/Haveno --socks5ProxyHttpAddress=localhost:9050 --socks5ProxyXmrAddress=localhost:9050 --useTorForXmr=on
 
![image](https://github.com/haveno-dex/haveno/assets/139641914/3a4d19d2-b0df-45f9-9c8b-79a24fdca02a)

command prompt: https://paste.mozilla.org/LnRittQA/raw

haveno.log: https://paste.mozilla.org/JQm1ZqaY/raw

torrc files: https://paste.mozilla.org/xedt2w8v/raw

**Comment by woodser** [comment]
So the root exception is this:

```
Jun-12 08:53:33.055 [pool-37-thread-1] INFO  haveno.core.xmr.wallet.XmrWalletService: Initializing main wallet with monerod=http://xmr-node.cakewallet.com:18081 
Jun-12 08:53:33.055 [pool-37-thread-1] INFO  haveno.core.xmr.wallet.XmrWalletService: XmrWalletService.createWallet(haveno_XMR) 
Jun-12 08:53:33.062 [pool-37-thread-1] ERROR h.core.xmr.setup.MoneroWalletRpcManager: Unable to start monero-wallet-rpc instance after 2 attempts 
java.net.SocketException: Operation not permitted
	at haveno.core.xmr.setup.MoneroWalletRpcManager.startInstance(MoneroWalletRpcManager.java:120)
	at haveno.core.xmr.wallet.XmrWalletService.startWalletRpcInstance(XmrWalletService.java:1659)
	at haveno.core.xmr.wallet.XmrWalletService.createWalletRpc(XmrWalletService.java:1569)
	at haveno.core.xmr.wallet.XmrWalletService.createWallet(XmrWalletService.java:345)
	at haveno.core.xmr.wallet.XmrWalletService.maybeInitMainWallet(XmrWalletService.java:1340)
	at haveno.core.xmr.wallet.XmrWalletService.maybeInitMainWallet(XmrWalletService.java:1320)
	at haveno.core.xmr.wallet.XmrWalletService.lambda$initMainWalletIfConnected$37(XmrWalletService.java:1311)
	at haveno.common.ThreadUtils.lambda$execute$0(ThreadUtils.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Operation not permitted
	at java.base/sun.nio.ch.Net.listen(Native Method)
	at java.base/sun.nio.ch.NioSocketImpl.listen(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at java.base/java.net.ServerSocket.<init>(Unknown Source)
	at java.base/java.net.ServerSocket.<init>(Unknown Source)
	at haveno.core.xmr.setup.MoneroWalletRpcManager.startInstance(MoneroWalletRpcManager.java:93)
```

Guessing because it's trying to connect over clearnet on initial launch, before the wallet is synced?

In that case, you could try starting with `--useTorForXmr=ON`.

**Comment by nihilist001** [comment]
when trying this command without tor bridges: 

```
torsocks /opt/haveno/bin/Haveno --useTorForXmr=ON --socks5ProxyHttpAddress=localhost:9050 --socks5ProxyXmrAddress=localhost:9050
```

i get the following:
![image](https://github.com/haveno-dex/haveno/assets/139641914/2649b7f3-e967-4809-a51a-ca9e66d11756)

cmd: https://paste.mozilla.org/cANLY7VL/raw
haveno.log: https://paste.mozilla.org/J7d1qnKN/raw


next i add tor bridges, and after a while i get the monero rpc error again:

![image](https://github.com/haveno-dex/haveno/assets/139641914/613c0bb2-66ad-49d9-81ae-34882333d544)

cmd: https://paste.mozilla.org/4NXkvAFt/raw
haveno.log: https://paste.mozilla.org/GKVE5AHr/raw

**Comment by nihilist001** [comment]
same thing when i use the command without the socks parameters:
``` 
torsocks /opt/haveno/bin/Haveno --useTorForXmr=ON
```
cmd: https://paste.mozilla.org/Ngrz8npO

**Comment by nihilist001** [comment]
Could the issue be that haveno tries to connect to a clearnet monero node instead of a .onion monero node?
![image](https://github.com/haveno-dex/haveno/assets/139641914/4c3e1d9d-5646-462a-a1f5-15767bdb7884)

**Comment by BrandyJSon** [comment]
Hi I have a script that allows for a user to easily set this up to run on tails. I couldn't get haveno-reto to run without control ports like it appears you where able to @nihilist001. So if there is anything additional you did and didn't mention please lmk cause using control port is definitely not preferable. 
https://github.com/BrandyJSon/haveno-install-tails/

**Comment by nihilist001** [comment]
> Hi I have a script that allows for a user to easily set this up to run on tails. I couldn't get haveno-reto to run without control ports like it appears you where able to @nihilist001. So if there is anything additional you did and didn't mention please lmk cause using control port is definitely not preferable. https://github.com/BrandyJSon/haveno-install-tails/

awesome work, big thanks! added the steps for the tails users in my main tutorial https://blog.nihilism.network/servers/haveno-client-f2f/index.html
@woodser  please give the full bounty to @BrandyJSon  as he found the solution.

sidenotes: it could be great to have that tails setup script bundled with the binaries alongside the .deb file or something similar

**Comment by woodser** [comment]
Thanks @BrandyJSon. Please open a PR adding this to the scripts directory.

**Comment by BrandyJSon** [comment]
https://github.com/haveno-dex/haveno/pull/1036

**Comment by woodser** [comment]
Completed in https://github.com/haveno-dex/haveno/pull/1036
