### ISSUE TITLE
Manual federation suggestion (user-based, and through the official haveno client)

### ISSUE THREAD

**Issue by nihilist001** [haveno-dex/haveno#1019]
suggestion that came up on the matrix chat today;

have the official haveno client (which is supposed to remain unaffiliated with any haveno network) with the possibility for the user to just mention which haveno network it wants to connect to.

example:

bob the noob goes on haveno-dex/haveno git repo, downloads the binary for haveno 1.0.7 for linux; and by default it does not have any seednodes hardcoded (unlike how it would be on haveno-reto for example) 

so haveno prompts bob to just mention the seednodes he want to connect to.

lucky for bob, haveno reto has their list of seed nodes made public (basically a list of .onion urls) so bob copies it, into his haveno client, and now he can connect just fine without having to download haveno-reto.

Now all the reto trade offers appear, and he can take them. (arbitrated via haveno reto's arbitrators)

Bob could also put the seed nodes of another haveno network, along the seed nodes he already entered from reto, and he would also see their trade offers; arbitrated by their arbitrators.

this would avoid having to install haveno-reto, haveno-whatever  packages to see the trades of each, in a different haveno client each time.
This would ALSO stay true to the principle that the official haveno client does NOT have an official haveno network, the user would have to look for one, and manually use their seed nodes

**Comment by woodser** [comment]
Related / duplicate of https://github.com/haveno-dex/haveno/issues/901

**Comment by nihilist001** [comment]
my bad; didnt see this was already suggested. hence closing
