### ISSUE TITLE
Fix 'key cancellation' and 'address hostage' bugs on Monero multisig [$1000]

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#102]
Monero's multisig implementation has some vulnerabilities:

- Key cancellation attack: during address construction, the attacker can 'cancel' the share components of other participants, giving himself full authority to spend funds
- Address hostage attack: during address construction, the attacker can add a non-shared key, forcing all participants to collaborate with him on any signature

These bugs need to be fixed before Haveno goes live. @UkoeHB is working on a PR.

**Comment by UkoeHB** [comment]
Here is my [WIP branch](https://github.com/UkoeHB/monero/tree/multisig_addr_v2).

**Comment by UkoeHB** [comment]
A [PR is now open](https://github.com/monero-project/monero/pull/7877) to resolve this issue.

**Comment by erciccione** [comment]
@UkoeHB now that https://github.com/monero-project/monero/pull/7877, please PM me on matrix/libera with an xmr address :)

**Comment by erciccione** [comment]
Sent. Thanks @UkoeHB :)
