### ISSUE TITLE
PayPal: 2 small issues

### ISSUE THREAD

**Issue by shortwavesurfer2009** [haveno-dex/haveno#1021]
1. When adding an account, every currency it supports is checked by default and must be unchecked one by one instead of being unchecked by default and letting you check mark the currencies you want.
2. No way to enter in offer details, such as must send an email from the email address of your account or other trade terms.

**Comment by woodser** [comment]
Wondering if we really want to include additional offer details. Why must they send an email from the email of their account?

Otherwise, the payment is a standardized PayPal transaction.

**Comment by shortwavesurfer2009** [comment]
Some people use it as fraud prevention because that means that not only do they have to have access to the PayPal account, but they also have to have access to the email listed on that PayPal account. Personally, I think I would like to use it in order to specify that an account must be at least X days old. Otherwise, I don't want to trade with them. By having an extra details screen, I could say that your account must be at least say one year old and be signed. Otherwise, don't open a trade or you will be refunded and the arbitrators will be notified.

**Comment by shortwavesurfer2009** [comment]
It would make sense to add it to all payment methods. In my opinion, just simply because local Monero did the same thing. They allowed the user to define terms on which they would accept the trade or not.

**Comment by shortwavesurfer2009** [comment]
There's an additional details thing under the pay-by-mail already and take a look at how it is used. For example, some people in pay-by-mail specifically say that they don't accept payments from people who live in New York, United States, for example.

**Comment by XMRfamily** [comment]
> It opens the door to every payment method having additional details for terms like this. Not saying I'm opposed, just thinking it means theoretically adding it to all fiat payment methods.

You should. There are things like I ask people to respond to my text messages for fraud prevention(making sure not someone being scammed, I don't ask them to click any links) this makes me feel safer, zelle for example has so much fraud so if I verify the person I am requesting from actually wants xmr then I know it's less likely to be fraud.

**Comment by wp07e** [comment]
This specific ticket for Paypal / Cashapp can be closed. Both suggestions by @shortwavesurfer2009 have been implemented.

1. #1067
2. #1106
