### ISSUE TITLE
Message on startup: No filter object from seed nodes [...] Please inform the Haveno developers.

### ISSUE THREAD

**Issue by OrangeCakeZero** [haveno-dex/haveno#1023]
Hello,

I did receive the following message on startup:

![Screenshot 2024-06-11 180120](https://github.com/haveno-dex/haveno/assets/105603041/4054ab76-1dc0-48e3-a2d9-def12062affe)

**Comment by woodser** [comment]
Unless you're running your own network, this is fixed by network admins after updating and restarting the services, so you won't continue seeing it.
