### ISSUE TITLE
Fix 'Wagner/Drijvers attack' in Monero multisig [$2500]

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#103]
Monero's multisig is vulnerable to the Wagner attack, where if multiple signatures are constructed for a given address, and the wagner attack is executed, then the attacker can learn the private key shares of other participants.

This (and #102 ) has been discussed with Monero's core team (@luigi1111) and researchers (@moneromooo-monero, @sarangNoether and @UkoeHB.)

Sarang's suggestion is to fix the vulnerability by implementing the constructions specified in [MRL-0009](https://www.getmonero.org/resources/research-lab/pubs/MRL-0009.pdf). Discussions are ongoing.

**Comment by AAH20** [comment]
I've the Solution , Adding some Data Encryption Standards simple components such as permutation of private addresses during multisig. , several encryption algorithms can be applied here , but the performance decide the winner.

**Comment by AAH20** [comment]
**### In This call within the "multisig.h" file** 

crypto::secret_key generate_multisig_view_secret_key(const crypto::secret_key &skey, const std::vector<crypto::secret_key> &skeys);

both arguments will be swapped with a fresh generated obfuscated secret key alternatives using the permutation method which the simplest component of the Data Encryption Standard process , then thrown after each transaction with a destructor.

**Comment by AAH20** [comment]
therefore i've an important note about the implementation of the account_keys data structure as a struct bec. it is not efficient when it comes to garbage management , should have been implemented as a class to facilitate using of destructor methods.

**Comment by AAH20** [comment]
This Solution also might provide an efficient enough solution to solve this #86 "multisig wallets generation time issue".

**Comment by UkoeHB** [comment]
A [PR is open](https://github.com/monero-project/monero/pull/7877) to resolve this issue.

**Comment by chaserene** [comment]
FYI, issue in upstream: https://github.com/monero-project/monero/issues/7830

**Comment by chaserene** [comment]
going by [this comment](https://github.com/monero-project/monero/issues/7830#issuecomment-907478929), maybe a more actionable title for this bounty would be "Implement thring signatures", wouldn't it?

**Comment by selsta** [comment]
As far as I know https://github.com/monero-project/monero/pull/8113 fixes Wagner/Drijvers attack. @UkoeHB could you confirm?

**Comment by UkoeHB** [comment]
Yes

**Comment by UkoeHB** [comment]
This was fixed [here](https://github.com/monero-project/monero/pull/8149), the original author @perfect-daemon gets credit if he ever wants to claim this bounty.

**Comment by woodser** [comment]
Excellent. @perfect-daemon, please let me know if you want to claim this bounty. :) Thanks @UkoeHB!
