### ISSUE TITLE
How can I install "unzip" on my system?

### ISSUE THREAD

**Issue by OkeyDokeyArtichokey** [haveno-dex/haveno#1038]
During installion. 
At step 5: "curl -s "https://get.sdkman.io" | bash"

I receive:
"Please install unzip on your system using your favourite package manager.

 Restart after installing unzip"

Did I miss something during the download of MSYS2?

**Comment by nihilist001** [comment]
sudo apt install unzip

**Comment by woodser** [comment]
For MSYS2:

```
pacman -Syu
pacman -S unzip
```

Please re-open if you continue to have problems.
