### ISSUE TITLE
"Missing resource for key: N/A_SHORT"

### ISSUE THREAD

**Issue by haveno-user** [haveno-dex/haveno#1047]
There is currently an offer listed in Market > Offers By Payment Method which doesn't have a localized short name available, so it displays as N/A_SHORT:USD, and there's a continual string of warning messages in the log while that tab is displayed.
```
Jun-19 20:37:53.606 [JavaFX Application Thread] WARN  haveno.core.locale.Res: Missing resource for key: N/A_SHORT 
Jun-19 20:37:53.620 [JavaFX Application Thread] WARN  haveno.core.locale.Res: Missing resource for key: N/A_SHORT 
Jun-19 20:37:53.626 [JavaFX Application Thread] WARN  haveno.core.locale.Res: Missing resource for key: N/A_SHORT 
Jun-19 20:37:55.328 [JavaFX Application Thread] WARN  haveno.core.locale.Res: Missing resource for key: 56
```
![NA_Short](https://github.com/haveno-dex/haveno/assets/171326655/38e912f9-c9bb-4690-a2eb-8476164d1e5a)

It's also in Sell > Monero.
![Sell_Monero_NA_Short](https://github.com/haveno-dex/haveno/assets/171326655/4f6f1b2b-401e-4500-abd4-0d7589d0562b)

Offer ID: 707838-a285d669-c83d-4795-87b3-e15019e26587-106
Maker's onion address: 4tvbn2unkz6ledp4unmtfy7mqm3zhv54a4vyw36tdvuj6xktj4mdmnad.onion:9999
**Payment method: N/A**

**Comment by woodser** [comment]
Have you upgraded to 1.0.7? It's a CashApp offer, which is only supported since the last release.

**Comment by haveno-user** [comment]
I downgraded to 1.0.6 because I was having some issues while testing, so that must be it, thanks.
