### ISSUE TITLE
Reserve funds only if the offer(s) gets taken

### ISSUE THREAD

**Issue by HardenedSteel** [haveno-dex/haveno#1055]
This is alternative approach to #1054 in order to increase liquidity on Haveno.

Currently you can't post more offers than the coins you have which resulting very low liquidity on Haveno (also for Bisq).

Letting makers to post offers as much as they want can increase the liquidity for payment methods by 5 times or more. However this can result in spam.

P2P platforms like Localmonero were working like that.

**Comment by woodser** [comment]
Not sure that I understand the difference from https://github.com/haveno-dex/haveno/issues/1053, but again, offers are intentionally funded so multiple offers cannot be created with the same funds.

**Comment by HardenedSteel** [comment]
If UTXOs are verified as you said then issue #1054 is better way to increase liquidity.

**Comment by woodser** [comment]
Yeah, that would be nice if an offer can support multiple payment methods.

**Comment by woodser** [comment]
Closing since this would enable a fractional reserve where people can offer to sell xmr they don't have.

Agreed #1054 would be a better way to increase liquidity.
