### ISSUE TITLE
Fees are calculated based on max amount of XMR 

### ISSUE THREAD

**Issue by HardenedSteel** [haveno-dex/haveno#1056]
Traders are paying fees based on the offer's maximum amount of XMR to sell/buy. 

So if someone posts offer min 1 XMR & max 100 XMR on 1% fee Haveno instance, traders would have to pay 1 XMR fee regardless of how much XMR traded, which can result in paying 50% fee.

This also would worsen the liquidity problem.

**Comment by woodser** [comment]
The maker must reserve the trade fee based on the maximum amount, but the final fee is determined by how much the taker trades.

**Comment by HardenedSteel** [comment]
thank you, AFAIK it wasn't the case for Bisq

**Comment by woodser** [comment]
> AFAIK it wasn't the case for Bisq

Yeah it was a bug fixed along the way :)
