### ISSUE TITLE
Add button to duplicate existing offers

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1072]
This issue requests adding a button to duplicate existing offers so offers can be quickly created and customized.

See Bisq's code for reference, it should be the same: https://github.com/bisq-network/bisq/blob/e450c494bd68a901c4b85aa7ad45a0382b4fcf8a/desktop/src/main/java/bisq/desktop/main/portfolio/openoffer/OpenOffersView.java#L882C18-L882C47

**Comment by boldsuck** [comment]
I just noticed 'left click' with the mouse on Offer ID opens a menu: Create new offer like this...

Bisq has 2 options: Duplicate offer and Create offer (with shared maker fee)

```
Background information
By cloning an offer one creates a copy of the given offer with a new offer ID but using the same maker fee transaction ID.

This means there is no extra maker fee needed to get paid and the funds reserved for that offer can be re-used by the cloned offers. This reduces the liquidity requirements for market makers and allows them to post the same offer in different markets or with different payment methods.

As a consequence if one of the offers sharing the same maker fee transaction is taken all the other offers will get closed as well because the transaction output of that maker fee transaction is spent and would render the other offers invalid. 

This feature requires to use the same trade amount and security deposit and is only permitted for offers with different payment methods or currencies.

For more information about cloning an offer see: [1]
[https://bisq.wiki/Cloning_an_offer]
```

**Comment by monerobull** [comment]
I think fractionally reserved offers is a stupid idea that shouldn't be implemented.

**Comment by woodser** [comment]
We wouldn't implement the shared trade fee thing. Bisq does it because the fee is paid to simply post the offer. In Haveno the fee is reserved when the offer is made but not paid until the offer is taken.

**Comment by monerobull** [comment]
By "fractionally reserved offers" I mean having the same security deposit for multiple different offers. Imo that will lead to many failed take-attempts and grossly inflate how large the orderbook is in reality.

**Comment by woodser** [comment]
Yeah this issue is only to duplicate existing offers for convenience, but every offer still requires a separate trade fee and security deposit.

**Comment by monerobull** [comment]
But we can already "create new offer like this"?

![grafik](https://github.com/haveno-dex/haveno/assets/84282654/df2810a9-7e73-4673-bdc2-561b4fbfed2f)

**Comment by boldsuck** [comment]
On Mittwoch, 26. Juni 2024 01:28:45 CEST monerobull wrote:
> But we can already "create new offer like this"?
> 
> ![grafik](https://github.com/haveno-dex/haveno/assets/84282654/df2810a9-7e73
> -4673-bdc2-561b4fbfed2f)

Yes, that's possible. For example, I have a EUR/SEPA trade for €42 online 
right now, which I duplicated.

-- 
Ciao Marco!

**Comment by woodser** [comment]
This issue is supported by right clicking an existing offer or past trade and selecting "Create new offer like this".
