### ISSUE TITLE
Arbitrator cannot close trade if completed by the peers after dispute is opened

### ISSUE THREAD

**Issue by shortwavesurfer2009** [haveno-dex/haveno#1078]
Forwarded message from m

"if someone could tell woodser: arbitrator cant close ticket if the trade was completed regularly after a ticket was opened. the offer info goes away but it's still marked as open."

"trying to close the ticket obviously creates wallet errors since the funds already left the multisig"

**Comment by woodser** [comment]
If you go to the trade's info > Detail Data, it will show the trade's state, payout state, and dispute state. For example:

<img width="1175" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/46693fdc-7103-4550-a040-b0fcd6f46ae1">

If the states indicate the trade is completed, but it's still Open in the support view, that would be a clear bug.

**Comment by woodser** [comment]
Closing after bug fixes in the last release. Also, traders can re-open disputes if the final payout was not published with `ctrl+o`. Please re-open if you continue seeing this problem.
