### ISSUE TITLE
Can't delete an offer

### ISSUE THREAD

**Issue by zoudada67** [haveno-dex/haveno#1081]
I have an open offer that I would like to delete but there's no way to do it. I have already asked to people and they tell me that they have trashcans on the offer's line. I don't. Enabling the offer doesn't help. I have no trashcan. I cannot find a way to delete the offer and get my funded money back

Please see screenshot 

![Haveno](https://github.com/haveno-dex/haveno/assets/113605775/cec68a74-b2fe-4bf6-93d7-4064f9d782db)

Thank you for any help !

Cheers

**Comment by woodser** [comment]
It looks to me like the screen resolution is too low to display the entire line. It should resolve if you're able to make the window bigger or increase the resolution.

**Comment by zoudada67** [comment]
You're right I needed to increase the haveno window's size. Wasn't screen resolution I think but the haveno window wasn't showing the entire line

Thank you
