### ISSUE TITLE
Failed to sign multisig tx: This signature was made with stale data

### ISSUE THREAD

**Issue by 13597** [haveno-dex/haveno#1082]
Hello,

As a buyer, upon completion of a trade I get the following message:

> 
> Attention
> The trade protocol encountered some problems.
> 
> There was an error during trade protocol execution.
> 
> Error: An error occurred at task: ProcessPaymentReceivedMessage
> Exception message: -35: Failed to sign multisig tx: This signature was made with stale data: export fresh multisig data, which other participants must then use
> RPC request: 'sign_multisig' with params: {"tx_data_hex":"4d6f6e65726f206d756c746973696720756e7369676e656420747820736574016f67359f309dc1aa4fa014aef67774f377434617572d69d508c664978dfcce9243f8989c99ddbb1aac9296d2e94d7bf01181ecdab3c61037d5e92f0378420bc40da5a05d68b5f1761e85965ce9bccfbd373c7b1682f8c885d80025a64cad7849d7acdee7756d5bbb9555a3b0f645f1c37ce3131d932c9671aa0e2cc1f08a699a8c02c0385550f70ae20e8b6349b4d00a7940a375e99d6220f79f62843a5c40b4c9a5399512aba1f2c0c59f1e1289e5179844140544acc0a640a8e401b82b7fa44226c831121383de873cb115e7ca227abedcf11074e1df78aef550ab51dc3c09de6faa1a9b25e86d331f2ffa88e5b6c2ab6698460767d5d765336ab652e73e0455c0fc016c646d253b576843dbac87153ec4417e6f623ffbf0a3b615f1af06eb523c5429659135aca66a5ec0f2bcfcf3c483b9319a5f50dc233e99422ce82d4f362176b541e86547e26928516c6940128b5362e02bc33998448b290d2cd0f5ad750af9c0f66ed479ca23bf240179f774056b72b40e674f3b9174e97b94fb7cda34d6327ba3425accdaf4ab63c17532cf2eaef26b01d81b9e808968cdf7544a7e2f2ba5ef970f91bf2f7fb33eb907d302bcfb25be2490647180255e1908f89280e6355c59e38fe46922cc1d35c70a0e5a6b47b1214e96d0a5cbc83d86cd3f54b33cdd00e52839467b7557be41a6a0e5d48c3a64eb490906eab3cef6512add09d5968bae4414a4253f7c410dc0bb248b4dc234c6129b0a2332e2f05cc0cf1f6b4f2d56832654cdfbbe0abb776a1cbe5ffb2555ba1e369e4aa2ee4ba8497252bb028a9c153a454cbe830c8e10841a363df1b2e1caf05ce8741ac3a0d517b13f991cca238889eb6e0a1425402032d4a48277de773db0a130a982bee5140aadec0651560d62136f4de80e93bac7a05c08eb565c0a7e2cf1cb0258b275df065a7de04c1032a96a08400230999881a783fec8ebaab2335b2744037353731ac3bbfdb0ef6bcc7a2ddd061dd3c4925d9141e9cbea39f356dd000629bb21a59ff68692e018f9dcf2809904edc2fab5aac7b5456f5afb6a3f45cea5bd0741483fcc0d1c2c226e93dca793f3270e665981c5005697c04a69be865bec3ba6aaff1f043f125d473ef3eb8ae332d8fd3323067561c9eac7a7910222b7d2c7b1b9448106a0f77d57ea9f74a009350fb5e0a9a23f68253e81738ca7d31537cbbb731f519b8a7b13373b448dc85257956360ce97661342e444180bfdf1712ee415f59782abadae9e0ed7815012b9059aed5409ff85d078a4f22a86199b206fa8eb7cb1a3b5c2d733b6ef8d1833b8836ede590f61bbc07870003456807b79dc8e748a833df3419d69fb34a29b6de8d96f6251008eec390981937eb6a8e04255f805a8fea809bd4c2536baa4f1745bd48b3b8b10eadce338f844d7030dd0d9d5322eaa9e5edd550db68ea1f9b654c9d41eca4aba1182624ebaf22b8ac96cb8e2c64912dc1163b073ae9d6bbbe61390979c9711fa8005b8c5feea569a2c650deed815df22e6032588f40accf7716aa7d03a54515ae9ac5e4c7c84b785a08841f69ca6acefc92ec1bb38d7e366f4663473952add38355a2646bb0b5d29001950420a0ccafbfec9f97f5d2e99eca8190d2d7d25686337098882857c7bca683aed669e9475e64fbdb71b8fc2069c1a29757d8e5cb447629421afe94a9151333172ca4ea517111b682d414b04abee86d346eae40250c888015b73df06ebe870e22bcaed490c0fad67af0eba07b155006bb15bcd542db09ad43e9d55c22c27bc255cddb4994911c9036cb25427d4e869cadda70eef5df80dc8202f441bbae4e0b2b6154a198c9c9e0cc3d93197ce565b0533e1fcfb1fe678ca211b933486fd4425888aef52ef27a60ca8412a005926201ac1f7c8c59797b2d1e4d6a639356ba951129246bf09532c79328ec80799b182778c7bba9deb3da0a8355721c7ad53955685e2dea1cf85fdafd9a2a060ee4253c111158eb1a02322b6bf3587984a08783d2d11716dcca5301dd25fa7fdb7fa3cb6d630f7d9368037af73fdb2ca2b6dd04f92bf7d4e67f52af54a1d53154dd1e6d331a9c6d15a656d47409206bc209b1735a0b8385c505a6dd0f512fe09cd768c78253dc437066a68c168b0365ed0c8cacfdb335ee9edaa73163da76aa129108e1e342c935f5b051fd8cc9eecb38e1d12f8403e70b92d6c4379ed3e00358a30447d310ff2f4391b05e76c48ee94de2c33bd1cd8a3adf09b9c66b9c3162c0173cb0afc807161663f8ce7593d02599f7a73222da142cacb740ac6128a6b715a18bb8beb73daf74ffd44c6543f6e7eceea2fa76f763cc3239aaf747aa145aa4b978cf372ccb4b2ceef3afcbc5f0c82b25a297a360c7c9b54b2897058b1d29ca5adae0563360a32cf76de97fd4b1f0046483d2c09d6bccb8559443f689f2660939c924c347500aba60c3c167fb39525e6b2ec026536c6901b4424e328e22785f9770aa471c97cdf7d383403040c0a81cec917eea482d9d17ea34e1d4218a5a85025fa2f5f77f86d97c02e90b338c316ba941e5a08a1ab7ca93efc07faf5030e2fdd27f8471eca2ae17bf3e31d1b65b2c1c0d67e01bb37683eea23307a1d7fd2585b62cb41b8d04c78f26b5ab005038ec8e7042e721e3fe499da6b6c93e71156a009be99017eaa4b3a247097c9a1a98ec8540d5905157a7b4523eb3e66867e7f4674209c0a6706bab6789abad96f1a570afda604fabf47464aa2180893bc9caef765cb405492cac1959112fec63a55edd5f22a1569f8b330e2aa1c84a933ce2d620d1c8eb8567e5fa1e0825d9bd93bf6a96f0cd6c1383b93194584fbe091347f50a4a7354fc45e943fc89f102e32d5c50057c1144826a2547a6b777107c18e12c62335745c189c5cc50b75fbfb20f04f8abde4942bde79bdde19e56ad75590a96c41503c510a65725c3c669220a19147678f5bf0ecc1597c2c87e63be274907267dce2a9722d563734955f68daeac2a9d497779e71a004aa2302927488ad2340dfeffc2ea805d959f2e9bbf3c6387f2f0bbaa24c1b39a57d3d65b28415ca14ba29b28dc0f310910367723c6dc4928308e3c50529a8c066c13fcb0e9d7e30a2801b2182c8ec0dcf8c8a72d6fe5932854420564061fb20014d1e71cd2778aa5063cd61c45a35679c8891e7a5805b388f0667fab5fe7a3f07161193f93be35377c0576b4c0d642fcbe94170fc1349e554f1404696a0416689762f1e3e576a37ecce16a7358cf79309dfa21966fb587a09317ff19916b7a6f7538d47585c6245b9bf1b03e842157d84afcde7219d05a49902b3af83a4a677df320a8da71953ffe2d4ccf72fce2ba7eaa1b9f4a569eeece50b3bb107f5dcf25b597aa8822495c856202069f50185537f778e12596ff95505e72d27f586c7af78cd6ba8c486ffedff2508389ba0f389b30e8c3407e4c73b10dc3875ec6b6f593bbeb9778859d5e9dab8c13ce8b042899dcc292623047fad5e13545b59545a692edd72d74eee5cf85aa8cc66aa2e86a97ba0e10cf500e20952cad59a7ba44be32c9a9cfa098ad10cac3c8270be3f1613c8c46f2b3cdb32a7654705d42abfccd3ed095b8908f68a9ab3ec2dd9a712f65682d6eb82f3835e0d603c59e367b69cd9ce2e29f9484d46fadc95d7e9e2841f8acfdbfd2d5f00f125411a79120bf38922dcdcbc71104633e21d2926f29fdf20a44e2e2e6367f5d85b58749b6ef34f47a0acda05316d3b91967dea5f57c56431867dc5568344cd1e6f7a90d670f9d5ffbedad92f613f8d92ac3828654f0f26d9929db349c19cd41ab4d0a0de6a7a4fa6b3b99a198544725375bf0b987e90a68e16b7e2ce70e7867c32f19227edaeecbd7198ca266a152bc098ce453f38118b84d2b7909b7957e99daab1c86c9296e8a02397e1997438a6b050bfcb89437e0dec6b607924514218e6d0a3706f1f4ba40440b69a5b55321778d2180ed1c97c53087ad5fbcbf9af8d5eea8ed5c450ca8f6b020649843ca3f78cc3198f16c93ccbbf096192a0f31fe12dc9fc134c133a7ffdb7980b2b35ac3d91163971b337f454f422e13fe8d5db561a0e5fca052e75f28de92fc39887d04dde3041f6f09aa1d76632429046e01a2f8e70980321ee2650553107920577da66461a41b1fe38107b67eb9f4314c0dd95ca198b392da6f80d1b49a956f43c84421d8a4bca2b2811a228db455ed0f8d350d6bd826381568ed17eda20f6d0cce23ccb1c61a6821c2657e60caaac1666a6e036d2aa8f0492a4a0aab4878121246f76abc4139311e7a803a170b4035be0a94695e6bbc5311cc0fc8db7a75142a8c1a38471c5a745e6e894658a99a36ac981616ce77e26b58c9d3431952b307b9b1476487334ba57731cedd49599e4acf3adf80fae335feaf883949ed69c195eee42e3d2505573c320ba892ca4649fc1473ef88653f139895e1e0d7254996083339fbb6f98b41c531bf9c850d113505103b8ef313ac51cc41275c940734604c78340f17382079bff71dab6ed7cefa96120dd8046f4304a81bd36a61000b49288b3626ea26dbe517b3ac50a1ab952ed08d4ef382500e2909e674bcd78fc1f4fcf333dd6d77ebee350adba61ba3c994e99f0fc4e7c2cdb3636e95f542142008a4c74154de87d7a45ad47ed0d6940c0feb7e52a6decfb11073ba1dfcb14a8aa9d025ae6c58f3a72603fd312879c43d2244da11daa36f0252d4d04170c61f6e623a6ae5d918ef07e2a1783ea71dc7d2c954c92809c42041666646c911ca84d3006447b39eb22fcf088d9f42cacc3ed11523d29161aadbaa7e587db3c88606e7970e85de2e7521db01b1df21ed24481a423745dad35e991035275f486ae8c805724c8d83af7ad98b8b0f44755cc5841b8fa6fe77abad6a963154484f3b2779c1ed9b7635a68f088d6d50a9c55a169cea9dec7dc0a3799be5d88da437add33a42d91a32c1642748e97c0665b5edd8dbfef2535ce59c3c1de100d55227b46360b9ff5043002f1076ff892d93fcb4c6beb1f4b183d522e6a84fff8e51f70945d3ac659653ad8348c3e23850f1317dde656c2477109f2929b0ad0947ac8577f1799c6605c27e58d1ea71699af2a113e6efad8f3063db8a555090f8b0b7871259673ea5cc5790ca9b3e992bbbd0ed67cb45f7c7c6c76732c666cf73ca1080b3842dda4f6b2ce97f1953bcfa58dfab39a4d4778f954d9ff87ae2fd58dde841997d10b01ef720ef75af303499e0e64c5d1ea24b1d1d0af8c7e7f471231b5e94cd63727995b62e3ea204ae5f9a53a50f624a4dd78c2e03f73c121925f331c8f0897a6f9cac33ca11eb1fd1bcdc3796a541b2af8e6a426235ff0cc31599e28720638025400bc8ff7cc1418545f86d7b8626ff986c13718cd4ea0acee28952c5640898ef9e1a9ba4fd9cf33410258812dc2d09342b26ee8e2a3002215e402de9d9ab22276ca5c509f35d5796d668c0b67b53e29ffa940b0861680d45d17ac38a4a43b0354945f99dd685019f21b64833e27a6607e8766ac330963ca415646e04f4e633da87e02b92657b998b591097dda220a6e247ac08fcc878e42e047131249bda3b8155ca011e6f51aebc0ef226c3feb9fabc48ef69e8387783f018771fc50ece83aa9f8fb4993787da8d6df890717f191ba84d2f5478184840773e1182ac95fde1630680e3b13ff5ac08307491fb02f6cf9461cdafcf7a97e9dd80a97163b8818a9695553433660eb2baf069589d05de89651cf73de07ea20d2ba8beaac557ebb85a503b59a03604526eeb49ce17bc5f2dbfbb340fcdf09819423ec61b2926ebf460424c04fcae7a11ec41dd2c98d80e5ec4e73619a8abf13b015bbe18fcc1e17f43f79bcc500b334e7f4432fa7b801c765a0db866cdd82c4c5f6c291efbddd34d511da4c3efd25e538efefabf729c833be6f28fbccecc955678c5c0e5ffbf1ac47154de768af45725db19ee3e350c985a04afdaae769efd59e5d08b52ad1526999a22ecde869db93cc0f3f349429cedf3e0242c179aa3e77331ed0cff52e8073c1dc32585e00189c952524c8307efc98cb93a33f0e21edc9151c0f55919c43bf8081a36f5e93e1160ea5c74d9a80ba619ec860b9d30ec9b5c37f748d1ab498c18a4949b10668ae6993fb1ad7abc678a86250b24dccbc2ca321f32e1acc8bf59334f25fd646a5a9666af86dea4f63e4f3e4d8b68f25d28723873d428cbb0bce2e4b223d423d1f2219c4b5ddb5519f79afd7ad677711b398416cb36ee5f7b3d5183444be67031970d4ad42f510e40367d8a1cd62eec5dd202bc6037758b39014e63962b1fd404473d6980c6bdb9cccc58a087d33802f0ac3512b7c32fed18ca39859012f8e96d2dfbb66786634cca0bdffad06f3f755814b0bdd285d19f21114ddcb6c728bdb8a6455e7b7f18e8b0e4f82d201aceaf7971b58bcb75ee7d0a3d40bbcaab68d1c0d35204f2345fce834c67d04c611977510fb8cd98c3f0b7bc18777f110c28b5cd0452ed6d0d04e01697945efb15ef0d5da88098a19751096ee2d84a8aee7123dc2563ed3ead452a5dbd42a8530e16eb50ac03623838ba9d7b83408e158227400823100fd2828afc38090472d5049b4e314044d3cced26ca831aa0711bf4ced5f6f388ad84ff20b94bc4784333f5c0cb3012ff206a22906a2bd1c76f479807c05375f71786d431b5ad0e2ebb09db44db6a2661be49aafede7d4fedb1d3165a935d4a3972f9205fb7a61d8a8ca91f0eab3526bbafe2b8d18f88c08098e43a86e20e478413b3f512ee77db1cd2420fb97ff1001ae48bfa71f4184a62c877b5c5461014de8fefc371420a415049bc3c8438f6cc87121bb9b895e05984f987bd1e360bbde2424d269ede834365a7753967f2bd1b9c40b87ceced66de295c75257d07f2c502aa59489f60c71fb0552b21cbf6da735e9221f44b3298a0d5ed43d237c7ef5cf9c5d5ec0a97a6dfbbbacc7fa9c7c1bdb91228e18b1ab77da73966ecdf66fc0611f609ac3e671dcc5441af84f138512e6255cbba4e4bf4c4d74aafb8d16c8dcbdb539a0b511c91faed809146cdd4e718c3f7abe96981a2d400a30b19d8e696a6acec79c48ccfaa4a30f774af4dbb2e0f0415ad2a62a239c315859ab959b129f96f11ec97c787f9883852144e9260bd61ad8482919d2ffa28e0c8ab724c91a3225c4277d36798ebb1821b0e23670bc812eae16e07f2226d38ad1349dff32781a60e87d5f79fd4f074d12989495865ada05246ea3f9b18b3053315663b5acd23f2f4229262b53e5ce75a81a195e233142724da269a0a0f8dbe6992c0465610a41e7c0882493b9d05320cf3cb9bac9373ea54d1ab307428647c72791b367ce8913eec0314e0fd48f2e7eaa0b0181c30fe36537da892494dc412d2451ebe01f0c646bfcc430355ad71a68288b84efcdd534d068dfb651a7fd718ba407c485fd1426bc82b73891a5150562e3af7ce8b0c4faed583d737622c1c8b25d8382ea83e824845fe6616114b5944d4c64ceb7452e9b592130d664ceb01661c19b79a4273e6a2a35a445da9f012276ca829cb7d125ae43d915284d4deb379cd0ea0cc1e2e04532e07de9bb559d174a9784f04a40b4b905fbf115bf753116cfc83723cb3bef10501abe1bcb5ef353b74b385069f7a9b69661e1c9c8bbad89d1d26f292b6f4e7837772cfa4500e43d1864170d08e6ecce57f071b19130b382a5cebb13fa46db0a7cc95e818f04299ac1aa60123c416b512980ea70fb19b606f1054f90310059c4bf4516a5d6d969458562c0d8e1c1046a3036eb94f4c0754d4c06a4ecd21570e1936be87c43d21373a3e72bc560d08897a38e2b2f5306fac70e1a752e588121323bd494baf2a0aec6647844c7bea255b58ee5fa85b9b529133726e256d45ad84bdac98ea7f82126ebc065f73fb361590a86157cea9d58314b9237937369a33f90053816002b06310d6ad135486e16549ef7be209ced6bb770cd65b43eb6c86f1821cb5ef5442d12dada3639bb26e93096d7cb098bc3a82254c43824ecd3d4ce2cf0d74a8c63010bb53b31734849015bbffaad1960806c79213da51b1bb481e552fa3aa5000ee52b84ea593975f9562867dd32b100aff242df1c7da2cc28fab391e5b0217e0f1688de8e0e02b0d96663a44291122f667f388d91558c1c6fffb44d2f068f1b0e4439a938844f8555d02476cfa09df7ee7041298f1d44056d89a5d7b30d34ba8000a14f62dd753057ab4b7fbb681ff7164f6a877bbec9ae12dd7a801137881e99eb30648ddc0226548cb38c0f2048b0fcbffd32f3581e9b8df7617d31939cc7ba2f3c1fd5db3d2aa93aa16c981af0295b4a21d56f112284ae307d905d971ebcd71a344ae5bd1167292ba01b33a320a7adcbda7432ff8380c30eb7eef73cd737d359c33e142c6cb9a2f29bdf89a05179480d83fe39b21f530161cd6fcb7e2edad3ec828bc904fbc6b260e4d5f88e402c9a10815355069efc75787dcb450f1dee5c70f01ac9d847553b28b8441135edabcba0ce7a77d37463490e720528963ca425487c34d2914875f6aab4cb96424f1c4ac5d6ea4b1e863d1fb234d8120a98d93cd56a370a5eb613749696351fb1b5ab3b3455fed76ad14d23f9ae9567c7caf5562dee71cd5f398ab1fed65dd436912bff57f4c1cc32615ab7f3d24851a62c39192804cf46ab36054c6386c9729f6c79857bc1adb30fc67d919c38718f57a5ec66a459c383a17dfc2347b6edb909543e603ab431b0b8ec77149d4b6a79e4c16fabea6fe4039e527452ed72df2e822660df38c09f9407874717782a926ed6c7a1b40dcf1c53e0d659f85520dbde2c5334eb769a8ce28125e5d723711840758a6e221263ee03dcb72645ed088146d9fa94cad6c6f5d5ef55024295b84de3875b778e41035af931744f0dcd2e4b4be511b4ab1bfd95c1a4b54091337ae52807030e38f8a956391857d6d7cc89cada089b591c32076da84bd81bd4f40434dee3acec223a45be439c77c4384a37073a07569833fbe30aa2a091ccdc659df6c15af9117a9a084d1d0f8e48faca52e0051febc7a356c5c268e062a94268211863f0ffd52e24addf682d0fb46707cfa794ec69ca4baf1338aa0b391fa553622c0044716a303e9fc1e7c2827482898207c216ab6b487b4d9d317f41d8f62fd687fbe32d6c6a5b969f8e31b9a7bbc7707a4a432754d2bce9e3f2bfb7af5592d26c9414e2a0b6bbe02c0b708f9d743f96e8dd887c26247dada8b1bc523a7a6e4247d957d3c19590bdce285a37425af85a4a87d7d3f14cf9e7db3882f2bedbcac978573cb4744fcb2e26c51c36f13df95da45fd721a4ccb36fd6286a62f4044ff4820f5cef54ad336180e40760b8fe19c62b3d92fa08a5ed4959fc99db895570bddcffcc22c99103138cc14ebafe7d42f5c5e41c8d8ff998c3fb362f4b8c972d771be3a9348a7a56284c185c70cd57195fec75f2e7ae8850460d859327edaf60a08750ddaf1f29822cb2d2a3c42e0ff2619d76ad419f036e0ca952af5db9e142a6335f4ed1ba0b5ce1ac7f82cceb32588c6599b671c97ce4016df8439aa2d03a72a799961eced580c27647859f8ecbeac4ac750218ecb4ac45002515118f107acf2fc19f4eca77f523f091fe54706a0a3f48b9637763c3f4979cc5e3d73d7723e06fa6fd57b69a9c1f8a4247d7971a8c82f816e2aef167a237396253c55746be8c8252922048fb917ccf183fc066cd880c70bc18ad778e956dd547b3e05a7bd32d7a193aff7b8d80d0a17973405ac756286e4b462e37fff7e69c9ce30e3fa53869cf35ac21037553e3eae2c6b5b9051a03eba3d3d7fcce36c2efe3a9043626db6553162a4badb97775e0d7f81b9015cf06f238abcb1530111f3bde5de275718a04ebdb8c2aa615d39f9326876af67176b1fbb512a005a3cab6d9c07978e9ec12acee702ab02989223f23e28023243b3f605ff696c3d4d9448d1b9e39d5939fc6a8ed232e144df37acd50f73a724169bd678fb502ab82cc6d58c777762f2da9e797d25e074599dabd9f7b88f15f2c1d2df13eed5ed0e27841b680582f717ec1127e500c9ce0517f6119bd328f08596984217122bd072a1694ae54dbe718b6d2e3362d59ede94d1c9659afa3cfa17f10a9bbfabdec275fe3a4a859ad68e5c6d325b283ec34e69a81c6e62028e5e956d82d6a72e06fae7319ff8e2d9f40e523b3d57f80645442b005231be59e87f22dcc37d64235525eb91c0752a9f6d777386010d0a5d2a51c597aefb9985f9c4bfab71e2a4b7f930083b9220fae8ef6c2aed8408618b8a5df5afe3856ee7e4ee65295bd4a359be868b94a57230eedeef1371491ef4d602f374de5bbff4b40d3af846731225cffda825717897baf6dd82048270536099a85631080105002277b2a923183eea8c15960b018a56e8170535df9859b35a7770afd0ea005b949f3dff0d0dbeebccb5364f65ca7b10b27d92edad19b3b8d7a427241d4037129d40890455a5de12c08f6058dc1fc96d8bbe98a05ff8cf1e2eef901a55d0bcd86fcc6aa8300e72e4a9a973884bb2a725250cddb5779f43a1e4c52d4a205ea42262308926fe467cef8060835ee93209e32f072844c05d49f3a785df493485de2e36687819b8dab0bd75b3c29a87dfb9ce482daf40dfe24e690793fb41c711308c63a79e9609c2c031289421ac0ef863d268b5aeeede81cb9934b62e38fb3edc9dd16eb9a264a78d073285bc6334a99ffda84145aef7a0b6a85e564c34025f99a70bd88b9d19b3b3a6444fb4601725f56bb6c672595e1aceea2ba02d82386b02fb6596ffbe63a6517bebf514186341b9dd0976c49a843bd9faa2b1bdac1bfdd982bbd90150a9f52b74d4ac8138dc977f56ebf69439ca8a059723894dc06e1ed92987ba38f96786b94f7e9f3f815988e68dfe144b9f4519deb5890577eb2dbbe6b2d4e1fae6bfbf5d7eee241722c2a18f5e19e687d470c69fc1d50d5083bc7c5f57461d7920714e42aea16050555ce4dff9c61e083bfa13b0def9053fca9918714b0a1c2f0a5a1ca8851613f786084bf9487ec8ad9d0fcf3dee6075e01c4892fb72b03c0f5ff8c0d26eb052c82116ef52d7acbcf9f1b1aaceb6eb05145846b11c8096638e7544b668d337a3c7f8d04fa9537a9f2ad551acd71076706342ed7d3d6bfc44a9bd94836184d295ad14308"}
> 
> It might be that this error is not critical, and the trade can be completed normally. If you are unsure, open a mediation ticket to get advice from Haveno mediators. 
> 
> If the error was critical and the trade cannot be completed, you might have lost your trade fee. Request a reimbursement for lost trade fees here: [1]
> [https://github.com/bisq-network/support/issues]

**Comment by woodser** [comment]
Are you running 1.0.8 and was the trade completed successfully?

It should complete successfully in 1.0.8.

**Comment by woodser** [comment]
This was fixed in 1.0.8. Please let us know if you continue to see it after updating.
