### ISSUE TITLE
[Question] Python module

### ISSUE THREAD

**Issue by sjehuda** [haveno-dex/haveno#1087]
Greetings!

Is there a Python module to interact with Haveno?

I am an XMPP developer, and I use Slixmpp (Python) as a library to develop chat bots and other type of software.

Kind regards,
Schimon

**Comment by woodser** [comment]
No, there's a [TypeScript client](https://github.com/haveno-dex/haveno-ts/blob/master/src/HavenoClient.ts) which binds to the gRPC API.

A client would need to be created in python, which gRPC also [supports](https://grpc.io/docs/languages/python/quickstart/).

**Comment by sjehuda** [comment]
Thank you.

If someone is interested in a Python library, then I would want to know. I might be of help.
