### ISSUE TITLE
Error: An error occurred at task: BuyerPreparePaymentSentMessage

### ISSUE THREAD

**Issue by surfninjas** [haveno-dex/haveno#1090]
Haveno v1.0.8

I'm getting the following errors associated with one of my trades: 

```
The trade protocol encountered some problems.

There was an error during trade protocol execution.

Error: An error occurred at task: BuyerPreparePaymentSentMessage
Exception message: not enough money

It might be that this error is not critical, and the trade can be completed normally. If you are unsure, open a mediation ticket to get advice from Haveno mediators. 

If the error was critical and the trade cannot be completed, you might have lost your trade fee. Request a reimbursement for lost trade fees here: [1]

[1] https://github.com/bisq-network/support/issues
```

and

```
The trade protocol encountered some problems.

There was an error during trade protocol execution.

Error: An error occurred at task: BuyerPreparePaymentSentMessage
Exception message: not enough money

It might be that this error is not critical, and the trade can be completed normally. If you are unsure, open a mediation ticket to get advice from Haveno mediators. 

If the error was critical and the trade cannot be completed, you might have lost your trade fee. Request a reimbursement for lost trade fees here: [1]

The trade transactions have been published and funds are locked. Only move the trade to failed trades if you are really sure. It might prevent options to resolve the problem.

Do you want to move the trade to failed trades?

You cannot open mediation or arbitration from the failed trades view, but you can move a failed trade back to the open trades screen any time.

[1] https://github.com/bisq-network/support/issues
```

It occurs when I press `Payment Sent` in my portfolio. I get the blue circle motion for `Preparing Confirmation` next to that button and then this warning pops up:
```
Sending message to your trading partner failed.
Please try again and if it continue to fail report a bug.

An error occurred at task: BuyerPreparePaymentSentMessage
Exception message: not enough money
```

**Comment by woodser** [comment]
Can you find a related error stack trace in your logs, or share logs for investigation?

**Comment by surfninjas** [comment]
happy to! do you know where they are located? I'm running ubuntu 22.04 LTS.

**Comment by woodser** [comment]
~/.local/share/Haveno/

**Comment by surfninjas** [comment]
got em! see attached.
[haveno.log](https://github.com/user-attachments/files/16074914/haveno.log)

**Comment by woodser** [comment]
I'd recommend restarting the application and trying again. If that doesn't work, switching to clearnet in the network settings, or starting a local node. We've seen this lately, not sure if it's related to a specific node.

**Comment by surfninjas** [comment]
I shutdown haveno, restarted my machine, restarted haveno, and got the same errors.
How do I go about switching over to clearnet in the network settings? I can give that a shot.

**Comment by woodser** [comment]
Settings > Network Info > "Use tor for Monero network" > Never

**Comment by surfninjas** [comment]
It appears that switching to the clearnet allowed me to press the `Payment Sent` button. However, the error icons still appear in the open trades list of the portfolio tab.

**Comment by woodser** [comment]
Yeah that's expected after an error like this, but trade should proceed fine.

**Comment by surfninjas** [comment]
Should I leave Haveno on the clearnet until the trade clears? Feel free to close this issue if it's something that is being worked on.

**Comment by woodser** [comment]
Probably it's fine to switch back to the default of switching to Tor after synchronizing the wallet on startup.

We can leave this open until a fix is submitted, since it demonstrates a weird wallet state which resolved by switching to clearnet.

**Comment by surfninjas** [comment]
sounds good. Thanks for the tips!

**Comment by boldsuck** [comment]
@surfninjas This is due to a bad connection to the RPC node:
`WARN  h.c.x.w.XmrKeyImagePoller: Error polling spent status of key images: org.apache.hc.core5.http.NoHttpResponseException: xmr-node.cakewallet.com:18081 failed to respond `

The best option is a local monerod. If you don't have one, find one in your country:

- [Public Monero Remote Nodes List](https://xmr.ditatompel.com/remote-nodes/)
- [Public Monero Remote Nodes List](https://monero.fail/)

You can start Haveno with command line argument `--xmrNode=` or set the option in Haveno's config file
`~/.local/share/Haveno*/haveno.properties` `xmrNode=xmr-example.org:18081`

For more haveno-desktop options see:
`~$ /opt/haveno/bin/Haveno --help`

**Comment by shortwavesurfer2009** [comment]
You can also add a custom node in the GUI by going to settings > network info, clicking custom and enter a node and port like example.com:18089 in the text box and restarting Haveno

**Comment by boldsuck** [comment]
Are you sure?
I have a whole list in the GUI associated commandline option `--xmrNodes=`, but none of them are used for the xmr wallet connection.

**Comment by shortwavesurfer2009** [comment]
)thats beyond me

**Comment by woodser** [comment]
Fixed by https://github.com/haveno-dex/haveno/pull/1102 and https://github.com/haveno-dex/haveno/pull/1156
