### ISSUE TITLE
ui improvement

### ISSUE THREAD

**Issue by XMRfamily** [haveno-dex/haveno#1094]
Allow people to filter trades if they have trade ID or onion address , it will be hard finding ads when it becomes more full the orderbook

**Comment by wp07e** [comment]
Easy one! (I think) I'll take a look.

**Comment by wp07e** [comment]
Looks Easy! (I think). I will take a stab at it.

**Comment by woodser** [comment]
Yep, done :)

**Comment by XMRfamily** [comment]
:)
