### ISSUE TITLE
PayPal Payment Method, Friends and Family or Goods and Services

### ISSUE THREAD

**Issue by username-unknown1** [haveno-dex/haveno#1105]
there are 2 different payment method with PayPal, is either Friends and Family or Goods and Services.
User unable to tell from trade posted whether the payment will be made in Friends and Family or Goods and Services.

**Comment by woodser** [comment]
Should be fixed by https://github.com/haveno-dex/haveno/pull/1103, which allows putting additional offer details.

**Comment by woodser** [comment]
#1103 is merged
