### ISSUE TITLE
No arbitrators available. Cannot make any offers

### ISSUE THREAD

**Issue by superhans65** [haveno-dex/haveno#1111]
Is this a feature of this software? That it can only operate if there are arbitrators?  How come there are other offers listed when there are no arbitrators available?

I also cannot take any offers.

On startup, I get: Warning
We did not receive a filter object from the seed nodes. Please inform the Haveno network administrators to register a filter object with ctrl + f.

Happy to report that withdrawing from the exchange works fine

**Comment by balz666** [comment]
Same problem here : 

![image](https://github.com/user-attachments/assets/b1eddf09-0bd2-42a7-81d4-35314361b733)

**Comment by woodser** [comment]
Closing as it's related to connectivity issues with a third party network. Fixes were made in the last release to improve connectivity, so first try updating.
