### ISSUE TITLE
Add IPv6 node to haveno-seednode.service

### ISSUE THREAD

**Issue by shortwavesurfer2009** [haveno-dex/haveno#1125]
in /scripts/deployment/haveno-seednode*.service and /seednode/haveno-seednode.service

\#  --xmrNode=http://127.0.0.1:18081
  --xmrNode=http://[::1]:18081

I have mine running with this and so far it appears to be fine

**Comment by shortwavesurfer2009** [comment]
I have never done PRs otherwise i might

**Comment by woodser** [comment]
> I have never done PRs otherwise i might.

Just to point in the right direction :)

```
cd ~/git/
git clone https://github.com/haveno-dex/haveno.git
cd haveno
git checkout -b fix_ipv6
<make and stage the change>
git commit -m "update to ipv6 address in seednode service"
git push shortwavesurfer2009
```

Then you'll be offered to open the PR when you visit this repo.
