### ISSUE TITLE
No filter object from seed node

### ISSUE THREAD

**Issue by IssuesPlease** [haveno-dex/haveno#1135]
Just downloaded v1.0.8. On logging in, I get error message "We did not receive a filter object from the seed nodes. Please inform the Haveno network administrators to register a filter object with ctrl + f." Says "Synced ... at block 3191865" but also "No seed nodes available." Market appears empty. How fix?

**Comment by woodser** [comment]
For mainnet, you need to build and run a third party network or [create your own](https://github.com/haveno-dex/haveno/blob/master/docs/create-mainnet.md). It's not pre-configured in this repo.

**Comment by IssuesPlease** [comment]
> For mainnet, you need to build and run a third party network or [create your own](https://github.com/haveno-dex/haveno/blob/master/docs/create-mainnet.md). It's not pre-configured in this repo.

Is there a repo without this issue? Will this be addressed in future builds? Thanks.

**Comment by woodser** [comment]
Yeah, find a third party network with this configuration already added. Maybe in the future the project will support adding third party config within the main app.

This issue can be closed.

**Comment by woodser** [comment]
Probably because seed nodes have been getting ddosed. That's specific to a third party network, not the main repo. They should reapply the filter and the next update should help with ddos.

**Comment by monerobull** [comment]
> > For mainnet, you need to build and run a third party network or [create your own](https://github.com/haveno-dex/haveno/blob/master/docs/create-mainnet.md). It's not pre-configured in this repo.
> 
> Is there a repo without this issue? Will this be addressed in future builds? Thanks.

https://github.com/retoaccess1/haveno-reto

**Comment by boldsuck** [comment]
> I have been getting "We did not receive a filter object from the seed nodes. Please inform the Haveno network administrators to register a filter object with ctrl + f." with haveno-reto 1.0.8 since yesterday.

Click away the message and let the app continue running. The app should have found seed nodes in 20-30 minutes.
Then it is best to let it run 24x7

**Comment by woodser** [comment]
Closing because it's related to connectivity issues with a third party network. The latest update should improve connectivity and reliability using proof of work defense.
