### ISSUE TITLE
Support deleting payment accounts over API

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1136]
This issue requests the ability to delete payment accounts over the gRPC API.

It should be supported and tested in the [haveno-ts](https://github.com/haveno-dex/haveno-ts) client.

**Comment by wp07e** [comment]
I'll look at this one

**Comment by woodser** [comment]
Fixed with https://github.com/haveno-dex/haveno/pull/1151 and https://github.com/haveno-dex/haveno-ts/pull/299
