### ISSUE TITLE
Still some log spam

### ISSUE THREAD

**Issue by shortwavesurfer2009** [haveno-dex/haveno#1164]
ul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.561 [InputHandler-dddd758d-b68...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.561 [InputHandler-af5e2332-bf7...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.575 [InputHandler-3cdf6122-033...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.575 [InputHandler-3cdf6122-033...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.575 [InputHandler-34965351-8da...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.575 [InputHandler-20ca57ac-a01...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.575 [InputHandler-624e8abc-2b2...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.576 [InputHandler-3cdf6122-033...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.576 [InputHandler-624e8abc-2b2...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.576 [InputHandler-20ca57ac-a01...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.576 [InputHandler-34965351-8da...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.576 [InputHandler-34965351-8da...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.576 [InputHandler-20ca57ac-a01...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.576 [InputHandler-624e8abc-2b2...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-be09a281-beb...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-d17e6798-373...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-bd2371d7-b9c...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-4e4b53db-7d5...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-be09a281-beb...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-bd2371d7-b9c...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-d17e6798-373...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-be09a281-beb...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-bd2371d7-b9c...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-d17e6798-373...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-4e4b53db-7d5...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.591 [InputHandler-4e4b53db-7d5...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.624 [InputHandler-39d3c198-0e4...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.624 [InputHandler-39d3c198-0e4...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.624 [InputHandler-39d3c198-0e4...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-82f8e455-7b0...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-63929d1a-a05...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-261f149d-2ef...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-05e7fdcc-078...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-61899662-69a...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-dd2e7979-51a...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-82f8e455-7b0...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-05e7fdcc-078...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-261f149d-2ef...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-61899662-69a...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-63929d1a-a05...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.633 [InputHandler-261f149d-2ef...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.634 [InputHandler-61899662-69a...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.634 [InputHandler-05e7fdcc-078...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.634 [InputHandler-82f8e455-7b0...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.634 [InputHandler-63929d1a-a05...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.634 [InputHandler-dd2e7979-51a...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.634 [InputHandler-dd2e7979-51a...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.635 [InputHandler-ebd34ba3-755...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.635 [InputHandler-c79d8368-d28...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.635 [InputHandler-ebd34ba3-755...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.635 [InputHandler-c79d8368-d28...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.635 [InputHandler-ebd34ba3-755...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.635 [InputHandler-c79d8368-d28...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.638 [InputHandler-0a34634c-f36...] ERROR haveno.network.p2p.network.Connection: Protocol message end-group tag did not match expected tag.
Jul 21 09:15:57 miner1 Haveno-Seednode[1882506]: Jul-21 09:15:57.638 [InputHandler-0a34634c-f36...] ERROR haveno.network.p2p.network.Connection: Protocol message tag had invalid wire type.

**Comment by woodser** [comment]
Maybe you can track down the log spam log and fix, from here?

https://github.com/haveno-dex/haveno/commit/e8e4e8d94fc70531cf1f3c3fd5b6a25ea7073c1b

**Comment by woodser** [comment]
Guessing it's one of these lines. You could comment them out to confirm:

https://github.com/haveno-dex/haveno/blob/629e1508f2251d7d2fccb94d06d72d0be4e0be0d/p2p/src/main/java/haveno/network/p2p/network/Connection.java#L547

https://github.com/haveno-dex/haveno/blob/629e1508f2251d7d2fccb94d06d72d0be4e0be0d/p2p/src/main/java/haveno/network/p2p/network/Connection.java#L886

https://github.com/haveno-dex/haveno/blob/629e1508f2251d7d2fccb94d06d72d0be4e0be0d/p2p/src/main/java/haveno/network/p2p/network/Connection.java#L882

**Comment by shortwavesurfer2009** [comment]
Do i need to rebuild with `make clean && make skip-tests`?

**Comment by woodser** [comment]
At least make skip-tests.

The build succeeds before making any changes? Commenting out the lines shouldn't cause the build to fail.

**Comment by shortwavesurfer2009** [comment]
Well, it does. Unless I'm commenting using the wrong syntax I was using it with "#"

**Comment by woodser** [comment]
Use `//` to comment out the line :)

**Comment by shortwavesurfer2009** [comment]
confirmed the line causing the tag logs is 886. there is still some more log spam but that fixes more of it

**Comment by woodser** [comment]
Great. Can you give an example of the remaining log spam so we can target that too?

**Comment by shortwavesurfer2009** [comment]
I used /*...*/ rgat i found on the interwebs. Should I paste the log spam here or should I open a new issue for it? Since it's a different spam?

**Comment by shortwavesurfer2009** [comment]
Jul 21 17:19:37 miner1 Haveno-Seednode[11332]: Jul-21 17:19:37.981 [InputHandler-c0d881c1-632...] WARN  haveno.network.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown.
Jul 21 17:19:37 miner1 Haveno-Seednode[11332]: Jul-21 17:19:37.981 [InputHandler-543cc485-6dd...] WARN  haveno.network.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown.
Jul 21 17:19:37 miner1 Haveno-Seednode[11332]: Jul-21 17:19:37.981 [InputHandler-1f0f73d7-43f...] WARN  haveno.network.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown.
Jul 21 17:19:37 miner1 Haveno-Seednode[11332]: Jul-21 17:19:37.981 [InputHandler-6843c087-41d...] WARN  haveno.network.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown.
Jul 21 17:19:37 miner1 Haveno-Seednode[11332]: Jul-21 17:19:37.998 [InputHandler-9cb221e2-85b...] WARN  haveno.network.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown.
Jul 21 17:19:37 miner1 Haveno-Seednode[11332]: Jul-21 17:19:37.998 [InputHandler-418f6b86-c03...] WARN  haveno.network.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown.
