### ISSUE TITLE
Increase size of Haveno desktop icon

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1167]
This issue requests making the Haveno icon bigger. For comparison to Bisq:

<img width="43" alt="image" src="https://github.com/user-attachments/assets/7129a5b1-7fd5-4100-9cd5-cbbf710e5c7a">

**Comment by phytohydra** [comment]
https://github.com/haveno-dex/haveno/blob/master/desktop/package/linux/icon.png

The source image just needs to be cropped to content before generating the icons for the different platforms.
It's 506x542 but padded to 800x800 with transparency.
Scaling the whole thing down makes it look too small.

**Comment by phytohydra** [comment]
Apple macOS Icon Image (.icns) tools
https://sourceforge.net/projects/icns/

The Mac icon is actually 1024x1024x32, but has transparency around a 647x693 core.

Somewhere there's an SVG version of the Haveno logo, but who has a copy?

**Comment by woodser** [comment]
> who has a copy?

Here are the original logo artifacts: https://github.com/haveno-dex/haveno-meta/issues/1#issuecomment-819741689

**Comment by woodser** [comment]
Fixed with https://github.com/haveno-dex/haveno/pull/1172.

Thanks! :)
