### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by richie115** [haveno-dex/haveno#1183]
so i get to step 6 and enter
sdk install java 21.0.2.fx-librca

but it says command not found can someone help me?

**Comment by woodser** [comment]
You should be able to run:

```
curl -s "https://get.sdkman.io" | bash
sdk install java 21.0.2.fx-librca
```

Perhaps try running in a new terminal window?

**Comment by richie115** [comment]
> You should be able to run:
> 
> ```
> curl -s "https://get.sdkman.io" | bash
> sdk install java 21.0.2.fx-librca
> ```
> 
> Perhaps try running in a new terminal window?

i tried runing a new terminal and it still didnt work , i even tried restarting from the beginning

**Comment by woodser** [comment]
This appears to be a common issue:

https://gist.github.com/masudcsesust04/3c8ba2390fcd49e61851e92ea19907e2
https://stackoverflow.com/questions/45392965/sdk-command-is-not-found-is-coming-the-terminal

**Comment by boldsuck** [comment]
On a Debian system it worked like this for me:
```
curl -s "https://get.sdkman.io" | bash
source "/home/user/.sdkman/bin/sdkman-init.sh"
sdk install java 21.0.2.fx-librca

```

**Comment by richie115** [comment]
> You should be able to run:
> 
> ```
> curl -s "https://get.sdkman.io" | bash
> sdk install java 21.0.2.fx-librca
> ```
> 
> Perhaps try running in a new terminal window?

i opened a new window and it took the curl command but its saying that i need to install unzip file and then restart

**Comment by boldsuck** [comment]
> i opened a new window and it took the curl command but its saying that i need to install unzip file and then restart

Yeah, I had that too. After install unzip you get the message with 'source.'

Note: If you only want to build Haveno.
You need JDK 21, but it doesn't matter if you use openjdk, oracle or sdkman. ;-)

**Comment by richie115** [comment]
> On a Debian system it worked like this for me:
> 
> ```
> curl -s "https://get.sdkman.io" | bash
> source "/home/user/.sdkman/bin/sdkman-init.sh"
> sdk install java 21.0.2.fx-librca
> ```

im on ming and when i put in the curl -s "https://get.sdkman.io" | bash
but it says i need to download unzip and reinstall on new page but what does that even mean

**Comment by boldsuck** [comment]
Have you now installed unzip with your distro package manager?
This has nothing to do with sdkman.

Generally, are you sure you want to build Haveno testnet?

**Comment by richie115** [comment]
> Have you now installed unzip with your distro package manager? This has nothing to do with sdkman.
> 
> Generally, are you sure you want to build Haveno testnet?

thats what im having issues with i dont know what or how to install i have tried a few different ones and nothing worked also yes im sure i want to build the testnet

**Comment by richie115** [comment]
i fixed the problem!!
