### ISSUE TITLE
Check what git lfs is used for and get rid of it if we don't need it

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#12]
Bisq was using it, but we probably don't need it as it seems to be used to store DAO-related files. Files stored using git lfs:

```
f485f1a26f * p2p/src/main/resources/AccountAgeWitnessStore_BTC_MAINNET
0feba11eb9 * p2p/src/main/resources/BlindVoteStore_BTC_MAINNET
f56bde9875 * p2p/src/main/resources/DaoStateStore_BTC_MAINNET
ef168a7a11 * p2p/src/main/resources/ProposalStore_BTC_MAINNET
f91435a2a5 * p2p/src/main/resources/SignedWitnessStore_BTC_MAINNET
c6b7362593 * p2p/src/main/resources/TradeStatistics2Store_BTC_MAINNET
```

**Comment by erciccione** [comment]
Apparently we are hitting Github's limits:

```
We wanted to let you know that you’ve used 80% of your data plan for Git LFS on the organization haveno-dex. No immediate action is necessary, but you might want to consider purchasing additional data packs to cover your bandwidth and storage usage:

  https://github.com/organizations/haveno-dex/billing/data/upgrade

Current usage as of 10 Apr 2021:

  Bandwidth: 0.83 GB / 1 GB (83%)
  Storage: 1.42 GB / 1 GB (142%)

```

**Comment by niyid** [comment]
I think these 3 are DAO related...

- 0feba11eb9 * p2p/src/main/resources/BlindVoteStore_BTC_MAINNET
- f56bde9875 * p2p/src/main/resources/DaoStateStore_BTC_MAINNET
- ef168a7a11 * p2p/src/main/resources/ProposalStore_BTC_MAINNET
Getting rid of DaoStateStore will be good based on the size alone and it will go once DAO is removed.

file:///home/odada/Pictures/Screenshot%20from%202021-04-23%2002-31-49.png

**Comment by erciccione** [comment]
>  Getting rid of DaoStateStore will be good based on the size alone and it will go once DAO is removed.

Yes, i think git lfs is mostly used for that one big file. If it's related to the DAO resolving #13 should also resolve this issue.

**Comment by erciccione** [comment]
Labelling this issue P1 (maximum priority), because we are hitting github's LFS limits (probably because of the buildbots). We need to get rid of git LFS ASAP.

**Comment by premek** [comment]
currently normal `git clone` says:
```
Error downloading object: p2p/src/main/resources/AccountAgeWitnessStore_BTC_MAINNET (f485f1a): Smudge error: Error downloading p2p/src/main/resources/AccountAgeWitnessStore_BTC_MAINNET (f485f1a26f0d272074989b28815ad2e8140e2ddf9f83479849888e28e18749d2): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by premek** [comment]
could be cloned with `GIT_LFS_SKIP_SMUDGE=1 git clone SERVER-REPOSITORY`

**Comment by erciccione** [comment]
@premek Could you check if you are still having ghat problem? Everything seems to be working fine for me.

Note that we still use git lfs, but for the moment is just a placeholder file. Will be populated with our network data in the future.

**Comment by premek** [comment]
Yes `git clone` finishes successfully for me now

**Comment by woodser** [comment]
This issue was resolved in by replacing Bisq's LFS files with a [placeholder file](https://github.com/woodser/haveno/blob/master/p2p/src/main/resources/AccountAgeWitnessStore_XMR_MAINNET_placeholder) for Haveno:

* Updated [.gittributes](https://github.com/woodser/haveno/blob/6e4f5174eb9c2de2b96682b1136442f855b26130/.gitattributes#L15) to track the new placeholder
* [BFG tool](https://rtyley.github.io/bfg-repo-cleaner/) was used to remove the old LFS files from the repo
* Contacted GitHub support to completely disassociate the old LFS files from the repo
