### ISSUE TITLE
haveno issue artifact 

### ISSUE THREAD

**Issue by xOnePumpx** [haveno-dex/haveno#1200]
in the middle of dfoing my first payby mail and i cant clicik i sent the funds this morning because i dont have seed nodes and says i dont have a artifact

**Comment by monerobull** [comment]
Update to 1.0.10 and try again.

**Comment by woodser** [comment]
Closing because seed node availability is dependent on the third party network you're using.

**Comment by xOnePumpx** [comment]
okay and not to sound stupid but how do you update

**Comment by monerobull** [comment]
back up your haveno-reto folder just to be save and then just run the newest installer from https://haveno-reto.com and it should update it.
