### ISSUE TITLE
Build fails because Unauthorized dependency

### ISSUE THREAD

**Issue by bvcxza** [haveno-dex/haveno#1206]
```
$ make skip-tests
mkdir -p .localnet
./gradlew build -x test -x checkstyleMain -x checkstyleTest

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':desktop:shadowJar'.
> Could not resolve all dependencies for configuration ':desktop:runtimeClasspath'.
   > Could not resolve com.github.JesusMcCloud:jtorctl:9b5ba2036b.
     Required by:
         project :desktop > project :common
      > Could not resolve com.github.JesusMcCloud:jtorctl:9b5ba2036b.
         > Could not get resource 'https://jitpack.io/com/github/JesusMcCloud/jtorctl/9b5ba2036b/jtorctl-9b5ba2036b.pom'.
            > Could not GET 'https://jitpack.io/com/github/JesusMcCloud/jtorctl/9b5ba2036b/jtorctl-9b5ba2036b.pom'. Received status code 401 from server: Unauthorized


```

It depends on build geo/ip location.
Maybe related #132

**Comment by woodser** [comment]
I'm not seeing this problem, but sometimes build problems can happen due to VPN, and also you could try deleting your  gradle cache, `rm -rf ~/.gradle/caches` and rebuilding with fresh dependencies, `./gradlew build --refresh-keys --refresh-dependencies -x test -x checkstyleMain -x checkstyleTest`.

**Comment by Kreyren** [comment]
I am also running into the issue [while trying to package haveno in nixpkgs](https://github.com/NixOS/nixpkgs/pull/311314)

**Comment by boldsuck** [comment]
Yeah, I saw it by chance when Github workflows CI started after 'Sync Fork' And only in the Win build. Linux and Macos ran through: https://github.com/boldsuck/haveno/actions/runs/10318742896

```
* What went wrong:
Could not determine the dependencies of task ':desktop:shadowJar'.
> Could not resolve all dependencies for configuration ':desktop:runtimeClasspath'.
   > Could not resolve com.github.JesusMcCloud:jtorctl:9b5ba2036b.
     Required by:
         project :desktop > project :common
      > Could not resolve com.github.JesusMcCloud:jtorctl:9b5ba2036b.
         > Could not get resource 'https://jitpack.io/com/github/JesusMcCloud/jtorctl/9b5ba2036b/jtorctl-9b5ba2036b.pom'.
            > Could not GET 'https://jitpack.io/com/github/JesusMcCloud/jtorctl/9b5ba2036b/jtorctl-9b5ba2036b.pom'. Received status code 401 from server: Unauthorized
```

Link of JesusMcCloud wants user and password ;-)

**Comment by JesusMcCloud** [comment]
Sorry, I did nort realize anyon was still using it. I shelved it because AFAIK it was [forked and (contrary to my original repo) maintained by bisq](https://github.com/bisq-network/jtorctl).

**Comment by woodser** [comment]
Thanks for chiming in @JesusMcCloud :)

This issue should be resolved now with this PR from @bvcxza to remove the transitive dependency override: https://github.com/haveno-dex/haveno/pull/1208

Please reopen if there's still any issue.

**Comment by boldsuck** [comment]
Just as a note (in case anyone ever needs it), the origin of the code is here:
https://github.com/guardianproject/jtorctl/tree/master
https://gitlab.torproject.org/legacy/trac/-/issues/32574
https://github.com/torproject/jtorctl/tree/master

Given its age, it's no wonder that ADD_ONION can't do a lot of things.

**Comment by woodser** [comment]
This issue is still appearing when running CI tests for haveno-ts: https://github.com/haveno-dex/haveno-ts/actions/runs/10422781708/job/28869363554?pr=305

```
#22 83.74 FAILURE: Build failed with an exception.
#22 83.74 
#22 83.74 * What went wrong:
#22 83.74 Could not determine the dependencies of task ':bootJar'.
#22 83.74 > Could not resolve all task dependencies for configuration ':runtimeClasspath'.
#22 83.75    > Could not resolve com.github.JesusMcCloud:jtorctl:9b5ba2036b.
#22 83.75      Required by:
#22 83.75          project : > project :haveno:common
#22 83.75       > Could not resolve com.github.JesusMcCloud:jtorctl:9b5ba2036b.
#22 83.75          > Could not get resource 'https://jitpack.io/com/github/JesusMcCloud/jtorctl/9b5ba2036b/jtorctl-9b5ba2036b.pom'.
#22 83.75             > Could not GET 'https://jitpack.io/com/github/JesusMcCloud/jtorctl/9b5ba2036b/jtorctl-9b5ba2036b.pom'. Received status code 401 from server: Unauthorized
```

Wondering what we can do to fix it now?

**Comment by woodser** [comment]
Fixed by updating the haveno submodule within the haveno-pricenode project, which was still using the old dependency.

**Comment by Kreyren** [comment]
haveno-pricenode is 3rd party right?
