### ISSUE TITLE
no offers showing

### ISSUE THREAD

**Issue by richie115** [haveno-dex/haveno#1210]
i finally got haveno to open made the account but no offers are showing wondering if i did something wrong? also tried to run "make deploy" but it wont let me thanks in advance to anyone who can help

**Comment by woodser** [comment]
Sometimes it needs a moment to populate the offers. It still shows no offers?

**Comment by boldsuck** [comment]
> i finally got haveno to open made the account but no offers are showing wondering if i did something wrong?

Are you sure you are on mainnet? Haveno-dex is stage

**Comment by richie115** [comment]
> > i finally got haveno to open made the account but no offers are showing wondering if i did something wrong?
> 
> Are you sure you are on mainnet? Haveno-dex is stage

how would i know if im on the mainnet? i got to the point where it opens i made a trade but once i open the 4 different screens more apps open

**Comment by richie115** [comment]
> Sometimes it needs a moment to populate the offers. It still shows no offers?

yes it still shows no offers i had it open for about an hr and nothing showed up

**Comment by monerobull** [comment]
If you want to use haveno on mainnet you will need to get it from the retoaccess1/haveno-reto repository.

**Comment by woodser** [comment]
> > Sometimes it needs a moment to populate the offers. It still shows no offers?
> 
> yes it still shows no offers i had it open for about an hr and nothing showed up

You should expect these issues if you're building the official haveno-dex repo, which isn't running a mainnet network.

Otherwise please try updating to 1.0.10 and restarting the software, and confirm if you still see the issue.

**Comment by woodser** [comment]
Closing as stale.
