### ISSUE TITLE
Where is debian 1.10 version?

### ISSUE THREAD

**Issue by balz666** [haveno-dex/haveno#1212]
I can't find the debian version to update from 1.0.9 to 1.0.10 and don't know what to do with the bunch of files in the zip files.
I tried 

```
git clone https://github.com/haveno-dex/haveno.git
cd haveno
git checkout master
make
```
but it only messed everything.

Now I can't run Haveno anymore.

Updates shouldn't be mandatory like this. I don't have time for this right now. :/

How can I fix that mess? How can I make a clean install and have some launcher? Is there some .deb file somewhere?

What do I do with all those files and how can I build the software?

![image](https://github.com/user-attachments/assets/79e3b699-d2fd-43ad-95b5-8956e579c285)

With 1.0.9 there was a .deb file and all I had to do was click on it and I was good to do.

Please help.

**Comment by shortwavesurfer2009** [comment]
https://github.com/retoaccess1/haveno-reto/releases

**Comment by woodser** [comment]
May 26 is not the latest release, so it would need to be under the latest release.

**Comment by balz666** [comment]
Yeah, I saw this... But it still the same problem

![image](https://github.com/user-attachments/assets/35ed234c-5c59-4873-9ef8-c3d22747fad4)

No .deb file! And how can I build the software with the zip files?

**Comment by woodser** [comment]
To extract a zip file on Debian systems:

```
sudo apt-get install unzip
unzip file.zip
```

**Comment by balz666** [comment]
OK thanks let me check... I see there is a .deb.zip that was added... It wasn't there yesterday.

**Comment by balz666** [comment]
Is there another way to build the software without a .deb file and would it be possible, in the future, to release a .deb file BEFORE making the update mandatory? I'm really struggling with all this and I remember yesterday there was no .deb files and only two zip files and my old 1.0.9 was not working anymore... so I couldn't use Haveno. Thanks.

**Comment by woodser** [comment]
> Is there another way to build the software without a .deb file

Sure you can build the software yourself by following these instructions in the third party mainnet repository: https://github.com/haveno-dex/haveno/blob/master/docs/installing.md

And then starting with `make haveno-desktop-mainnet`.

> would it be possible, in the future, to release a .deb file BEFORE making the update mandatory?

That'd be up to the network admins of the mainnet instance.

**Comment by balz666** [comment]
I tried to use these instructions but failed. I got error messages.

This is really complicated to me. I'm an old fart and I'm struggling. 

A .deb file is easy and it works. 

I don't know where I could suggest this to the admins, but it would be nice to make the installation as user-friendly as possible, and releasing the .deb before making the update mandatory.

Thanks for your help. I got the .deb file now and am installing it!

Sorry for the "stupid" questions, but I'm not that tech-savvy. I wish privacy was easier.

**Comment by woodser** [comment]
Yeah ideally the installers should be pre-extracted from the zip and ready for installation.

**Comment by balz666** [comment]
I installed, but when trying to launch it I keep getting this message : 

![image](https://github.com/user-attachments/assets/d9af84f5-525b-4710-a113-7620e69b4219)

**Comment by woodser** [comment]
Do you have any processes named "monero-wallet-rpc" running in your task manager? If so, stop Haveno, kill those processes, then restart.

**Comment by balz666** [comment]
It works now, thanks! I quit Monero GUI, killed the monero-wallet-rpc and restarted it and now it works. I think there is something with Monero GUI... Thanks for the help! I hope the next update will be easier.
