### ISSUE TITLE
Support building AppImage installer [2 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1222]
This issue requests building an AppImage installer from the Haveno repo.

The AppImage should be built as part of the existing installer build process with `./gradlew packageInstallers`. See [package.gradle](https://github.com/haveno-dex/haveno/blob/master/desktop/package/package.gradle) within `./desktop` to add support for building AppImage.

This script is invoked as part of [GitHub Actions](https://github.com/haveno-dex/haveno/blob/d3ee7340f0ef284b734acf9ba047f05a488b3113/.github/workflows/build.yml#L53), in order to automatically create the installers, which users can verify against installers posted for download.

Here are related instructions to [manually build the installers](https://github.com/haveno-dex/haveno/blob/master/desktop/package/README.md), if useful.

Related: https://github.com/haveno-dex/haveno/issues/862#issuecomment-2295246898, https://github.com/haveno-dex/haveno/issues/270#issuecomment-2295247375

**Comment by niyid** [comment]
I'm on it...

**Comment by TheTollingBell** [comment]
I deleted the Monero chain off my computer so you might have to wait a day for the sync.

**Comment by TheTollingBell** [comment]
Confirming my matrix as well. Syncing should be done in 6-8 hrs hopefully.

**Comment by TheTollingBell** [comment]
@woodser Ready to recieve at:
```
45ZXas7gQJmUKHqJsxbP2mgupHRGcSRe5Z42QDcAXTFi3meXmGm7AaUSGhid8ZXb1m1Q74EZeHUBqVe4hSFD9vNsEt4fzdz
```

**Comment by woodser** [comment]
Payment sent. Thanks!

**Comment by TheTollingBell** [comment]
Writing here to verify 2 XMR has been recieved. Thanks woodser.
