### ISSUE TITLE
Support building Flatpak installer [1 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1223]
This issue requests building a Flatpak installer from the Haveno repo.

The Flatpak should be built as part of the existing installer build process with `./gradlew packageInstallers`. See [package.gradle](https://github.com/haveno-dex/haveno/blob/master/desktop/package/package.gradle) within `./desktop` to add support for building Flatpak.

This script is invoked as part of [GitHub Actions](https://github.com/haveno-dex/haveno/blob/d3ee7340f0ef284b734acf9ba047f05a488b3113/.github/workflows/build.yml#L53), in order to automatically create the installers, which users can verify against installers posted for download.

Here are related instructions to [manually build the installers](https://github.com/haveno-dex/haveno/blob/master/desktop/package/README.md), if useful.

Related: https://github.com/haveno-dex/haveno/issues/862#issuecomment-2295246898, https://github.com/haveno-dex/haveno/issues/270#issuecomment-2295247375, https://github.com/haveno-dex/haveno/issues/931

**Comment by ZhenyaPav** [comment]
I'm trying to make a flatpak, expect it to take up to a week. If I don't reply until then - feel free to assign it to someone else.

**Comment by woodser** [comment]
Thanks @ZhenyaPav. Please be aware that @Jabster28 has a pull request open to support flatpak, marked as a draft: https://github.com/haveno-dex/haveno/pull/1230

In a worst case we would take the first acceptable solution, but maybe it's best to review their PR and collaborate.

**Comment by niyid** [comment]
I'm on it...

**Comment by obamaruntz** [comment]
Is this still open?

**Comment by woodser** [comment]
We're awaiting @Jabster28 to complete his PR: https://github.com/haveno-dex/haveno/pull/1230

(Hoping soon for the next release :))

**Comment by woodser** [comment]
Resolved with https://github.com/haveno-dex/haveno/pull/1316

@Jabster28 If you can please pass along your payout address, on here or DM :)
