### ISSUE TITLE
UI scaling on high DPI displays

### ISSUE THREAD

**Issue by cryeprecision** [haveno-dex/haveno#1225]
I couldn't find any documentation on the side of haveno for how to change the UI scaling. Maybe I didn't look for it in enough places...
I'm mainly creating this issue so others with the same problem can find this as a bandaid solution if they're looking for one.

I'm using KDE Plasma 6.1.4 with 150% UI scaling and installed haveno from the AUR (1.0.10-1).

The solution for me was to change the haveno shortcut to include `JAVA_TOOL_OPTIONS="-Dglass.gtk.uiScale=2"` as a environment variable or start haveno with `JAVA_TOOL_OPTIONS="-Dglass.gtk.uiScale=2" haveno-desktop`. 
You can replace the '2' with anything you want (1.25, 1.5, etc.)
There are other solutions available if this doesn't work for you, just google for "javafx ui scaling" or something similar.

Also, thanks for this project, your work is much appreciated ❤️

**Comment by woodser** [comment]
Probably best to add a new section to the docs with this info about scaling: https://github.com/haveno-dex/haveno/blob/master/docs/user-guide.md

**Comment by woodser** [comment]
Fixed with #1226. Thanks!
