### ISSUE TITLE
haveno.exchange documentation error.

### ISSUE THREAD

**Issue by zabaniz** [haveno-dex/haveno#1237]
Issue with Documentation Branch Reference

I followed the instructions on the [Haveno documentation](https://docs.haveno.exchange/development/installing/#install-dependencies) to check out version 1.0.10 for building the project. However, the build fails when using this version, likely because 1.0.10 is a detached branch.

Switching to the master branch resolved the issue and allowed the build to complete successfully. It seems the documentation might be pointing to the wrong branch for building.

Screenshots:

+ [Documentation Issue](https://github.com/user-attachments/assets/4328b9e5-9aa7-4a2d-bef3-bec718d52159)
+ [Build Error](https://github.com/user-attachments/assets/f27f8ed6-746a-4a65-b41c-dd79222d4e9b)

 **Could the docs be updated to reference the master branch instead?**

![haveno-docs-issue](https://github.com/user-attachments/assets/4328b9e5-9aa7-4a2d-bef3-bec718d52159)

![haveno-build-error](https://github.com/user-attachments/assets/f27f8ed6-746a-4a65-b41c-dd79222d4e9b)

Might not be a real issue with the app but the [Haveno documentation](https://docs.haveno.exchange/development/installing/#install-dependencies).

+ This fixed the issue on the 1.0.10 branch.
![gitdiff-haveno 1 0 10](https://github.com/user-attachments/assets/beaecbcd-7c75-4515-8fb2-1f4f37a5c32c)

**Comment by woodser** [comment]
Yeah this issue appeared due to an external dependency and is fixed on master. The docs can be updated to master for now, then changed to 1.0.11 on the next release

**Comment by woodser** [comment]
I've updated the instructions to build master: https://github.com/haveno-dex/haveno-docs/pull/14

Thanks!
