### ISSUE TITLE
Can’t login

### ISSUE THREAD

**Issue by Githuber1-ai** [haveno-dex/haveno#1242]
Hello,

yesterday I tried logging in as I usually do. For some reason I get this message:

![EFC98C19-D0AB-44C0-8704-2EEB51E9358C](https://github.com/user-attachments/assets/d2c83949-a572-4741-a487-f5f6a184773a)

Why? What’s going on and how do I fix it? 
please please help me, I already deposited Monero in the security deposit section and I can’t get it back unless I sign in.

PLEASE PLEASE PLEASE SOMEONE HELP!!!

**Comment by woodser** [comment]
Please first ensure that no instances of monero-wallet-rpc are running in your task managers, then try again.

If that doesn't work, you can delete your wallet's cache file, located at your_app_folder/xmr_mainnet/wallet/haveno_XMR

Linux: ~/.local/share/Haveno/
macOS: ~/Library/Application Support/Haveno/
Windows: ~\AppData\Roaming\Haveno\

Be sure to back up any files before deleting them.

**Comment by Githuber1-ai** [comment]
> Please first ensure that no instances of monero-wallet-rpc are running in your task manager, then try again.
> 
> If that doesn't work, you can delete your wallet's cache file, located at your_app_folder/xmr_mainnet/wallet/haveno_XMR
> 
> * Linux: ~/.local/share/Haveno/
> * macOS: ~/Library/Application Support/Haveno/
> * Windows: ~\AppData\Roaming\Haveno\
> 
> Be sure to back up any files before deleting them.

Thank you for the quick reply. I tried many things including deleting and uninstalling my entire gui wallet as well as uninstalling other apps that took space but to not avail. I have not tried the next method but how do i back up my data before deleting it? I want it so that when I install it again I can just put in my password as normal.

thanks

**Comment by woodser** [comment]
> how do i back up my data before deleting it?

You can copy and paste your application folder to a backup location of your choice, located at:

Linux: ~/.local/share/Haveno
macOS: ~/Library/Application Support/Haveno
Windows: ~\AppData\Roaming\Haveno

Or use the backup function within the app which does the same thing.

**Comment by Githuber1-ai** [comment]
> > how do i back up my data before deleting it?
> 
> You can copy and paste your application folder to a backup location of your choice, located at:
> 
> Linux: ~/.local/share/Haveno macOS: ~/Library/Application Support/Haveno Windows: ~\AppData\Roaming\Haveno
> 
> Or use the backup function within the app which does the same thing.

I use a windows. How exactly does that work? Do I just find the file name and back it up? Also, are you a million percent sure that if I back it up delete it and reopen it will in fact ask for my password and not look like it’s a new account?

I’m desperate to get back to it. I hope the developers are fixing this issue because my Monero is with them. May I talk to the owners/developers of this?

**Comment by Githuber1-ai** [comment]
> > how do i back up my data before deleting it?
> 
> You can copy and paste your application folder to a backup location of your choice, located at:
> 
> Linux: ~/.local/share/Haveno macOS: ~/Library/Application Support/Haveno Windows: ~\AppData\Roaming\Haveno
> 
> Or use the backup function within the app which does the same thing.



Hello? Are you still there? This doesn’t make any sense and this app is so stupid. I played no role in this. I’m not seeing the roaming thing or whatever the folder name is. I can’t back it up and I’m still having a problem.


I should NEVER HAVE TO DEAL WITH THIS. please put me in contact with the owners and/or developers because I demand a refund for the funds lost.

this is my Monero address:

42Nk5dKHr84KyEBxNojeRwNVsthhB56vPFvQYvyqEmbkJjQcZGTniHA92gDBoecyNBQ8JC5UCT7mq9EtKrCS6noRCWLhsZg

the total funds lost were around 0.52817236 xmr

since I did not play any role in losing my funds and due to the incompetence of the developers and a terrible app which I will NEVER use until I can trust it. I either demand that the developers fix this immediately, or that I recieve a refund for the xmr that I lost due to their incompetence.

**Comment by charcharchar** [comment]
if you backed up the seed words you can restore your funds by entering them in a mobile wallet.

**Comment by woodser** [comment]
Go to your home directory in a windows explorer folder (C:\Users\<yourname>).

Show hidden items by going to the View menu > Show > Hidden items.

Now go into AppData > Roaming.

You'll see your Haveno folder there. Copy and paste it to safe backup location. This will let you restore everything in case something goes wrong.

Now go into your Haveno folder > xmr_mainnet > wallet > delete the file named "haveno_XMR".

Now try to launch the application. It should work.

**Comment by woodser** [comment]
This PR automatically reverts to the backup cache in case it's corrupt: https://github.com/haveno-dex/haveno/pull/1244

**Comment by woodser** [comment]
This issue should be fixed automatically by upgrading to v1.0.11 which is now released. Please let us know if you continue to have a problem after updating.

**Comment by Githuber1-ai** [comment]
> This issue should be fixed automatically by upgrading to v1.0.11 which is now released. Please let us know if you continue to have a problem after updating.

Yes I download it and I got it all back. I’m so sorry for how angry and panicked I seem. I just get really scared of these sort of things. Can I reward you? Paste your Monero address so I can give you a small reward.

**Comment by woodser** [comment]
Donations are always welcome and help fund development: `42sjokkT9FmiWPqVzrWPFE5NCJXwt96bkBozHf4vgLR9hXyJDqKHEHKVscAARuD7in5wV1meEcSTJTanCTDzidTe2cFXS1F`

Thanks :)
