### ISSUE TITLE
Add a notification sound on a trade open

### ISSUE THREAD

**Issue by shortwavesurfer2009** [haveno-dex/haveno#1246]
It would be good to have a notification tone that would play if an offer is accepted. That way you could respond faster if you have your laptop lid closed or monitor turned off

**Comment by KewbitXMR** [comment]
This has been implemented into mobile

**Comment by shortwavesurfer2009** [comment]
It should still be on desktop so that people who are nearby their machines but not looking at them can know if a trade comes in.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by woodser** [comment]
Subset of https://github.com/haveno-dex/haveno/issues/1284
