### ISSUE TITLE
Inconsistent Wallet Transactions History Amounts

### ISSUE THREAD

**Issue by dkaparis** [haveno-dex/haveno#1247]
After some trades, the sum of transaction amounts in Funds->Transactions does not equal the current reported available balance.

A trade generates two transactions `Multisig payout` and `Multisig deposit`. The sum of these is not equal to the trade sum, nor the trade sum adjusted with the corresponding trade and transaction fees as reported in trade history.

In Bisq, a third transaction, `Maker/Taker and tx fee` is generated for a trade and there the sum of the three transactions is equal to the trade amount with trade and transaction fees added.

**Comment by woodser** [comment]
Opened an issue to add a column for the transaction fees: https://github.com/haveno-dex/haveno/issues/1254

**Comment by woodser** [comment]
Resolved by https://github.com/haveno-dex/haveno/pull/1288
