### ISSUE TITLE
Separate build artifacts for Linux [0.5 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1250]
Currently there's a GitHub Action which creates installers for mac, linux, and windows:

<img width="509" alt="image" src="https://github.com/user-attachments/assets/0cdb0829-41e3-49f3-b383-c979122fc133">

This issue requests splitting the linux artifact into two artifacts, deb and rpm.

**Comment by woodser** [comment]
@Jabster28 You were interested in splitting these assets as well.

This will be even more useful when there's AppImage and flatpak, so it's actually a good idea.

**Comment by Jabster28** [comment]
> @Jabster28 You were interested in splitting these assets as well.
Yes that's fine, I'll cherry pick those commits and make a new PR for them. I read somewhere in the matrix that they shouldnot contain versions? Should that be trusted?

**Comment by boldsuck** [comment]
Independent question:
`./gradle build` creates `/haveno/seednode/build/distributions/seednode.tar`
Is it possible to store seednode.tar in Github Actions like 'cached-localnet'?

**Comment by Jabster28** [comment]
Yeah, that should be possible. If woodser green lights it, it can probably be done for the next release.

**Comment by woodser** [comment]
Sure I don't see why not.

**Comment by woodser** [comment]
Completed with https://github.com/haveno-dex/haveno/pull/1264
