### ISSUE TITLE
Capture errors and warnings to dedicated log file [0.5 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1252]
This issue requests creating a log file specifically for errors and warnings with Haveno.

The log file should collect any logs which are logged at the `ERROR` or `WARN` level.

In addition, it should record error stack traces.

In addition, it should be guarded against growing to unlimited size. Currently the log files are split to new files when they become too large (e.g. haveno_log1.log), and eventually the log files are recycled.

**Comment by preland** [comment]
I can do this one

**Comment by woodser** [comment]
Great, we'll leave it open to first accepted solution.

**Comment by preland** [comment]
PR #1256 should solve this

**Comment by woodser** [comment]
Resolved with https://github.com/haveno-dex/haveno/pull/1256
