### ISSUE TITLE
Add column with transaction fees (Funding > Transactions > Export CSV) [0.5 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1254]
This issue requests adding a column for transaction fees in the generated transaction report CSV.

To generate the transaction report, go to Funding > Transactions > Export CSV.

The report only has a column for the amount of XMR transacted.

The tx fee should also appear as a column in the Funds > Transactions tab.

**Comment by preland** [comment]
I'll start looking into this one

**Comment by niyid** [comment]
Is it OK to assume transaction fee = tx.getFee() in TransactionsListItem?

**Comment by niyid** [comment]
> I'll start looking into this one

Oops, sorry. I put in a PR.

**Comment by woodser** [comment]
This issue is resolved with https://github.com/haveno-dex/haveno/pull/1288

With this change, the total amounts in Funds > Transactions adds up to the total balance correctly.

I'll be awarding the bounty to @niyid because his submission was first and functional, while preland's submission has an error when run (and some unnecessary formatting changes :P). While neither submission was fully correct, niyid's submission was easily adapted to display the fee for outgoing transactions.

Thanks very much for your help. @niyid please message me an address for payment. Thanks!
