### ISSUE TITLE
Importing backed up data

### ISSUE THREAD

**Issue by Newaccount-github** [haveno-dex/haveno#1278]
Hello,

I know how to back up my haveno data but how exactly do you import it to another device? Every time I try downloading the haveno app it starts as a new account. There should be a button/feature that says “import account” or something like that. 

I want to do this so that if my laptop breaks, I have not lost the data.

Please help me thanks.

**Comment by woodser** [comment]
Opened an issue to document this in FAQ: https://github.com/haveno-dex/haveno-docs/issues/16

**Comment by woodser** [comment]
Closing this issue, please let us know if you have trouble.
