### ISSUE TITLE
Build app as a JPackage app-image before making other installers [1 XMR]

### ISSUE THREAD

**Issue by Jabster28** [haveno-dex/haveno#1280]
Right now, the Linux CI builder uses JPackage to build for each platform, but the package is reset every time. JPackage supports building into an intermediary app-image (not an [AppImage](https://appimage.org/)) and building the individual installers on top of that. Using this instead of rebuilding that will save a lot of CI minutes, and may be necessary once we also have Flatpaks and AppImages.

I've been thinking of doing this for a bit, and @\TheTollingBell raised the idea of putting it in an issue. I'll try and get this done after we merge these two PRs, as that'll be less likely to break anything.

**Comment by Jabster28** [comment]
Should've mentioned: blocked by #1222, #1223, and #1250

**Comment by woodser** [comment]
I've added a bounty of 0.5 XMR to this issue.

@TheTollingBell (from your [comment](https://github.com/haveno-dex/haveno/pull/1270#issuecomment-2343947331)).

**Comment by TheTollingBell** [comment]
I'm on it. Should be done by end of tomorrow EST time.

**Comment by TheTollingBell** [comment]
Sorry, forgot that #1230 was blocking. I'll wait till all blocking PRs are merged before starting.

**Comment by woodser** [comment]
@TheTollingBell the changes from #1230 have been merged to master, so we're ready to build to the intermediary JPackage app image.

**Comment by woodser** [comment]
@Jabster28 has expressed interest in working on this too, in which case we're happy to take the first acceptable solution, in the interest of time for the next release.

**Comment by TheTollingBell** [comment]
Almost done with my changes. I forgot to check on this issue lol.
