### ISSUE TITLE
Build fails because checksum for jtorctl fails

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#132]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':desktop'.
> Checksum failed for com.github.JesusMcCloud:jtorctl:389d61b1b5a85eb2f23c582c3913ede49f80c9f2b553e4762382c836270e57e5
```
Bisq seems to be having the same issue.

**Comment by erciccione** [comment]
#128 is merged but the buildbot still fails from time to time. I cannot see an obvious reason for these random failures. Note that Haveno seems to be building fine on Mac and Linux. Not sure about Windows.

**Comment by premek** [comment]
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#caching-dependencies

**Comment by erciccione** [comment]
I didn't know `setup-java` had a caching mechanism built in. Nice catch!

**Comment by erciccione** [comment]
The new checksum hash should work. If it doesn't, please try deleting the `~/.gradle` folder and try again.

**Comment by premek** [comment]
> please try deleting the `~/.gradle` folder and try again.

Maybe just `~/.gradle/caches`

**Comment by erciccione** [comment]
Bisq's considerations: https://github.com/bisq-network/bisq/issues/5807#issuecomment-963641322
