### ISSUE TITLE
"Force restart" Loop During Wallet Sync on Startup

### ISSUE THREAD

**Issue by ChanoSan** [haveno-dex/haveno#1335]
(Reposting here from Haveno-Reto after they told me to report upstream. Original issue is here: https://github.com/retoaccess1/haveno-reto/issues/23 )

**Haveno-Reto Version:** _1.0.11_
**OS:** _Ubuntu 20.04.6 LTS_

On startup, Haveno makes a connection to the Tor network successfully and progresses to "Synchronizing wallet with Monero Mainnet (via clearnet) at block...". From here, the synchronization progress makes it to 1 or 2% (sometimes higher, but always a single digit percentage) before going back down to 0%. It remains in this state for hours with no visible progress.

Looking at the process logs, I see the following errors:

```
Oct-12 12:46:57.203 [XmrWalletService] WARN  haveno.core.xmr.wallet.XmrWalletService: Error syncing wallet with progress on startup: java.lang.RuntimeException: Sync progress timeout called 
Oct-12 12:46:57.204 [XmrWalletService] INFO  h.core.xmr.setup.MoneroWalletRpcManager: Stopping MoneroWalletRpc path=haveno_XMR, port=46567, pid=128399 
Oct-12 12:46:57.218 [XmrWalletService] WARN  haveno.core.api.XmrConnectionService: Requesting switch to next best monerod, source monerod=http://xmr-node.cakewallet.com:18081 
Oct-12 12:46:59.080 [JavaFX Application Thread] INFO  haveno.network.p2p.peers.PeerManager: We have 8 connections open. Our limit is 12 
Oct-12 12:46:59.434 [XmrWalletService] INFO  haveno.core.api.XmrConnectionService: XmrConnectionService.onConnectionChanged() uri=http://node.community.rino.io:18081, connected=true 
Oct-12 12:46:59.436 [XmrWalletService] INFO  haveno.core.xmr.wallet.XmrWalletService: Initializing main wallet with monerod=http://node.community.rino.io:18081 
Oct-12 12:46:59.436 [pool-32-thread-7] WARN  haveno.core.xmr.wallet.XmrWalletService: Force restarting main wallet because connection changed while syncing 
Oct-12 12:46:59.436 [XmrWalletService] INFO  haveno.core.xmr.wallet.XmrWalletService: XmrWalletService.openWallet(haveno_XMR) 
Oct-12 12:46:59.437 [pool-32-thread-7] WARN  haveno.core.xmr.wallet.XmrWalletService: Force restarting main wallet
```
also...
```
Oct-12 12:50:08.005 [InputHandler-k6wctqd5l2nh...] WARN  haveno.network.p2p.network.Connection: Shut down caused by exception Read timed out on connection=Connection{peerAddress=Optional[k6wctqd5l2nhmietzs6zg4pric3ukeg7lazzz67ttbl75qwfr2q4yvqd.onion:2002], connectionState=ConnectionState{,
     peerType=PEER,
     numInitialDataRequests=1,
     numInitialDataResponses=1,
     lastInitialDataMsgTimeStamp=1728704767966,
     isSeedNode=true,
     expectedInitialDataResponses=5
}, connectionType=OutboundConnection, uid='94d3838e-62fe-4644-a772-bbc1d85b8fff'} 
```

The above WARN errors repeat multiple times throughout the logs.

I understand the need for patience while starting up Haveno, but I tried leaving it in this state for upwards of 6 hours and it still made no progress.

I tested this on another machine running Ubuntu 22.04.5 LTS with the same results, including the same error logs.

As a result of this, Haveno can never complete startup, and thus cannot be run or used. While startup slowness existed before (due to the attacks on the seed nodes, I imagine) this is my first experience of this particular startup problem.

**Comment by woodser** [comment]
Are you still encountering problems after restarting the application? It sounds like some issue with network conditions or the Monero nodes, but I haven't heard other reports of startup problems recently. My own client is starting without any problems.

You're still on v1.0.11 which has been stable, so at least we know it's not something newly broken in the v1.0.12 release, and v1.0.12 is unlikely to change anything related to this.

The connection shut down warning is common and can be ignored in most cases.

Can you share your startup logs so I could look through what it's doing in more detail? It ought to be able to switch successfully to a working node.

In the meantime, the app should start successfully by running your own local Monero node.

**Comment by ChanoSan** [comment]
This is the part where I sheepishly close the issue with a successful launch of Haveno. But let me answer a question or two first.

> Are you still encountering problems after restarting the application?
The issue I described persisted after multiple restarts of the application, and even multiple reboots of the PC.
At one point I left it sitting in the problem state overnight for 10+ hours with no visible change.

In order to give you a suitably long period of logs to work with, I tried it one more time... rebooting, restarting, and writing stdout to a log file overnight and throughout the next day, for a period of roughly 24 hours. I returned to check on it, only to find it had finally successfully competed loading and Haveno worked as expected.

I guess my sin was not being patient enough. But I'll append my log to this post just to be thorough, in case it's of use to anyone else. I guess my only advice to other users encountering this issue is to be persistent and patient.

Thank you for your time.

[haveno_startup.txt](https://github.com/user-attachments/files/17435450/haveno_startup.txt)

**Comment by woodser** [comment]
Actually there is an update in v1.0.12 which could help with your startup problem.

The timeout to sync the wallet was increased from 60s to 120s, giving your wallet more time to make progress with the node it's connected to before switching to an alternative.

For some reason it is taking significant time to sync your wallet with public nodes (maybe slow connection?).
