### ISSUE TITLE
Describe how payment account details are used when creating account [0.2 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1359]
This issue requests adding a description of how payment account details are used when adding a new payment account.

The description should be added as a line of text after "Create new account" in the following screenshot:

<img width="1197" alt="image" src="https://github.com/user-attachments/assets/792a2d6f-84c7-42e7-ada1-ddf63d312baf">

An appropriate description is: "Your payment account details are stored locally on your device and shared only with your trading peer and the arbitrator if a dispute is opened."

**Comment by XMRZombie** [comment]
Something [like this](https://github.com/XMRZombie/haveno/compare/c8ac07d70b9a750cdf0942af9946102498713ea3...78921559e18e20e81caab88c6ad3c57ca1fea646) is good ?

**Comment by woodser** [comment]
I was thinking as normal text on the next line.

**Comment by XMRZombie** [comment]
I didnt found how to change highlighting but I put the description on a new line. [PR](https://github.com/XMRZombie/haveno/commit/b1bf42a2f00c0aa047256527631faf0ef6087224)
![accountsetup](https://github.com/user-attachments/assets/8ce7a1c6-bb4b-4a4c-a50a-3cf773cbd27f)

**Comment by woodser** [comment]
It needs to be formatted normally without the bold highlighting.

**Comment by RealFFF000** [comment]
Is this correct?
https://github.com/haveno-dex/haveno/pull/1380

**Comment by woodser** [comment]
Yes this issue is fixed with https://github.com/haveno-dex/haveno/pull/1387.

@RealFFF000 Please share or DM an address for payment. Thanks!

**Comment by RealFFF000** [comment]
How can I DM?

**Comment by woodser** [comment]
You can find me on Matrix. If you join our channel, #haveno:monero.social, you'll find me in there.

**Comment by RealFFF000** [comment]
ok - I just sent you a message on matrix
