### ISSUE TITLE
Can't Raise Dispute or Create Support Ticket

### ISSUE THREAD

**Issue by SirCreatus** [haveno-dex/haveno#1393]
I completed a zelle trade. Then all bugged. It stopped allowing me to communicate to the seller and by the time the transaction time ran out I could not raise a dispute or create a support ticket. Haveno would start with errors like:

```
Error initializing trade 24290

Could not open wallet 'xmr_trade_24290_cb3faee5'. Please close Haveno, stop all monero-wallet-rpc processes in your task manager, and restart Haveno.

Error message: Failed to open wallet****
```
[logfilenodispute.txt](https://github.com/user-attachments/files/17637052/logfilenodispute.txt)
^ here is the log file^
![chat](https://github.com/user-attachments/assets/9147b53b-5a01-47bc-aacc-ee4db394f2e3)

If there were some manual way to raise a dispute or chime in an arbitrator this issue could be resolved. 

Thanks for your help!

**Comment by woodser** [comment]
Do you have any instances of monero-wallet-rpc running in your task manager when the application is closed? Please terminate them if so.

**Comment by SirCreatus** [comment]
I don 't think so? What they night be titled as

**Comment by woodser** [comment]
They'd be named monero-wallet-rpc in your task manager.

**Comment by SirCreatus** [comment]
when I click to open a support ticket the error says `Cannot invoke "monero.wallet.MoneroWallet.exportMultisigHex()" because "this.wallet" is null`

If there were any way to manually open a support ticket that would be awesome. I have all the proof that I made my side of the trade.

**Comment by woodser** [comment]
You can try closing Haveno and replacing that wallet's cache file (the wallet file with no extension) with its backup version within your application directory, then starting Haveno.

Make sure to create a safe backup first before replacing the file.

**Comment by woodser** [comment]
> You can try closing Haveno and replacing that wallet's cache file (the wallet file with no extension) with its backup version within your application directory, then starting Haveno.
> 
> Make sure to create a safe backup first before replacing the file.

Nevermind, the application already tries this automatically.

For some reason your trade wallet isn't able to be opened. Maybe it's corrupted somehow? Not sure, but this is the first instance I've seen of this happening with a trade wallet.

I think next best thing is to fix the application to allow you to open a dispute without the wallet being opened, and then the arbitrator can manually resolve the trade.

**Comment by woodser** [comment]
Actually I noticed a bug automatically restoring the wallet cache file, which explains the error in your case. Fixed in https://github.com/haveno-dex/haveno/pull/1398

**Comment by SirCreatus** [comment]
> Actually I noticed a bug automatically restoring the wallet cache file, which explains the error in your case. Fixed in #1398

I don't follow. Can you explain a bit? How do I restore the corrupted wallet?

**Comment by woodser** [comment]
This issue should be fixed automatically in the next update, when the changes are incorporated.

**Comment by SirCreatus** [comment]
> This issue should be fixed automatically in the next update, when the changes are incorporated.

thank you!
