### ISSUE TITLE
keyserver.ubuntu.com does not have advertised Haveno GPG keys

### ISSUE THREAD

**Issue by kavfixnel** [haveno-dex/haveno#1395]
The GPG key with the fingerprint for `0xFAA24D878B8D36C90120A897CA02DAC12DAE2D0F` does not exist in Ubuntu's key server:

```bash
~ ❯ curl https://keyserver.ubuntu.com/pks/lookup\?op\=get\&search\=0xFAA24D878B8D36C90120A897CA02DAC12DAE2D0F -L
Not Found
```

This makes some installs fail on verification

**Comment by woodser** [comment]
`FAA24D878B8D36C90120A897CA02DAC12DAE2D0F` is for an example only. It needs to be replaced with the value from the network you're using.
