### ISSUE TITLE
We did not receive a filter object from the seed nodes. Please inform the network administrators to register a filter object.

### ISSUE THREAD

**Issue by Chibraax** [haveno-dex/haveno#1406]
After the GUI open I have this error message 
![Screenshot_20241111_212833](https://github.com/user-attachments/assets/b5e06635-d4ae-4976-a907-9cb2a5677798)

Then I see NO offers available for everything. 

Is there a DDOS attack ?

**Comment by boldsuck** [comment]
> Then I see NO offers available for everything.

That's normal, there are rarely offers on Stagenet. Actually only when a developer is testing something.

**Comment by woodser** [comment]
Either you're trying to run the app on mainnet from the official repo, or it's an issue with third party network.
