### ISSUE TITLE
Mining-Fee: (4) instead of fee

### ISSUE THREAD

**Issue by Ben-Held** [haveno-dex/haveno#1408]
<img width="588" alt="Bildschirmfoto 2024-11-12 um 21 21 08" src="https://github.com/user-attachments/assets/757706b1-54df-43c9-b9b3-33aaa50768ab">

I dunno, if its a translation-error in the german language or if you all also see like in the screenshot only a (4) at Mining-Fee in 1.0.12 AND 1.0.13 ?

**Comment by woodser** [comment]
Thanks. The translations need to be updated from the latest English version, specifically:

- `createOffer.createOfferFundWalletInfo.msg`
- `takeOffer.takeOfferFundWalletInfo.msg`
