### ISSUE TITLE
Support remote Bitcoin node in place of local node

### ISSUE THREAD

**Issue by wallart1** [haveno-dex/haveno#1410]
I have a pre-existing Bitcoin full node in a different virtual machine. I would like to connect to it rather than making another copy of the blockchain.

**Comment by woodser** [comment]
Do you mean remote Monero node? It doesn't use a Bitcoin node at all.

**Comment by wallart1** [comment]
Maybe I'm thinking of something else. Perhaps Basicswap. Sorry.
