### ISSUE TITLE
Price percentage for buying XMR off between fixed and dynamic

### ISSUE THREAD

**Issue by h3mhFs7bjD** [haveno-dex/haveno#1418]
Using haveno-reto 1.0.13

Everything converted to mBTC per 1 XMR:

1. 2 mBTC/XMR                       -18.03%
2. 2 mBTC/XMR                       -18.03%
3. 1.85185 mBTC/XMR            -11.46%
4. 1.681486 mBTC/XMR             2.50%
5. 1.74409 mBTC/XMR               6.00%
6. 1.76284 mBTC/XMR               7.00%
7. 1.76283 mBTC/XMR               7.00%
8. 1.82161 mBTC/XMR              10.00%

The best offer is 4 and it says you pay 2.5% more than market. Offers 1-3 are the worst together with 8. 1-3 say you pay far under the market rate but 8 says you pay 10% over the rate. It looks like fixed offer percentage are calculated differently from dynamic ones, which can mislead unattended traders.

![Screenshot_2024-11-15_16-56-14](https://github.com/user-attachments/assets/5d40ce75-84c1-4bcb-8bf6-8ceac7fc47d0)

**Comment by woodser** [comment]
Already fixed with https://github.com/haveno-dex/haveno/pull/1411 and included in the 1.0.14 tag.
