### ISSUE TITLE
Improve docs/installing wording so layman knows that Haveno-dex is not usable software

### ISSUE THREAD

**Issue by slrslr** [haveno-dex/haveno#1430]
I have spend more than 30 minutes of my time and time of others because you have not explained at https://github.com/haveno-dex/haveno/blob/master/docs/installing.md in enough newbie user friendly way that this software is not usable for real trading.

Details: https://github.com/haveno-dex/haveno/issues/966#issuecomment-2493226900

Idea for fix/improvement:
1) At https://github.com/haveno-dex/haveno/blob/master/docs/installing.md switch NOTE to WARNING or other way better highlight it and then rewrite the content to say something like: Tutorial on this page installs only testing network (testnet), you can not use it for real trading. For real trading use https://haveno-reto.com ...
IMO this description should be major eye-catching element of the page/title of the page mentioning "testing", "testnet".
2) do the similar for main README https://github.com/haveno-dex/haveno

basic GUI user expects the software linked from main webpage of the project to work for real world trades, but it does not seem to be the case and there is no GUI indication user can select other real trading network.

**Comment by woodser** [comment]
How about this?

<img width="950" alt="image" src="https://github.com/user-attachments/assets/6ae6532b-63b6-48c7-ac99-2e81b18443e0">

From https://github.com/haveno-dex/haveno/pull/1434

**Comment by slrslr** [comment]
No, I do not think that layman users (which is the most of users) know what is "mainnet" string. They just trying to use Haveno to do the trade.
Maybe removing first sentence and in second one replacing "The" by "This" and "mainnet to make" by nothing "".
In the third sentence users does not know which network and you should link to known networks even if you have to place a disclaimer (that it is not endorsed). I have noticed that the -reto official page also mentions it "Haveno-reto is not ... Officially endorsed by the Haveno developers - no instance is endorsed"

**Comment by woodser** [comment]
We won't name any third parties, so we'll need to find the language without that.

**Comment by woodser** [comment]
<img width="1019" alt="image" src="https://github.com/user-attachments/assets/b40de835-8a90-428a-ab6a-112346759b75">

**Comment by slrslr** [comment]
Pretty good. Thanks. Unfortunately it is a dead end without providing a link to a third party network list or such.

please

> do the similar for main README https://github.com/haveno-dex/haveno if possible so people do not spend time installing non working software.

**Comment by woodser** [comment]
> do the similar for main README https://github.com/haveno-dex/haveno

How's this modification of the readme?

<img width="1030" alt="image" src="https://github.com/user-attachments/assets/f7ef27c2-e97a-46d0-b2e5-a020e66568d8">

**Comment by slrslr** [comment]
It is not bad, is a Note not Warning, it says " The official Haveno repository" not "This official ....".
Otherwise looks good. Thanks.
