### ISSUE TITLE
Require user to select payment account type (account for sending/receiving or both)

### ISSUE THREAD

**Issue by slrslr** [haveno-dex/haveno#1444]
[There](https://lemmings.world/post/17167059) is mentioned that sending money from an account different from one that is saved in Haveno (Haveno>Accounts>Manage accounts) can cause issues in arbitration and possibly losing the arbitration case.

Despite this, Haveno does not ask user about the type of the newly created account (receiving, sending, both).

This can cause issues (at least to a new user), because user can create BTC account in Haveno using new BTC address their wallet provided them. After some days, user wants to sell some BTC and picks an offer. Then he selects his generally-named BTC account in a drop-down menu and proceeds, which ends up in the need to send from a different BTC wallet than one set in Haveno (as mentioned, I have set random receiving address since I have not expected to sell BTC, but rather BUY), causing described issue during possible arbitration.

Proposal:

- During account creation, user has to select account type by clicking the three-option switch. Used for: sending, receiving, both
Upon selecting, the proposed account name is automatically updated to reflect this: BTC: abcd... [my BTC receiving account]
- If adding the name like that is not good/too difficult, maybe the account type ([my BTC receiving/sending account]) may be also shown only on a page where user picks an account to be used in the offer.

Sorry if this is bad idea, wrong understanding.

**Comment by boldsuck** [comment]
Cryptocurrency addresses in Haveno are for receiving.
When sending, every usable (XMR, BTC¹, LTC) wallet creates a new address. If needed you have TX-ID as proof for arbs.
¹even bisq integrated bitcoinj

**Comment by woodser** [comment]
Yeah the crypto accounts are always for receiving funds. Funds can be sent from a different address. Closing as invalid.

**Comment by slrslr** [comment]
So the person in the linked post is wrong, and i can send from any wallet? I thought that Haveno asks to send from certain wallet.

So either Haveno should not mention from which account I should send / on a page where new account is created/added, it should mention for which purpose it is receiving/sending/both.

**Comment by boldsuck** [comment]
> So the person in the linked post is wrong, and i can send from any wallet? I thought that Haveno asks to send from certain wallet.

Yes, sending BTC, BCH, ETH, LTC, USDT, USDC, etc. is done via external wallets and you can use whatever you want.
And of course you can always send from a different address or wallet.

Cryptocurrencies cannot be charged back. The risk of chargebacks (stolen accounts) only exists with fiat payments. That is why Traditional Account data¹ is created in Haveno and transmitted to the peer.
¹(e.g: Username, Account-Age, eMail)

HINT:
For privacy reasons, some users also create 2 or more accounts for one fiat payment type. e.g: `Pay By Mail` with data for receiving and other data for sending. You can select the option: `Use custom account name` and name accounts accordingly.
