### ISSUE TITLE
"You can only create one offer at a time" but why, I can not see any open offer of mine.

### ISSUE THREAD

**Issue by slrslr** [haveno-dex/haveno#1448]
System info: os.name=Linux; os.version=6.1.0-27-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=21.0.2+14-LTS (BellSoft); JVM=21.0.2+14-LTS (OpenJDK 64-Bit Server VM)

{VERSION=1.0.14, P2P_NETWORK_VERSION=A, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=0A}

Sell XMR for fiat direction does not allow me to create new offer. The button has a tooltip: "[You can only create one offer at a time](https://github.com/search?q=repo%3Ahaveno-dex%2Fhaveno+%22You+can+only+create+one+offer+at+a+time%22&type=code)" but even when i select to view all currencies, all payment methods, there is no offer of mine and also on the Portfolio / My open offers, is no offer. Other tab (Sell XMR for CRYPTO) and others allows creating offer.

I suspect that i have started making offer and then redirected to other page/tab and it is left "at background" being inaccessible?
It looks like that mentioned message makes no sense or there is some glitch.

After restarting, i can make an offer. I am unsure how to reproduce this. Clicking to create offer and going to other Haveno section and back, returns properly to the offer form.

**Comment by woodser** [comment]
So it fixed itself after restarting and you're unable to recreate the issue?

We can probably consider this a fluke and not worry about it if so, given this is the first report I've seen of such a problem, and it fixes itself on restart.

**Comment by woodser** [comment]
Please re-open if you see it again.
