### ISSUE TITLE
RetoSwap is missing at haveno.com/networks/

### ISSUE THREAD

**Issue by slrslr** [haveno-dex/haveno#1458]
[RetoSwap](https://github.com/retoaccess1/haveno-reto) is missing at https://haveno.com/networks/ where I can only see [controversial](https://www.reddit.com/r/Monero/comments/1gln8b9/warning_aioha_haveno_network_shady_hotheads/?share_id=_OlZOL121e_l76ME-_OGt) Aloha.
I am writing here, because that haveno.com page lacks a contact email.

**Comment by woodser** [comment]
haveno.com is run by @KewbitXMR and is independent from this project.
