### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by stdec00** [haveno-dex/haveno#1479]
**System: Artix Linux
Steps: Aur install**

`yay -S haveno`

==> Starting build()...

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/home/dec/.cache/yay/haveno/src/haveno-1.0.14/settings.gradle' (/home/dec/.gradle/caches/8.6/scripts/2ii5klxjjq1d8e574diplcyy2).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 67

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: haveno-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
haveno - exit status 4

Does the same when trying git clone, make method. Thanks!

**Comment by woodser** [comment]
Have you installed JDK 21 from the [instructions](https://github.com/haveno-dex/haveno/blob/master/docs/installing.md)?

**Comment by XMRZombie** [comment]
Instructions should mention [install_java.sh](https://github.com/haveno-dex/haveno/blob/master/scripts/install_java.sh), because it really helps a lot to setup java correctly

**Comment by boldsuck** [comment]
Script installs unsupported Java. I wouldn't use it. I was also surprised that Nihillist mentioned the script in his tutorial.

https://jdk.java.net/21/
Older releases, which do not include the most up to date security vulnerability fixes and are no longer recommended for use in production, remain available in the [OpenJDK Archive](https://jdk.java.net/archive).

**Comment by stdec00** [comment]
@woodser Aye this was my problem I copied together and not sequenced:

`curl -s "https://get.sdkman.io" | bash`

`sdk install java 21.0.2.fx-librca`

Nood linux user issue forgive me everyone for wasting your time.

**Comment by boldsuck** [comment]
Note: On some systems you must 'source' it first

```
curl -s "https://get.sdkman.io" | bash
source "/home/user/.sdkman/bin/sdkman-init.sh"
sdk install java 21.0.2.fx-librca
```
Extra Note:
Haveno-DEX is stagenet ;-)
