### ISSUE TITLE
Support sample application using haveno-ts library [3 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#1482]
This issue requests getting the [sample Node.js application](https://github.com/haveno-dex/haveno-sample-app) to work using the [haveno-ts](https://github.com/haveno-dex/haveno-ts) library.

Currently, haveno-ts does not package its dist assets correctly to be used as a NPM dependency via `npm install haveno-ts`, causing this error when used:

```
Error: Cannot find module './HavenoClient'
```

There is a pull request in progress,  https://github.com/haveno-dex/haveno-ts/pull/332, to start fixing haveno-ts to be used as a NPM dependency, but it's only meant as a starting point.

Apply the PR to haveno-ts and run these steps to test the latest fixes in the sample application:

1. `cd haveno-ts`
2. `npm install`
3. `npm pack`
4. `cd ~/git/haveno-sample-app`
5. `npm install ../haveno-ts/haveno-ts-0.0.30.tgz`
6. `npm run start`

With the fixes from the PR applied, you should see this output in the sample application for further debugging:

```
Sample app using haveno-ts
/Users/woodser/git/haveno-sample-app/node_modules/haveno-ts/dist/HavenoClient.js:666
            throw new HavenoError_1.default(e.message, e.code);
                  ^

HavenoError: XMLHttpRequest is not defined
    at HavenoClient.getBalances (/Users/woodser/git/haveno-sample-app/node_modules/haveno-ts/dist/HavenoClient.js:666:19)
    at async main (file:///Users/woodser/git/haveno-sample-app/dist/index.js:8:22) {
  code: undefined
}
```

**Comment by im-adithya** [comment]
Would like to help here.

But I'm seeing these errors on doing `make skip-tests`:

```
Could not determine the dependencies of task ':desktop:shadowJar'.
> Could not resolve all dependencies for configuration ':desktop:runtimeClasspath'.
   > Could not resolve com.github.bisq-network:bitcoinj:2a80db4.
     Required by:
         project :desktop
         project :desktop > project :assets
         project :desktop > project :common
         project :desktop > project :p2p
         project :desktop > project :core
      > Skipped due to earlier error
   > Could not resolve com.github.bisq-network:jtorctl:b2a172f44edcd8deaa5ed75d936dcbb007f0d774.
     Required by:
         project :desktop > project :common
      > Skipped due to earlier error
   > Could not resolve com.github.haveno-dex.netlayer:tor.external:e2ce2a142c.
     Required by:
         project :desktop > project :p2p
         project :desktop > project :core
      > Skipped due to earlier error
   > Could not resolve com.github.haveno-dex.netlayer:tor.native:e2ce2a142c.
     Required by:
         project :desktop > project :p2p
         project :desktop > project :core
      > Skipped due to earlier error
   > Could not resolve com.github.bisq-network:jsonrpc4j:1.6.0.bisq.1.
     Required by:
         project :desktop > project :core
      > Skipped due to earlier error
```

Would appreciate some help

**Comment by bl4ck-cod3** [comment]
I've been working on this for a bit now and I'm having a hard time at the npm install phase.

**Comment by bl4ck-cod3** [comment]
this "fix" just introduces new issues.  I'll dig through and find where the undefined XMLHttpRequest is being used and figure out a suitable replacement.  This is a pretty big project, is the bounty capped at 3XMR?

**Comment by bl4ck-cod3** [comment]
I would like to point out this introduces vulnerabilities, per npm audit

**Comment by woodser** [comment]
@im-adithya Can you open the PR on https://github.com/haveno-dex/haveno-ts please?

**Comment by im-adithya** [comment]
@woodser done: https://github.com/haveno-dex/haveno-ts/pull/339

**Comment by woodser** [comment]
@bl4ck-cod3  What do you think about @everoddandeven's solution here: https://github.com/haveno-dex/haveno-ts/pull/338

- Uses node-xmlhttprequest which is currently used in the jest tests
- Only imports types to the global object if not present
- Exports the types for clients to use without additional imports
- Ignores type warnings
- Doesn't introduce vulnerabilities (actually fixes the current high severity vulnerability).

This looks good and works well for me. Otherwise I don't know how it can be improved.

**Comment by woodser** [comment]
Fixed by https://github.com/haveno-dex/haveno-ts/pull/338
