### ISSUE TITLE
fliter "no deposit" is applied on offers to sell xmr

### ISSUE THREAD

**Issue by Cyrix126** [haveno-dex/haveno#1493]
**Description of bug:**
When enabling the "no deposit" button in the tab "buy xmr" and then switching to "sell xmr", no offers will appear.

**Possible cause:**
The filter "no deposit" is applied to the list of sell offers when it should not since only "buy offers" can choose to not require a deposit.

**Comment by woodser** [comment]
Fixed in https://github.com/haveno-dex/haveno/pull/1490
