### ISSUE TITLE
Why fork bisq?

### ISSUE THREAD

**Issue by goodboy** [haveno-dex/haveno#15]
Curious why you've decided to entirely fork `bisq` when they're already looking at adding this?

Relevant issue set:
- https://github.com/bisq-network/bisq/discussions/5285
- https://github.com/bisq-network/projects/issues/50

I mean all the power to you but just seems like burning rubber on many roads.

**Comment by erciccione** [comment]
Please see in the readme: [Why a new platform](https://github.com/haveno-dex/haveno#why-a-new-platform)

> they're already looking at adding this in bisq-network/bisq#5285

That proposal is definitely an improvement over the current situation, but requiring traders to own the entire amount in Bitcoin makes it unintuitive and way too demanding. I see the point behind it and i appreciate the effort, but it don't think would bring real benefits.

**Comment by goodboy** [comment]
@erciccione I think it's good if you can justify the fork 💯 .

Probably good to let new viewers of this code base see where the potential improvements can be found as things progress 🏄🏼

**Comment by sethsimmons** [comment]
It's also important to note that Monero integrations have been proposed, built, and rejected several times in the past, despite the vast majority of volume on Bisq being XMR/BTC:

https://github.com/bisq-network/bisq/issues/1863
https://github.com/bisq-network/proposals/issues/110
https://bisq.network/blog/cycle-6-results/
https://github.com/bisq-network/proposals/issues/122

The latest attempt to add Monero to Bisq is already receiving pushback and requires 115% deposits *in BTC* to trade XMR against fiat, which is not only a massive UX hurdle, it doesn't improve the ability for users to trade solely fiat<>XMR without owning substantially more BTC first.

**Comment by erciccione** [comment]
Closing this, as the question has been answered.
