### ISSUE TITLE
Replace absolutely every reference to Bisq, to Haveno

### ISSUE THREAD

**Issue by uranuspucksaxophone** [haveno-dex/haveno#150]
In the source code, there are still several references to bisq. It might be a good idea to remove all of those. Low priority issue.

**Comment by erciccione** [comment]
Thanks @uranuspucksaxophone :) Some references might be good to have, but we do need to cleanup the source code. #35 keeps track of the update of the copyright notice in the header.

**Comment by uranuspucksaxophone** [comment]
Thank you, I have opened PR #151   , please, keep in mind, I'm a beginner, so, if I break the entire project, please, try not to be angry.

**Comment by erciccione** [comment]
> if I break the entire project, please, try not to be angry.

I think the PR does break Haveno, but no worries, nobody will get angry :)

i'm unscheduling this issue for now, since many files still need to be removed or heavily edit. Better remove all references later on.

**Comment by erciccione** [comment]
This is resolved by #193
