### ISSUE TITLE
Price per XMR is not accurate

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#18]
Currently the price per XMR actually shows the price per BTC.

![image](https://user-images.githubusercontent.com/13068859/114878192-fccbc000-9dcd-11eb-9c60-398774d0b020.png)

This issue requests fixing the price to be accurate.

**Comment by dowdyma1** [comment]
it looks like the price providers for bitcoin are held in `bisq.core.provider.ProvidersRepository`

I tried to access the 5 tor links on line 39-43, but I got an error.
I also tried to access the link on line 114, same error.

**Comment by dowdyma1** [comment]
> it looks like the price providers for bitcoin are held in `bisq.core.provider.ProvidersRepository`
> 
> I tried to access the 5 tor links on line 39-43, but I got an error.
> I also tried to access the link on line 114, same error.

I believe these links are called pricenodes. I think they are servers which the bisq team hosts to get the latest price for bitcoin. If that is true, I believe we need to host our own servers for getting the latest price for monero.

One thing that is troubling me still is that I cannot get a response of bitcoin price when I put the links into the tor browser, or a response from the http link. This leads me to believe that either I am wrong about these pricenodes, or there is some 'special' way of accessing them.

**Comment by erciccione** [comment]
> This leads me to believe that either I am wrong about these pricenodes

You are not wrong. Pricenodes are managed by members of Bisq and ['pricenode operator'](https://bisq.wiki/Pricenode_Operator) is a role inside Bisq's governance system.

Detailed info: https://github.com/bisq-network/bisq/tree/master/pricenode#bisq-pricenode

**Comment by woodser** [comment]
This issue is largely resolved by basing xmr prices on the current bisq btc price feed so prices throughout the application are approximately accurate.

In the future bisq's price feed could be replaced with a service which computes prices directly from xmr markets but this can be handled as a separate issue.

**Comment by HoverHalver** [comment]
> it looks like the price providers for bitcoin are held in `bisq.core.provider.ProvidersRepository`
> 
> I tried to access the 5 tor links on line 39-43, but I got an error.
> I also tried to access the link on line 114, same error.

Hello, 
you must add getAllMarketPrices to a pricenode onion address in order to get the data.
ie pricenode.onion/getAllMarketPrices
