### ISSUE TITLE
Investigate possibility of self-hosting jtorctl

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#186]
We recently had a problem with jtorctl (https://github.com/haveno-dex/haveno/issues/132), or better, we have a problem with the correct hash not being relayed properly, which causes the buildbot to randomly fail. This will be solved only when cloudflare's cache will start to relay the same hash everywhere. It could take some time.

jtorctl is currently deprecated and could make sense to self-host it. That would allow us to rely less on external infrastructure and avoid the problem of hashes not being relayed properly in the future.

**Comment by uranuspucksaxophone** [comment]
It makes sense, it's a great idea in my opinion.

**Comment by erciccione** [comment]
Now that the issue has been fixed (https://github.com/haveno-dex/haveno/pull/214), we can close this issue, as it's not a problem anymore. In the future we might consider self host dependencies in general, not only jtorctl, but that will have a dedicated issue for that.
