### ISSUE TITLE
Provide reports on Haveno's performance[ɱ2]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#20]
Haveno's Java backend currently consumes significantly more computing resource than is necessary.

For example, performance analysis revealed the Bisq DAO to consume significant resources which will be resolved when the DAO is removed.

This issue requests detailed reports on Haveno's current resource usage in order to achieve significant performance improvements.

**Specifically requested is a list breaking down top time consumers while running the application, including references to related code in order to inform where optimizations are needed and focus developer effort.**

For example, this performance analysis on Monero's daemon breaks down time consumers and related code: https://github.com/monero-project/monero/issues/7913#issuecomment-909707754

There are many tools to analyze performance of a Java application like [JVM Monitor](https://marketplace.eclipse.org/content/jvm-monitor) built into Eclipse or [VisualVM](https://visualvm.github.io/).

**Comment by erciccione** [comment]
@haveno-dex/developers this is a good issue to start with.

**Comment by cirocosta** [comment]
tip: flamegraphs are tremendously useful - https://netflixtechblog.com/java-in-flames-e763b3d32166

**Comment by M0ner0Mum** [comment]
> tip: flamegraphs are tremendously useful - https://netflixtechblog.com/java-in-flames-e763b3d32166

I ran the `perf` command on "alice" in the guide at https://github.com/haveno-dex/haveno/blob/master/docs/installing.md

You can find the svg flamegraph at https://github.com/M0ner0Mum/haveno-performance

**Comment by erciccione** [comment]
Hello @M0ner0Mum. Thanks for the chart. Note that to receive the bounty we need more details:

> Specifically requested is a list breaking down top time consumers while running the application, including references to related code in order to inform where optimizations are needed and focus developer effort.

**Comment by chaserene** [comment]
I'm bumping the bounty to 2 XMR (1.5 XMR from me).

**Comment by agg505** [comment]
I monitored cpu consumption for the app in idle state without DAO.
By VisualVM and JMC, we can see the top consumer threads and methods.
And I'll make up reports for app and seednode with and without DAO if this kind of report is ok.

![微信截图_20211021101304](https://user-images.githubusercontent.com/5590596/138199375-e4bd8fea-69b1-4872-accf-ed40d2415276.png)
![微信截图_20211021101538](https://user-images.githubusercontent.com/5590596/138199550-fac45fab-f585-456f-a700-0c30705c6018.png)

**Comment by erciccione** [comment]
#12  is merged. @agg505 please provide us with an xmr address :)

**Comment by agg505** [comment]
@erciccione I confirm my wallet address starts with '4594' and ends with 'wLCd

**Comment by erciccione** [comment]
2 XMR Sent. @agg505 please confirm you have received the coins.

**Comment by agg505** [comment]
@erciccione I have received the XMRs, thank you!

**Comment by erciccione** [comment]
Thank you. Hopefully we will see you around again :)
