### ISSUE TITLE
make test errors if OS is using language other than English

### ISSUE THREAD

**Issue by Randall-Coding** [haveno-dex/haveno#210]
make tests won't pass if OS is using a language other than English. I have mine set to Spanish right now.

Error:
> org.junit.ComparisonFailure: expected:<0 d[ay]s> but was:<0 d[ía]s>

Test:
> testFormatAccountAge

It appears the problem is with checking for the output "days" if the language is something different (in this case "dias").

To reproduce:
Set OS to a language other than English and do `make clean && make` in haveno/ folder

**Comment by premek** [comment]
Should be fixed by #212

**Comment by erciccione** [comment]
Could you confirm this is fixed?

**Comment by erciccione** [comment]
I'm assuming #212 fixed the problem. Please reopen if that's not the case.
