### ISSUE TITLE
Support setting daemon login credentials in monero-wallet-rpc `set_daemon`

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#215]
This issue requests support to set daemon login credentials in monero-wallet-rpc's [`set_daemon`](https://github.com/monero-project/monero/blob/4f08d52dfacb62469b44c1ab68a37852011c8e3b/src/wallet/wallet_rpc_server.cpp#L4357) rpc call.

See https://github.com/monero-project/monero/issues/8143

**Comment by erciccione** [comment]
Our testing binaries support it: https://github.com/haveno-dex/monero/releases/tag/testing3

**Comment by premek** [comment]
would you mind summarizing what are the credentials for? Where are their values taken from? 
Are they used by monero-wallet-rpc to authenticate when connecting to the daemon?

**Comment by woodser** [comment]
The credentials are used by monero-wallet-rpc to connect to a Monero daemon to support wallet operations. They're taken from whichever Monero daemon the user connects to (local or remote).

**Comment by woodser** [comment]
PRs opened on monero-project: https://github.com/monero-project/monero/pull/8145 https://github.com/monero-project/monero/pull/8166

**Comment by woodser** [comment]
Resolved with monero v0.17.3.2 release.
