### ISSUE TITLE
Upgrade Gradle version to 7.3.3 [0.75 XMR]

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#224]
Currently we are using `6.6.1` would be good to upgrade to `7.3.3`.

#223 needs to be merged first.

Upgrading to > 7 requires some breaking changes. See Bisq's commits:

- [Upgrade to 7.3](https://github.com/bisq-network/bisq/commit/6a3d2642da86e6b9a9225719bdadd39fbe1f8908)
- [Upgrade Gradle wrapper to 7.3.3](https://github.com/bisq-network/bisq/pull/5936/commits/064c7590a8defd7b95eb2ed4007546e16b130d93)

**Comment by erciccione** [comment]
Note that there is an abandoned draft that could be used a a base to resolve this PR: https://github.com/haveno-dex/haveno/pull/232

**Comment by duriancrepe** [comment]
Hi I'll take a look at this.

**Comment by erciccione** [comment]
Thanks @duriancrepe. Assigned to you :)

**Comment by duriancrepe** [comment]
Got a pull request up but realized the mac / windows build fails, will take a look.

**Comment by duriancrepe** [comment]
All builds working.

**Comment by erciccione** [comment]
Reward sent. Thanks again @duriancrepe! :)
