### ISSUE TITLE
Adding Gold & Silver as Currency Options

### ISSUE THREAD

**Issue by RunnyBabbit** [haveno-dex/haveno#229]
High-value, low difficulty feature request for adding gold, silver & [Goldbacks](https://m.youtube.com/watch?v=TeFXrh6DEMY)  as currency options within Haveno 

Adding this functionality would be huge for XMR adoption, liquidity & utility — particularly to the 'Free Staters' in New Hampshire (the largest Monero & hard money parallel economy in the world), and create new private, fungible, sound-money, non-KYC/AML avenues for customers & vendors to on-ramp/off-ramp into the Monero ecosystem

Note:  Gold & silver are denominated in grams & troy ounces, and 24k 'Goldback' plastic-laminated gold-foil bills are in denominated by 1/1000's of a troy ounce

**Comment by trymeouteh** [comment]
Would be an amazing addition!

**Comment by bitcoinlion21** [comment]
Really like this idea

**Comment by aerarius** [comment]
**epic idea**

**Comment by plxkax** [comment]
Great idea, how exactly will the gold selection work? Say someone sends a canadian 1oz gold coin but the buyer wants an american? There would need to be a selection of say "Gold Bar" or "Gold Coin" first, if gold coin is selected then it goes into saying:-

"American Buffalos" 
"Britannias"
"Krugerrand " 
"Austrian Philharmonic"
"Canadian Maples"

Would need information added such as:-

Name: American Buffalos
Manufacturer: United States Mint
Purity: .9999
Country: USA
Condition: Perfect

and perhaps it could all start with 1oz only before getting into others. Just some ideas if this was to be added?

**Comment by albotroz** [comment]
In the near future, this may become a little more difficult with the anonymous buying and selling of gold bars, for example.

On the other hand, the blockchain could be used to verify the authenticity of the precious metal bars when trading it via Haveno DEX.

https://www.mining-journal.com/gold-and-silver-news/news/1429338/wgc-and-lbma-to-trail-blockchain-gold-tracing

**Comment by RunnyBabbit** [comment]
> Great idea, how exactly will the gold selection work? Say someone sends a canadian 1oz gold coin but the buyer wants an american? There would need to be a selection of say "Gold Bar" or "Gold Coin" first, if gold coin is selected then it goes into saying:-
> 
> "American Buffalos" "Britannias" "Krugerrand " "Austrian Philharmonic" "Canadian Maples"
> 
> Would need information added such as:-
> 
> Name: American Buffalos Manufacturer: United States Mint Purity: .9999 Country: USA Condition: Perfect
> 
> and perhaps it could all start with 1oz only before getting into others. Just some ideas if this was to be added?

Numismatic prices & rare collectables are irrelevant;  Only the bullion prices (ie, melt value) should be listed, based on the publicly-traded XAU (gold) & XAG (silver) exchange rates

Most gold & silver bars/rounds/coins have no numismatic premium attached to them, and are strictly used for their non-collectable monetary value

The standard units of measurement for XAU & XAG are troy ounces (and fractions thereof), at 24k purity (99.999%)

"Goldbacks" have a monetary premium that trades at a floating ratio of about ~2:1 GLDBCK/XAU

**Comment by RunnyBabbit** [comment]
> 

Checking for counterfeit fiat is already the responsibility of the Monero tradee, just as assaying the purity of precious metals is; also,the reputation system already solves this for both fiat & precious metals trading

No need to make it needlessly complicated

**Comment by woodser** [comment]
This would require fetching prices for gold and silver in the [price node](https://github.com/haveno-dex/haveno-pricenode), else all offers would need to be posted with fixed prices.

**Comment by woodser** [comment]
Gold and silver are supported in the latest release, using fixed price offers only: https://github.com/haveno-dex/haveno/releases/tag/v0.0.6
