### ISSUE TITLE
Deploy clearnet price node

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#254]
This issue requests deploying a clearnet price node for Haveno so localhost develpment can use Haveno's price node.

Currently, localhost development does not run a Tor node and requires a clearnet price node endpoint.

See https://github.com/haveno-dex/haveno/blob/10f39aa65f706dd4518b8e131b8e27e44665510e/core/src/main/java/bisq/core/provider/ProvidersRepository.java#L109

**Comment by erciccione** [comment]
Added in #251. Can be tested at https://price.haveno.network/getAllMarketPrices
