### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/haveno#268]
Will Haveno have multiple accounts and as many accounts as possible. This would be useful and will increase users privacy and allow a person to have accounts for different uses such as account 1 for buying Monero and account 2 for selling Monero.

**Comment by erciccione** [comment]
I don't see the benefit of having one account for selling and one account for buying. Anyway, for general questions please use our chatrooms (see the readme of this repository).

**Comment by trymeouteh** [comment]
Many crypto wallets such as Unstoppable Wallet for example support multiple accounts. This will be useful when dealing with public ledger coins like bitcoin to give users the ability to do certain tasks in different accounts and no one can determine these two accounts are the same person by observing the blockchain.
