### ISSUE TITLE
Reject creating crypto payment account with invalid currency code or address [0.25 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#282]
This issue requests rejecting new crypto payment accounts with an invalid currency code or address.

The functionality should be implemented in [CorePaymentAccountsService.java](https://github.com/haveno-dex/haveno/blob/75c66ee43f86952481548dc7c66c0f16714c32c9/core/src/main/java/bisq/core/api/CorePaymentAccountsService.java#L103).

This entire file should be [updated from Bisq](https://github.com/bisq-network/bisq/blob/master/core/src/main/java/bisq/core/api/CorePaymentAccountsService.java) and merged with Haveno with proper attribution.

In addition, [these tests](https://github.com/haveno-dex/haveno-ts/blob/226072d28d260b6b3abcbac849fbdb046f595d5a/src/HavenoClient.test.ts#L991) should be enabled to test end-to-end.

**Comment by notabitologist** [comment]
I'm in work on this, though crazy schedule next couple weeks, so it will be a minute before I can test. The "these tests" link gives me a 404 error.

**Comment by notabitologist** [comment]
Looks like the test link should be https://github.com/haveno-dex/haveno-ts/blob/master/src/HavenoClient.test.ts
Correct me if I'm wrong.

**Comment by woodser** [comment]
Corrected the test link to https://github.com/haveno-dex/haveno-ts/blob/226072d28d260b6b3abcbac849fbdb046f595d5a/src/HavenoClient.test.ts#L991

**Comment by gilnicki** [comment]
Hi! 
Is this issue still being worked on?

**Comment by woodser** [comment]
napoly had opened a pr: https://github.com/haveno-dex/haveno/pull/487

**Comment by woodser** [comment]
Closed by #487
