### ISSUE TITLE
Reject payment accounts with duplicate names [0.25 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#283]
This issue requests rejecting payment accounts with previously given names.

A [test should be added](https://github.com/haveno-dex/haveno-ts/blob/6640dcb2ee3d99e3dadd01c47b07336c30085fd2/src/HavenoClient.test.ts#L922) to test correct error handling in that case.

**Comment by klinki** [comment]
Please assign it to me, I will look into it.

**Comment by woodser** [comment]
I've assigned the issue to you. Thanks.

**Comment by woodser** [comment]
Fixed with #556 and [#180](https://github.com/haveno-dex/haveno-ts/pull/180).
