### ISSUE TITLE
Make offers support multiple payment methods

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#285]
It would be very beneficial for users and would allow people to offer multiple choices to traders for a single offer. For example:

Somebody wanting to sell XMR for EUR at the moment can only choose between SEPA transfer, revolut, cash by mail, etc. If they want to offer additional payment methods they have to open multiple offers (and pay additional fees).

With multiple payment methods, the trader would be able to sell their XMR for all the payment methods they have set up on Haveno, and people would be able to pick the method they prefer.

We believe this would improve user experience and liquidity. We plan to introduce this in the future, but it's not a priority at the moment. Community contributions are always appreciated

**Comment by SamsungGalaxyPlayer** [comment]
Seems useful 👍
