### ISSUE TITLE
Base/counter currencies and price inverted for crypto offers [$250]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#293]
Every offer has a base currency (XMR) and a counter currency (e.g. ETH).

Currently, the base currency and counter currency are switched when a crypto offer is posted. For example, an offer posted to trade XMR for ETH will store the base currency as ETH and the counter currency as XMR.

In addition, the offer price is also inverted, so the price is posted as e.g. ~13 instead of ~1/13.

This issue requests fixing the base and counter inversion for crypto offers.

To reproduce and test this issue:
- Run and fix [this line](https://github.com/haveno-dex/haveno-ts/blob/1281f9223f3c2657889623c836f2c0bbeb7a6669/src/haveno.test.ts#L915) in the tests to remove the `TODO` about the base/counter inversion.
- Run and fix [this line](https://github.com/haveno-dex/haveno-ts/blob/1281f9223f3c2657889623c836f2c0bbeb7a6669/src/haveno.test.ts#L748) in the tests to remove the `TODO` about the offer price inversion.

**Comment by duriancrepe** [comment]
Started looking at the code, and I see why this is done this way. The legacy desktop UI treats fiat to XMR as "buy and sell XMR" orders. 

Alt-coins are treated as buy and sells of those coins (i.e. ETH) with XMR as the base. I'll see if there is a way to unify the creation of these orders to not depend on the currency type of the order and hopefully the rest of the logic should fall in place.

**Comment by woodser** [comment]
> Started looking at the code, and I see why this is done this way. The legacy desktop UI treats fiat to XMR as "buy and sell XMR" orders.
> 
> Alt-coins are treated as buy and sells of those coins (i.e. ETH) with XMR as the base. I'll see if there is a way to unify the creation of these orders to not depend on the currency type of the order and hopefully the rest of the logic should fall in place.

Interesting, although I still so no reason to do it like that. The base currency is always XMR. Treating it as anything else creates inconsistency and confusion throughout the code.

**Comment by duriancrepe** [comment]
> > Started looking at the code, and I see why this is done this way. The legacy desktop UI treats fiat to XMR as "buy and sell XMR" orders.
> > Alt-coins are treated as buy and sells of those coins (i.e. ETH) with XMR as the base. I'll see if there is a way to unify the creation of these orders to not depend on the currency type of the order and hopefully the rest of the logic should fall in place.
> 
> Interesting, although I still so no reason to do it like that. The base currency is always XMR. Treating it as anything else creates inconsistency and confusion throughout the code.

Agreed, it was difficult but I managed to find the spots that needed the inversion removed.

**Comment by erciccione** [comment]
We decided to stick with the standard. Reward for the work done sent anyway.

**Comment by duriancrepe** [comment]
> We decided to stick with the standard. Reward for the work done sent anyway.

Received, thank you!

**Comment by woodser** [comment]
> Agreed, it was difficult but I managed to find the spots that needed the inversion removed.

How do you feel about incorporating these changes, to resolve the inversions and checks throughout the code, and simply adjust in the UI to conform to standard presentation?
