### ISSUE TITLE
Create XMR transaction ask.

### ISSUE THREAD

**Issue by abouolia** [haveno-dex/haveno#307]
Hi Haveno folks, Tried to create XMR transaction to send some xmr to another address using `havenoClient.createXmrTx()` but always the daemon replies that message `not enough unlocked money` even though there's `422130734339104` in the available balance and locked balance and reserved balance is still zero and amount that set to `setAmount` method is "1" as string.

**Comment by woodser** [comment]
Sounds quite strange. Can you share the relevant havenod logs?

There should be an exception or messages related to XmrWalletService, createTx, or createXmrTx in the havenod terminal.

You can confirm that this prints `422130734339104`

```
const balancesBefore: XmrBalanceInfo = await havenoClient.getBalances();
console.log(balancesBefore.getUnlockedBalance());
```

Also, you should send e.g. "100000000000" instead of "1" atomic unit, but that doesn't explain the error message.

**Comment by abouolia** [comment]
```
balance: 422130734339104
lockedBalance: 422130734339104
reservedOfferBalance: 0
reservedTradeBalance: 0
unlockedBalance: 0
```


Tried to fund my daemon with `start_mining ADDRESS 1` but how to fund `unlockedBalance`.

**Comment by woodser** [comment]
The funds in the wallet are locked. 10 blocks need to be mined before the funds in the wallet unlock and can be used in a transaction.

To mine, enter into monerod, e.g.: `start_mining 59dF9pSotECe1Fn4dBGZXWHYyNdo53rbZ7YYseu9jBKCf4c2cUzhuFVRH8HuD4wyaKTqtD3VF3F4eQe3Kzq342F5U8R4jeq 1`

This assumes an external monerod to a command in the terminal, such as from the [setup instructions](https://github.com/haveno-dex/haveno/blob/master/docs/installing.md#3b-run-your-own-private-stagenet), not automatically started with the Haveno instance.

**Comment by abouolia** [comment]
Thanks, the issue is solved.
