### ISSUE TITLE
Support restoring an account without restarting havenod [$250]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#310]
This issue requests the ability to restore an account without restarting havenod.

Otherwise, the client must have permission to start the havenod process, which does not work with remote of vm setups.

**Comment by duriancrepe** [comment]
Hi, I'll give this a try.

**Comment by duriancrepe** [comment]
I've restructured the code and attempted to restart by running the daemon's execute(args[]) function but there are definitely issues to work through such as the persistence manager assuming its already shutdown. I think this is due to the guice initialized static objects and will need to be re-initialized correctly.

**Comment by duriancrepe** [comment]
Quick update I was able to issue multiple restarts on a daemon instance and it appears to function. It wasn't guice objects but the PersistenceManager static variables. Resetting them appears to solve the problems. Going to search for any remaining static objects that may cause issues.

**Comment by darkdrag00n** [comment]
@woodser Is this bug/bounty still open? I can see that #320 has probably been abandoned. I am open to reviving it and driving it to completion.

**Comment by woodser** [comment]
Sure you are welcome to complete it, with the bounty being split with @duriancrepe if he is available to claim it. The split would be somewhat subjective based on his contribution and yours, but it would be nice to close this one out. Thanks.

**Comment by woodser** [comment]
@duriancrepe Please message and we can pay this bounty out. Thanks for your work on it.

**Comment by woodser** [comment]
Closed with https://github.com/haveno-dex/haveno-ts/pull/174
