### ISSUE TITLE
Get prebuilt binaries for windows, linux, and mac

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#311]
This issue requests getting pre-built binaries for windows, linux, and mac of:

- havenod
- monerod
- envoy proxy

These binaries are necessary to create a standalone desktop app bundle.

**Comment by erciccione** [comment]
Note that monerod and envoy binaries are already available for all platforms, what we need is static Haveno binaries for linux, Mac and Windows.

This is how bisq creates static/release binaries: https://github.com/bisq-network/bisq/blob/master/docs/release-process.md. The command doesn't seem to work for us, so we either need it adapted for Haveno or we build binaries in another way.

**Comment by woodser** [comment]
Binaries are working using the legacy desktop app using these instructions: 

https://github.com/haveno-dex/haveno/issues/304

https://github.com/haveno-dex/haveno/issues/304
