### ISSUE TITLE
Connect to random seednodes

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#404]
seednodes are currently picked in the order they are lsited. Would be better to randomise the picking, to distribute load.

**Comment by AllyKaz** [comment]
Taking a look at this, but not sure I can see the issue. In the places where SeedNodes are pulled from SeedNodeRepository and used in some way where the order matters they are shuffled before use: 

Request Manager: 121, 
PeerExchangeManager: 104, 295.

Not sure if the issue has already been addressed, or I'm just misunderstanding it.
