### ISSUE TITLE
fix color scheme of offer book in market view [0.5 XMR]

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#409]
![Screenshot_20220816_090507](https://user-images.githubusercontent.com/28106476/184818704-398c1226-708e-4e84-b79a-791961eb0a4e.png)

**Comment by aguolmedo99** [comment]
hi im interested where i can find more info?

**Comment by erciccione** [comment]
Hello @aguolmedo99. Feel free to ask any question. The screenshot you see is taken from the Market view (see desktop/src/main/java/bisq/desktop/main/market). As you can see the text is almost invisible, because it's white instead of black.

You are welcome to join our support room for developers on Matrix: https://matrix.to/#/#haveno-dev:haveno.network or IRC/Libera: `#haveno-dev`

**Comment by DomPro11** [comment]
Hello, could I be assigned this issue? I found the problem here, and am currently drafting an official pull request. I'd be happy to explain it in detail here or on Matrix. Thanks!

**Comment by erciccione** [comment]
@DomPro11 DM me on matrix with an XMR address for the reward please :)

**Comment by erciccione** [comment]
Reward sent. Thanks @DomPro11 :)
