### ISSUE TITLE
Remove/disable unsupported payment methods

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#420]

**Comment by s11ngh** [comment]
Are there any guidelines, instructions on how to do it?

**Comment by erciccione** [comment]
He @s11ngh, missed your comment for some reason. There are no instructions, but you can see previous related PRs to get an idea, like https://github.com/haveno-dex/haveno/pull/298/. I also suggest to join the #haveno-dev channel, where devs can receive live coordination and support :)

**Comment by erciccione** [comment]
Note that we don't have a final list of payment methods and fiat currencies supported. So, better unschedule this task for the time being.
