### ISSUE TITLE
Increase fiat trade limit to 2 XMR

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#426]
This issue requests increasing the trade limit for high risk fiat trade limits from 1 XMR to 2 XMR.

**Comment by erciccione** [comment]
Hey @abdullahkhaled007, thanks, it would be very helpful. Limits were alrerady increased in past with https://github.com/haveno-dex/haveno/pull/79. It should give you a good start, but i suggest to join the matrix room for live help and coordination (https://matrix.to/#/#haveno-dev:haveno.network or on IRC/Libera: #haveno-dev)

**Comment by abdullahkhaled007** [comment]
seems like its already been increased by a factor of 10 with #84

**Comment by erciccione** [comment]
That's correct @abdullahkhaled007. We need to increase it again :)

**Comment by woodser** [comment]
This issue is not about increasing the overall trade limit, but about capping fiat trade limits. Currently high risk, low age fiat accounts have a trade limit of 1 XMR. We want to increase the cap to 2 XMR.

**Comment by woodser** [comment]
How's it going @abdullahkhaled007?

**Comment by woodser** [comment]
Closed by #490
