### ISSUE TITLE
can't compile haveno on archlinux 5.19.7-arch1-1

### ISSUE THREAD

**Issue by folfgirl** [haveno-dex/haveno#429]
I can't compile haveno on archlinux this is the make output with the --debug option [haveno.txt](https://github.com/haveno-dex/haveno/files/9536417/haveno.txt)

**Comment by woodser** [comment]
It looks like you're using JDK 17+. First thing I'd try is an earlier version up to 14.

**Comment by woodser** [comment]
I confirmed only JDK 11 is officially supported.

**Comment by folfgirl** [comment]
ok, thanks for the support and clarification
