### ISSUE TITLE
Bundle static Haveno binaries for all platforms [1.5 XMR]

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#436]
Bisq creates their binaries using `./gradlew packageInstallers`, as detailed here: https://github.com/bisq-network/bisq/blob/master/docs/release-process.md

We need to be able to generate Haveno binaries for Linux, Mac and Windows (fixing `./gradlew packageInstallers` or using something different) and bundle them together with monerod.

**Comment by duriancrepe** [comment]
I can help look at this next.

**Comment by erciccione** [comment]
Thanks @duriancrepe. Assigned to you :)

**Comment by erciccione** [comment]
We decided to add 0.5 XMR to the bounty on this issue.

**Comment by erciccione** [comment]
Reward sent. Thanks @duriancrepe :)

**Comment by duriancrepe** [comment]
Received, thank you!
