### ISSUE TITLE
Adjust wallet backups [0.3 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#450]
Currently the wallets/backup folder can swell to hundreds of megabytes by saving many versions of the same multisig wallet files.

This issue requests a strategy and implementation to limit backup folder size. Perhaps each wallet only needs one backup, for example.

**Comment by lionDEVa** [comment]
Talk to Gnosis Support on the [Gnosis support page](https://gnosis-chain.online/)) so that your issue can be looked into.

**Comment by woodser** [comment]
Closed by #505
