### ISSUE TITLE
make unable to click the button to take offers if not enough funds in wallet [0.25 XMR]

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#453]
Users are currently able to click the button to take an offer despite insufficient available balance. When taking the trade, the trade wallet balance will appear funded with whatever amount is needed, despite insufficient balance.

**Comment by duriancrepe** [comment]
Hi, I can look at this.

**Comment by duriancrepe** [comment]
From what I see, the reason you are allowed to enter into "take offer" without any funds in you wallet is that you can fund the wallet from that screen or fund it externally using that button. I see that the take offer page correctly shows my wallet balance of 0 which is insufficient. Do we still want to fix this by denying entry to the take offer page? It seems like the original intention was to allow it.

**Comment by woodser** [comment]
The issue is that the user is able to confirm taking the offer with insufficient funds, which leads to an error, not that they are able to open the take offer page.

**Comment by duriancrepe** [comment]
OK, I'll try to reproduce that part so far I have not seen that behavior with 0 funds, perhaps I need to be partially funded.

**Comment by woodser** [comment]
This issue is resolved.
