### ISSUE TITLE
Support changing password in legacy desktop app [$300]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#531]
This issue requests the ability to change the password in the legacy desktop app.

The UI supports changing the password under Account > Wallet Password:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/13068859/211644500-37d929a4-dcf1-4a9b-bb6d-3c8d03d49503.png">

But this function is currently broken, showing a popup error: "Wallet password could not be set. You may have imported seed words...".

There is a [PR in progress](https://github.com/haveno-dex/haveno/pull/530) to correctly set the account password.

On startup, there is UI prompt to input the account password:

![image](https://user-images.githubusercontent.com/13068859/211637154-f19b99cf-fb3e-4ee2-b118-1e02bc82a2e8.png)

What's missing from the PR is prompting for the password at the beginning of the startup sequence, in `loginAccount()`, to avoid any subsequent errors and warnings due to the account not yet being open.

We want to move this UI prompt to run as part of `loginAccount()` from HavenoExecutable.java and its subclass HavenoAppMain.java.

Steps to reproduce current broken behavior on master branch:

1. [Install haveno](https://github.com/haveno-dex/haveno/blob/master/docs/installing.md) if necessary.
2. Start haveno app: `make user2-desktop-local`.
3. Click Account > Wallet Password > enter and confirm a password.
4. Click to confirm setting the password.
5. Observe the warning "Wallet password could not be set. You may have imported seed words...".

The password is not changed.

After applying [the PR in progress](https://github.com/haveno-dex/haveno/pull/530) to master, you will see warnings on the app console indicating where the UI password prompt should be moved to. To reproduce:

1. Apply the PR, #530 
2. Change the password under Account > Wallet password
3. Restart application
4. Observe warnings on console with "TODO" indicating that account is not yet open, e.g. "TODO: override loginAccount() to collect account password by opening popup"

**Comment by niyid** [comment]
Hi. If this is still open, please assign to me. Thanks @woodser

**Comment by niyid** [comment]
I suppose I need to wait for the PR fixing #530 to be merged?

**Comment by woodser** [comment]
No need to wait. #530 is a work in progress intended to help resolve this issue.

**Comment by niyid** [comment]
Not a good idea to launch a GUI (`**desktop**`) entity from a `**core**` class. The `**desktop**` depends on `**core**` and not the other way round. The password window needs to be opened from within a higher up GUI entity. I will suggest which later.

Regards.

**Comment by niyid** [comment]
@woodser I await your comments.

**Comment by woodser** [comment]
Yes, this is the challenge to solve for this issue. Some time ago, @duriancrepe [added a method](https://github.com/haveno-dex/haveno/commit/e3b9a9962b4000a48b157664de5f62c4e23fd1f1), `loginAccount()`, which prompts for a password from the terminal on startup if necessary, and then loads and decrypts the app files.

Somehow we need to prompt for the password in the GUI on startup and then load and decrypt the app files.

**Comment by niyid** [comment]
Payment received. Thanks.
