### ISSUE TITLE
Add new page to legacy UI: Support > Signed Offers [$250]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#543]
This issue requests adding a screen to the legacy UI under Support > Signed Offers, alongside the current tabs:

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/13068859/214375452-11e923fc-fc45-4a95-8999-63700555e6c8.png">

This page will display offers which the arbitrator previously signed and allow the arbitrator to penalize the maker by broadcasting the offer's "reserve tx", thereby charging the maker's trade fee.

The page should display a table with a row for each signed offer, consisting of columns for Date, Offer Id, Key Images, and Signature.

The new page should support the ability for the arbitrator to right click a signed offer and select "Penalize maker by publishing reserve tx" and present a popup to confirm the transaction, which should invoke `xmrWalletService.getDaemon().submitTxHex(reserveTxHex)`.

This information is sourced from the existing SignedOffers table, where each signed offer consists of the following fields:

```
message SignedOffer {
    int64 time_stamp = 1;
    string offer_id = 2;
    string reserve_tx_hash = 3;
    string reserve_tx_hex = 4;
    repeated string reserve_tx_key_images = 5;
    string arbitrator_signature = 6;
}
```

To get signed offers for rendering: `openOfferManager.getSignedOffers(): List<SignedOffer>`

The PR should follow existing patterns in the legacy UI to implement the new page.

**Comment by niyid** [comment]
@woodser 

Please assign to me. Thanks.

**Comment by woodser** [comment]
Thanks @niyid.

In the confirmation popup, can you please also include basic information about the transaction, at least tx hash, mining fee, and a message e.g. "This will charge the buyer as maker the trade fee of 0.001 XMR and return the remaining trade funds of 0.45 XMR to their wallet. Are you sure you want to send?" ?

Others are interested to complete these bounties, so if you find yourself unavailable, please let us know so we can re-assign.

**Comment by niyid** [comment]
```
message SignedOffer {
    int64 time_stamp = 1;
    string offer_id = 2;
    string reserve_tx_hash = 3;
    string reserve_tx_hex = 4;
    repeated string reserve_tx_key_images = 5;
    string arbitrator_signature = 6;
}
```

The above is the expected. But the below is what is currently in the pb.proto file.

```
message SignedOffer {
    string offer_id = 1;
    string reserve_tx_hash = 2;
    string reserve_tx_hex = 3;
    string arbitrator_signature = 4;
}
```

I am assuming some update is required? Or should I go ahead and update myself?

**Comment by woodser** [comment]
Sorry, the update was in #542, which has just been merged to master.

**Comment by woodser** [comment]
Closed with https://github.com/haveno-dex/haveno/pull/570

**Comment by niyid** [comment]
Paid
