### ISSUE TITLE
Allow arbitrator to publish penalty tx in legacy UI "Failed trades" tab [$150]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#544]
The arbitrator has a record of trades which failed to initialize under Portfolio > Failed:

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/13068859/214374396-b8cb9093-b7a5-4f29-be0a-a68422e439f9.png">

When a trade is taken, both the maker and taker provide a "reserve transaction" to the arbitrator which, if broadcast, penalizes the trader by charging their trade fee and sending remaining trade funds back to their wallet.

This issue requests the ability to right click a failed trade and select "Penalize {buyer/seller} as {maker/taker} by publishing reserve transaction", providing an option for each trader, then confirming to broadcast the transaction, using `xmrWalletService.getDaemon().submitTxHex(reserveTxHex)` to publish the reserve transaction's hex.

The `reserveTxHex` is sourced from `trade.getMaker()/getTaker().getReserveTx()` and can be found in the failed trade's details in the UI.

**Comment by niyid** [comment]
@woodser 

Please assign to me. Thanks.

**Comment by woodser** [comment]
Closed with https://github.com/haveno-dex/haveno/pull/570

**Comment by niyid** [comment]
Paid
