### ISSUE TITLE
ARM64 installer (Apple M1)

### ISSUE THREAD

**Issue by troy-harris-droid** [haveno-dex/haveno#622]
Would be great to have an installer for an M1 without having to compile from source.

Latest Haveno-1.0.0.dmg 64-bit x86_64

**Comment by woodser** [comment]
Related issues from Bisq:

- https://github.com/bisq-network/bisq/issues/6180
- https://github.com/bisq-network/bisq/pull/5835
- https://github.com/openjfx/javafx-gradle-plugin/pull/113

**Comment by woodser** [comment]
@troy-harris-droid You ran the command to allow Haveno to run on mac?

`sudo xattr -rd com.apple.quarantine /Applications/Haveno.app`

**Comment by nbdy-coder** [comment]
> @troy-harris-droid You ran the command to allow Haveno to run on mac?
> 
> `sudo xattr -rd com.apple.quarantine /Applications/Haveno.app`

got this error

“Haveno” is damaged and can’t be opened. You should move it to the Trash.

**Comment by nbdy-coder** [comment]
> > “Haveno” is damaged and can’t be opened. You should move it to the Trash.
> 
> This error is expected. It can be ignored by right clicking /Applications/Haveno.app > Open, and repeating again if it's reported as damaged.
> 
> See [release notes](https://github.com/haveno-dex/haveno/releases/tag/v0.0.6) for full instructions on mac.

 no it doesn't work

Right click /Applications/Haveno.app > Open. Repeat again if necessary, even if reported as damaged.

== i can spam 100 time, mac os will not accept
