### ISSUE TITLE
Request - Add to payment method: Cardless Cash (Withdraw Cash at ATM with CashCode via smartphone bank app)

### ISSUE THREAD

**Issue by clonetang** [haveno-dex/haveno#626]
Cardless Cash is a non reversible, popular privacy preserving method in Australia of withdrawing cash from atm without a bank card. 

The buyer of monero uses bank app to initiate a cardless cash withdraw. 
A code and pin is generated that they need to share with the seller of monero. 
Monero seller can then withdraw cash with provided cash code/pin at the banks ATM within the allowed time. (30mins – 3hours depending on Bank)

What is needed to be known before accepting a trade:
Mandatory, List of Banks accepted.
 Both parties need to know what banks the other party use to ensure the trade is suitable before accepting.
	
$500 withdraw limit. Haveno  may not need to set this max per trade, users should be able to manage it?
	
The taker/maker will need to co-ordinate via the haveno chat for a suitable time for both parties to transact as Cash Codes/PIN are valid for limited time (30mins to 3hrs depending on bank)

Concern:
I am concerned offers may be listed on haveno but not immediately ready to accept by the other party when its finally taken.
Either a warning / reminder to make sure you leave your offer up only if you are ready to make trade because the price can change if using a floating price.
But with small fees on monero this may not be too much of an issue.
Bisq seemed to have had an issue with this too https://bisq.community/t/cardless-cash-option/2111/7 but could be mitigated if contact details are provided (optional) before accepting trade in a general text field for contacts or other conditions. Localmonero doesnt seem to have an issue with this. If a trade is initiated out of band there is no escrow protection.

Examples of Cardless cash Localmonero offers:
https://localmonero.co/buy-monero-using-cash-at-atm-with-aud-in-australia

Bisq discussions:
https://bisq.community/t/cardless-cash-option/2111/7
https://bisq.community/t/request-to-add-a-payment-method-for-au-cardless-cash-withdraw-cash-at-atm/5718/1

Cardless Cash information:

cba
https://www.commbank.com.au/digital-banking/cardless-cash.html
westpac
https://www.westpac.com.au/faq/cardless-cash-what-is-it/
bank of melbourne
https://www.bankofmelbourne.com.au/online-services/mobile-banking/cardless-cash
bank saa
https://www.banksa.com.au/online-services/mobile-banking/cardless-cash

**Comment by woodser** [comment]
The Cash at ATM option is now supported with #626.
