### ISSUE TITLE
Radio buttons are still green in legacy UI

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#634]
This issue requests making the radio buttons the same consistent blue theme used elsewhere.

<img width="647" alt="Screenshot 2023-06-02 at 11 06 15 AM" src="https://github.com/haveno-dex/haveno/assets/13068859/5a153213-f941-4d77-a627-447e15feb492">

**Comment by Vinicius149** [comment]
> @Vinicius149 Maybe you'd be interested to clean this bit up?

Yes, i am!
Good thing for the weekend, soon i will take a look.

**Comment by woodser** [comment]
Any luck @Vinicius149? :)

**Comment by coinstudent2048** [comment]
Hi,

This seems to be the default color of radio button in JFoenix. See:
https://github.com/sshahine/JFoenix/blob/a1be87d91d578e7799bc308b3b1bbe1d742a020d/jfoenix/src/main/java/com/jfoenix/controls/JFXRadioButton.java#L99-L106
And the color is #0F9D58.

So a fix is to change selected color to Haveno blue (#0b65da)
```java
public JFXRadioButtonSkinHavenoStyle(JFXRadioButton control) {
    super(control);
    control.setSelectedColor(Color.web("#0b65da")); // <---
```
I'll make a pull request for this.
