### ISSUE TITLE
Support editing offers

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#654]
This issue requests the ability to edit your offers, which is supported in Bisq but has not been maintained in Haveno while more basic function was built.

The button to edit offers was removed until this feature is supported, so a good first step is to revert this commit: 455b1f739cdb7d4e43d9d2a586c91d0e5777ec8c

See https://github.com/haveno-dex/haveno/blob/aeb0822f9fc72bd5a0e23d0c42c2a8f5f87625bb/core/src/main/java/haveno/core/offer/OpenOfferManager.java#L590

**Comment by woodser** [comment]
Implemented in https://github.com/haveno-dex/haveno/pull/662

**Comment by triskovac-zasmat-0g** [comment]
When editing offer there is not preset actual % from market price value.

**Comment by woodser** [comment]
@triskovac-zasmat-0g This should be fixed with @nsec1's PR, which has been merged to master, if you want to apply it: https://github.com/haveno-dex/haveno/pull/1062
