### ISSUE TITLE
Add scrollbar to payment account popups [0.25 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#656]
This issue requests adding a scrollbar to popups for payment account terms if they're too long to fit on the screen, which can happen with low resolution screens.

For example, the popup with terms for the "Pay by Mail" payment account is long:

<img width="821" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/f4d1da0b-db93-4224-9520-10ebdddef0f9">

**Comment by woodser** [comment]
This can be implemented by using a `ScrollPane` with Overlay.java's message field.

**Comment by coinstudent2048** [comment]
Working on this.

**Comment by woodser** [comment]
Ok I've assigned the issue to you  @coinstudent2048 :)

**Comment by woodser** [comment]
@coinstudent2048 Checking in if I should merge this as is, or if you are working on adding padding, and also if you are interested in working on bounty issue #673? Another volunteer can help with #673 if you're unavailable.

**Comment by coinstudent2048** [comment]
Hello. Apologies for late reply. I am not working on adding padding, but I
* Am adding this on other long overlays.
* Will try to fix the bullet (it's large).
* Will try #677, but no guarantees on this.
I'll add commits tomorrow. Thanks!

**Comment by woodser** [comment]
Thanks @coinstudent2048. Please message with a XMR address for payment. Feel free to DM on matrix.

**Comment by coinstudent2048** [comment]
Hello. I contacted the one with monero.social, because the haveno.exchange one doesn't work for me in Element. Thank you.

**Comment by coinstudent2048** [comment]
Payment received. Thank you.
