### ISSUE TITLE
Entering offer amount below minimum resets to maximum

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#658]
In the legacy desktop UI, if you enter an offer amount below the minimum of 0.1 XMR, the application will reset your input to the maximum offer amount with a popup:

<img width="857" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/67386830-8e80-47d7-a058-4b79f9700311">

This issue requests resetting the user's input to the minimum offer amount in this case.

**Comment by Sowik** [comment]
I would like to work on that
