### ISSUE TITLE
Add Cash App as a payment method

### ISSUE THREAD

**Issue by Final-Phoenix** [haveno-dex/haveno#685]
Cash App is a popular payment method on LocalMonero/Agoradesk. It would be a nice option to have on Haveno for onramping small to moderate sized Monero purchases. 

While not on the same level of privacy as in person trades or mailing physical cash - Cash App has no knowledge of the other side of the trade. It is also much more difficult for the counterparty to chargeback if paying from their cash app balance vs other popular digital payment methods.

**Comment by woodser** [comment]
Bisq removed CashApp in response to chargebacks a few years ago:

https://bisq.community/t/important-cash-app-and-venmo-payment-methods-have-been-blocked-due-to-chargeback-activity/5459/35

Unless something has changed, it'd be risky to trade an unreversable asset.

**Comment by woodser** [comment]
> there are many payment methods like Zelle that are on Bisq that can be chargebacked, no?

They can, but it depends how easily they grant chargebacks. Some services are more thorough while others make it too easy.

**Comment by shortwavesurfer2009** [comment]
I think the maker should be the ultimate decision maker as to whether they want to take that risk or not. If they wish to take the risk, then we should allow them to do so. If they do not wish to take the risk, then they don't have to.

**Comment by shortwavesurfer2009** [comment]
Bounty available 0.4+ XMR https://bounties.monero.social/posts/125/0-400m-haveno-add-cash-app-and-paypal

**Comment by preland** [comment]
I will work on this if everyone is okay with it being added.

I think the chargeback risks should be presented to the seller, as that is a valid concern.

**Comment by shortwavesurfer2009** [comment]
Oh, absolutely. I think my comment from earlier applies. The seller should absolutely be told of the risks. And if the arbitration really just doesn't want to deal with it, they can put in something about they will always find in favor of the seller or the buyer or whatever with no questions asked.

**Comment by preland** [comment]
This issue can now be closed
