### ISSUE TITLE
"Error in the pull function." when attempting to clone

### ISSUE THREAD

**Issue by jerzybrzoska** [haveno-dex/haveno#71]
When attempting to clone the repository by running:
```
git clone https://github.com/haveno-dex/haveno.git
```
I get the following output:
```
Cloning into 'haveno'...
remote: Enumerating objects: 268676, done.
remote: Counting objects: 100% (286/286), done.
remote: Compressing objects: 100% (200/200), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

**Comment by premek** [comment]
can you try some of the tips here? https://stackoverflow.com/questions/38378914/how-to-fix-git-error-rpc-failed-curl-56-gnutls

**Comment by erciccione** [comment]
This seems to be a local problem unrelated to Haveno. Please try @premek's suggestion and see if that works.

**Comment by jerzybrzoska** [comment]
As suggested in the link that @premek provided, `apt install gnutls-bin` resolved the issue.
