### ISSUE TITLE
Add ability to freeze and thaw outputs using monero-wallet-rpc

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#73]
Haveno depends on the ability to freeze and thaw outputs from monero-wallet-rpc, so this issue requests implementing that functionality in monero-project.  [See existing issue](https://github.com/monero-project/monero/issues/7720)

**Comment by woodser** [comment]
I'm working on this.

**Comment by woodser** [comment]
Implemented by https://github.com/monero-project/monero/pull/7729

**Comment by erciccione** [comment]
monero-project/monero#7729 is merged. Monero now supports freezing and thawing outputs.

**Comment by woodser** [comment]
It's merged into monero-project master but not the v0.17 release to be in the next update. Maybe they will accept it being merged there.

**Comment by woodser** [comment]
PR to release-v0.17 branch: https://github.com/monero-project/monero/pull/7838
