### ISSUE TITLE
Fix error starting applictions after upgrading to Gradle wrapper 8.5

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#735]
After upgrading to [Gradle wrapper 8.5](https://github.com/haveno-dex/haveno/commit/593bced55aa20cb8b309403fa0a677595a1a0a3a), this error occurs running the applications e.g. with `make haveno-desktop-stagenet`:

```
./haveno-desktop \
		--baseCurrencyNetwork=XMR_STAGENET \
		--useLocalhostForP2P=false \
		--useDevPrivilegeKeys=false \
		--nodePort=3104 \
		--appName=Haveno \
		--apiPassword=apitest \
		--apiPort=3204
Error: Could not find or load main class haveno.desktop.app.HavenoAppMain
Caused by: java.lang.ClassNotFoundException: haveno.desktop.app.HavenoAppMain
make: *** [haveno-desktop-stagenet] Error 1
```

The error is seen in the [CI tests](https://github.com/haveno-dex/haveno-ts/actions/runs/7169199799/job/19757432337) too.

@napoly Hoping you can help?

**Comment by napoly** [comment]
pls assign.. will have a look
