### ISSUE TITLE
Load native libraries [0.75 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#783]
This issue requests loading the [native libraries](https://github.com/woodser/monero-java/releases/tag/v0.8.10) for monero-java in Haveno, such that `MoneroUtils.loadNativeLibrary()` succeeds.

The native libraries should be loaded using proper gradle config.

This will allow us to switch from monero-wallet-rpc to native wallet bindings in the future for better performance.

**Comment by niyid** [comment]
Hello @woodser 

I  will take a look at this if you don't mind.

**Comment by woodser** [comment]
Ok, thanks @niyid :)

**Comment by niyid** [comment]
> Ok, thanks @niyid :)

Assign please.

BTW, I have gotten the MoneroUtils.loadNativeLibrary() call to complete successfully after installing just:

libmonero-java
libmonero-cpp
libboost_serialization (libboost-serialization-dev)
libunbound (libunbound-dev) 
libboost_chrono (libboost-chrono-dev)
libboost_program_options (libboost-program-options-dev)
libhidapi-libusb (libhidapi-dev)

But I suppose for a universal solution, I need these steps automated in Gradle:

1. Clone the project repository: git clone https://github.com/woodser/monero-java.git
2. cd ./monero-java
3. Install Maven dependencies: mvn install
4. Update submodules: ./bin/update_submodules.sh
5. Build the monero-cpp submodule (located at ./external/monero-cpp) as a shared library by following [instructions](https://github.com/woodser/monero-cpp#using-monero-cpp-in-your-project) for your system.
6. Build shared libraries to ./build/: ./bin/build_libmonero_java.sh

**Comment by niyid** [comment]
> Ok I will assign once at my computer.
> 
> The static libraries can be assumed to be downloaded to the .localhost directory, alongside the current monerod and monero-wallet-rpc binaries, and can be installed from there in a presumably similar fashion. Later we can update the build script to automatically download to the .localnet folder from a remote repository.

I do not understand - "downloaded to the .localhost directory"

**Comment by woodser** [comment]
> Remember to assign.

I've assigned the issue to you. Please let me know if you're not able to complete so we can re-assign based on availability.

> Do you use a Mac? I will need your help testing on a Mac

Yes, I can test proper solutions which should be cross-platform for windows, linux, and mac.

Thanks!

**Comment by niyid** [comment]
> Ok I will assign once at my computer.
> 
> The static libraries can be assumed to be downloaded to the .localhost directory, alongside the current monerod and monero-wallet-rpc binaries, and can be installed from there in a presumably similar fashion. Later we can update the build script to automatically download to the .localnet folder from a remote repository.

I am currently cloning monero-cpp into ${projectDir} - haveno. Does that work? I can then add monero-cpp to .gitignore

**Comment by niyid** [comment]
> > Remember to assign.
> 
> I've assigned the issue to you. Please let me know if you're not able to complete so we can re-assign based on availability.
> 
> > Do you use a Mac? I will need your help testing on a Mac
> 
> Yes, I can test proper solutions which should be cross-platform for windows, linux, and mac.
> 
> Thanks!

Well, I don't own a Mac. I do not know any other way to test but on one. If that is an issue, let me know.

**Comment by woodser** [comment]
No we don't want to import the projects directly. Instead we should assume that the [static libraries](https://github.com/woodser/monero-java/releases/tag/v0.8.10) built from the projects are downloaded from a remote repository to haveno/.localnet, the same as how monerod and monero-wallet-rc are currently downloaded to that folder and then made available to the application via gradle config and some Java code. Essentially for testing, I want to be able to copy and paste libmonero-cpp.so and libmonero-java.so into .localnet, build, and have them become available on the classpath of app.

**Comment by woodser** [comment]
> I don't own a Mac. I do not know any other way to test but on one

A mac shouldn't be necessary to develop the solution, since it should use gradle config and be platform agnostic, except to hardcode the library extensions (i.e. .so, .dylib, .dll).

With that solution, I don't mind to test on mac to ensure it's working the same as on linux and windows.

**Comment by niyid** [comment]
> > I don't own a Mac. I do not know any other way to test but on one
> 
> A mac shouldn't be necessary to develop the solution, since it should use gradle config and be platform agnostic, except to hardcode the library extensions (i.e. .so, .dylib, .dll).
> 
> With that solution, I don't mind to test on mac to ensure it's working the same as on linux and windows.

The static libs in https://github.com/woodser/monero-java/releases/download/v0.8.10/libmonero-linux-arm64.zip etc will not work unless of course the list of deps are installed - 

sudo apt update && sudo apt install build-essential cmake pkg-config libssl-dev libzmq3-dev libsodium-dev libunwind8-dev liblzma-dev libreadline6-dev libpgm-dev qttools5-dev-tools libhidapi-dev libusb-1.0-0-dev libprotobuf-dev protobuf-compiler libudev-dev libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev libboost-locale-dev libboost-program-options-dev libboost-regex-dev libboost-serialization-dev libboost-system-dev libboost-thread-dev python3 ccache

...and of course this must be executed in Gradle. I want to be sure this gives a consistent result across OSes.

**Comment by niyid** [comment]
Thanks for this. I just realized I had the solution already and I was just
complicating things. I will continue with the assumption that all setup is
complete and the native libraries for Monero-Java are just being copied to
the expected path where they are shared.

**Comment by woodser** [comment]
The static libs should bundle their dependencies to be executable standalone, afaik.

Yeah fine to assume the libs have been pre-downloaded to the .localnet, and then the build process should install to make them available at runtime.

**Comment by niyid** [comment]
> The static libs should bundle their dependencies to be executable standalone, afaik.
> 
> Yeah fine to assume the libs have been pre-downloaded to the .localnet, and then the build process should install to make them available at runtime, similar to the monerod and monero-wallet-rpc binaries downloaded to .localnet.

Let me get this clearly - the final libs you need in .localnet for the proper functioning of MoneroUtils.loadNativeLibrary() are the .a files (static libraries) and not the .so libs? Are you saying you will be producing the .a files and placing them where they can be downloaded to the user's workspace where they will be referenced during the build process?

**Comment by woodser** [comment]
Yes that's correct, though I'll have some work to do to make the libs static with a dynamic lib wrapper to be imported into JNI. I think that's my todo before you can reliably proceed, since otherwise, the dynamic libraries won't be self-contained.

**Comment by niyid** [comment]
OK then. You can create a new issue that this depends on; and tag me so I
get notified when it is completed and closed.

**Comment by woodser** [comment]
Probably we need to update the JDK and JFX to make the native libs work.

**Comment by niyid** [comment]
Any new commits that I am missing in the latest release? I don't see expected files in .localnet after make build.

**Comment by woodser** [comment]
Not yet. We're trying to upgrade the JDK which will allow the native libraries to be used.

**Comment by niyid** [comment]
Ok, thanks for the update. What issues are you getting trying to update the
JDK? What version are you targeting?

**Comment by woodser** [comment]
Targeting JDK 21. The only issue now is fixing the Windows installer.

**Comment by woodser** [comment]
Good news @niyid. Upgrading to JDK 21 has resolved the issue loading the native libraries in Haveno. I have a draft PR to load and test the libraries, which I prepared before this was working: https://github.com/haveno-dex/haveno/pull/813. It works if the shared libraries are first copied into the .localnet directory.

A next step will be to download and extract the shared libraries from a remote repository. I'd like to think about this a bit longer, but it should be straight forward once decided, so no action needed at this time.

**Comment by woodser** [comment]
Native libraries are successfully loading and being used with this PR: https://github.com/haveno-dex/haveno/pull/813
