### ISSUE TITLE
Update TOR to 0.4.8.8+ [1 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#789]
This issue requests updating the TOR binary to use 0.4.8.8+.

Currently we're using 0.4.7.7, and 0.4.8 improves performance using POW.

See [netlayer in build.gradle](https://github.com/haveno-dex/haveno/blob/f875479311b8bb85423065a30aa388ef97c1fa5f/build.gradle#L74). Probably we want to upgrade to the latest from https://github.com/JesusMcCloud/netlayer.

Likely related to https://github.com/haveno-dex/haveno/issues/756

**Comment by preland** [comment]
As the PR for this issue has been merged, is this issue now resolved?

**Comment by woodser** [comment]
Yes, this and the [scrollbar](https://github.com/haveno-dex/haveno/issues/677) bounty are now resolved. Please post or DM an address to receive the bounties. :)
