### ISSUE TITLE
Update JFX and JDK [5 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#803]
This issue requests updating to JFX 17+ and the JDK accordingly.

Otherwise, Haveno cannot build or run on ARM without emulation.

Further, this update is necessary to use native monero libraries (.so/.dll/dylib) instead of the monero-wallet-rpc server.

The person who solves this should be able to claim the related bounty to run on ARM: https://github.com/haveno-dex/haveno/issues/792.

Napoly has started a PR to update to JDK 21 and JFX 20: https://github.com/haveno-dex/haveno/pull/647/files

The UI should be minimally functional for MVP.

**Comment by niyid** [comment]
@woodser

Please just reassign. I don't want to cause delays. Apologies for any
inconveniences.

**Comment by woodser** [comment]
This issue is solved and bounty claimed with https://github.com/haveno-dex/haveno/pull/647. Thanks @napoly!
