### ISSUE TITLE
Investigate and remove Google analytics

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#804]
On startup, this message is logged:

`Feb-29 19:02:37.331 [JavaFX Application Thread] INFO  b.core.btc.setup.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=www.google-analytics.com:9050        Version 5`

This issue requests investigating and removing google analytics.

**Comment by preland** [comment]
Looking into this reveals a very weird revelation....

That message....shouldn't exist in Haveno. At all.

The message occurs on line 202 of [this file](https://github.com/bisq-network/bisq/blob/f941ef300f8d036d9bfd73a1231b408d7eaeb44b/core/src/main/java/bisq/core/btc/setup/WalletsSetup.java#L202); however, the line is only present in the original Bisq code. The equivalent code for haveno [here](https://github.com/haveno-dex/haveno/blob/master/core/src/main/java/haveno/core/xmr/setup/WalletsSetup.java#L166) should result in very different behavior.

Is Haveno somehow....running unmodified Bisq code directly?

**Comment by phytohydra** [comment]
I see from the timestamp that's quoted from my comment in #790.  I included the log messages referencing Google Analytics from both Bisq and Haveno, and that's the one from Bisq, as you can see if you check the context.  The Haveno one was,
`Feb-29 19:26:46.744 [JavaFX Application Thread] INFO  h.core.xmr.setup.WalletsSetup: Using Socks5Proxy: www.google-analytics.com:9050   Version 5`

**Comment by phytohydra** [comment]
Ha.  Okay, this is some interaction with /etc/hosts.

I have several lines in my /etc/hosts to prevent DNS lookups of those domains from succeeding, of the form,
`127.0.0.1      www.google-analytics.com`

For whatever reason, the code is doing a reverse DNS lookup of 127.0.0.1 by taking the first matching line in /etc/hosts, which on my system happens to have been www.google-analytics.com.  If I change that, the logged message changes.

So this can be closed, I guess.

**Comment by woodser** [comment]
Closing as invalid. Thanks for your analysis @phytohydra.
