### ISSUE TITLE
Generate keypairs from a script [0.25 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#821]
Currently, to register arbitrators or other roles, keypairs can be generated with [GenerateKeypairs.java](https://github.com/haveno-dex/haveno/blob/master/core/src/test/java/haveno/core/util/GenerateKeypairs.java), which can be run from an IDE (e.g. right click > run java).

This issue requests easily running this utility from a command line, without dependence on an IDE.

The solution is ideally portable and self-contained.

**Comment by woodser** [comment]
Not necessarily executables, but something that runs from the terminal. It could depend on the haveno project to be built.

Someone has reached out interested to work on this, fyi.

**Comment by niyid** [comment]
Strange. If you can run it from the IDE, why can't you run it from the
Terminal?

**Comment by woodser** [comment]
The IDE configures the classpath for you, which is based on your local gradle cache.

For example, the command copied from Eclipse is:

```
/Users/woodser/.sdkman/candidates/java/21.0.2.fx-librca/bin/java \
-classpath /Users/woodser/git/haveno/core/bin/main:/Users/woodser/git/haveno/core/bin/test:/Users/woodser/git/haveno/core/bin/default:/assets/bin/default:/Users/woodser/git/haveno/assets/bin/main:/Users/woodser/git/haveno/common/bin/default:/Users/woodser/git/haveno/common/bin/main:/Users/woodser/git/haveno/proto/bin/default:/Users/woodser/git/haveno/proto/bin/main:/Users/woodser/git/haveno/p2p/bin/default:/Users/woodser/git/haveno/p2p/bin/main:/Users/woodser/.gradle/caches/modules-2/files-2.1/javax.annotation/javax.annotation-api/1.2/479c1e06db31c432330183f5cae684163f186146/javax.annotation-api-1.2.jar: ... :/Users/woodser/.gradle/caches/modules-2/files-2.1/org.objenesis/objenesis/3.3/1049c09f1de4331e8193e579448d0916d75b7631/objenesis-3.3.jar \
-XX:+ShowCodeDetailsInExceptionMessages haveno.core.util.GenerateKeypairs
```

But this isn't a generic script.

**Comment by niyid** [comment]
So you mean you cannot execute this exact same script in the Terminal?

**Comment by woodser** [comment]
I can execute that command in my terminal, but it's specific to my environment. It needs to be a generic script or command that anyone can run.

**Comment by niyid** [comment]
But the environment is from the project run configuration for the specific
Java application which is the same in every instance of the project. I
don't think you added anything to the run configuration did you?

**Comment by woodser** [comment]
Nope I didn't customize the run config at all.

**Comment by woodser** [comment]
Could be easiest to create a gradle task which can be invoked from the terminal, e.g. `./gradlew generateKeypairs`.
