### ISSUE TITLE
Border appears on chat message hover or click, causing changes to text wrapping and sporadic scrolling [0.25 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#836]
After the JDK 21 update, blue borders appear around trader chat messages on hover and click:

<img width="761" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/6e292ab1-64b7-45c9-971e-de5ec7448d87">

The borders cause changes to the text wrapping and unexpected scrolling.

This issue requests removing the blue border and restoring previous behavior so the UI does not re-render or unexpectedly scroll.

**Comment by preland** [comment]
Looking into this

**Comment by woodser** [comment]
@preland Pushing for a new release since there's a bug in the trader chat with the last release. Hoping this can make it in :)

**Comment by preland** [comment]
I did see that bug while working on it; the issue should be solved by that PR (it looks like it was just some leftover css from bisq)

**Comment by woodser** [comment]
Issue is resolved with https://github.com/haveno-dex/haveno/pull/840
