### ISSUE TITLE
Native libraries failing on Windows [2 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#842]
Currently, native libraries are built on Windows for monero-java and monero-cpp, producing these files:

- libmonero-cpp.dll
- libmonero-cpp.dll.a
- libmonero-java.dll
- libmonero-java.dll.a

However, using the native libraries results in an error when using JNI functions: "UnsatisfiedLinkError".

If they worked as expected, Haveno could use the native libraries instead of monero-wallet-rpc on Windows.

To reproduce the failure in a test:

1. On Windows, download [Visual Studio Code](https://code.visualstudio.com/) and install Java extensions.
2. Import the monero-java project into workspace.
3. [Build](https://github.com/woodser/monero-java?tab=readme-ov-file#windows) or [download](https://github.com/woodser/monero-java/releases/tag/v0.8.13) the Windows native libraries to the ./build folder.
4. Open TestMoneroUtils.java and click the button to run `testGetIntegratedAddresses()`.
5. The test should succeed, but instead fails with `UnsatisfiedLinkError`:

![image](https://github.com/woodser/monero-java/assets/13068859/798eb8f7-5c43-40e8-bdf7-82dc65dc6ad8)

This bounty is shared with the related issue on monero-java: https://github.com/woodser/monero-java/issues/82

**Comment by everoddandeven** [comment]
Take a look on my comments at https://github.com/woodser/monero-java/issues/82
I think I resolved it partially

**Comment by woodser** [comment]
This issue is resolved and the steps are documented in the instructions, with this commit to monero-java: https://github.com/woodser/monero-java/commit/45360d1d901af7b9d59ade2177d65d11c503bc73

Please post or DM an address for payment. Thanks @everoddandeven!

**Comment by woodser** [comment]
Payment sent. Thanks for your help!
