### ISSUE TITLE
Application hangs while creating withdraw tx [0.25 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#853]
Currently, the application hangs while creating a withdraw tx from Funds > Send Funds.

<img width="766" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/0cfda5d7-c5a4-40c8-9e87-ac0e206cdbf6">

On tor especially, creating the tx can take 30-60 seconds, so the application is unresponsive during this time.

This issue requests moving the processing off the main thread so the application does not hang, and adding a spinny wheel so the user knows stuff is happening, similar to the Payment Sent and Payment Received confirmation buttons.

**Comment by niyid** [comment]
I will take a look if it is all right.

**Comment by woodser** [comment]
Great, thanks.
