### ISSUE TITLE
Implement efficient generation of multisig wallet addresses [$2500]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#86]
Currently a taker must pay a trade fee before initializing the multisig wallet with the maker and arbitrator in order to prevent takers from spamming peers with unpaid work by creating multisig wallets.

As a result, the taker must have 2 outputs available in order to take a trade, one to cover the trade fee and one to deposit to multisig, which complicates the user experience. If the multisig wallet address could be known ahead of time, the taker could use one output to pay both the trade fee and the deposit tx in a single transaction.

Chapter 10 of [Zero to Monero](https://web.getmonero.org/library/Zero-to-Monero-2-0-0.pdf) describes a way to derive the address of a multisig wallet before initializing the wallet among peers.  The first two peers (maker and arbitrator) create a shared secret and publish its public key which the third peer (the taker) can use to derive the multisig address before the wallet is initialized among them.

This issue requests implementing the ability to derive multisig wallet addresses using this method. The implementation should be added to [monero-project](https://github.com/monero-project/monero).

**Comment by UkoeHB** [comment]
Until commit-and-reveal is implemented (assuming it does...) (see ZtM2 section 9.3), you will need to make sure makers and takers never re-use keys between orders. Always generate new subaddresses. Even that restriction may not be enough to prevent Wagner attacks (ask a real cryptographer).

**Comment by UkoeHB** [comment]
I am investigating this issue. Multisig wallet/address generation needs a major overhaul.

**Comment by woodser** [comment]
MRL is also investigating multisig with tryptich.

**Comment by erciccione** [comment]
A good point from tobtoht (i invited them to join the conversation here):

> Right now I'm am waiting on Sarang to get back with details on how multisig with work with Triptych.
With Triptych on the horizon it might be a waste of time to build on top of the current ms implementation as a lot of ms related code and wallet APIs may need to be changed/rewritten.

**Comment by UkoeHB** [comment]
I am operating on the assumption that wallet/address generation will be unaffected.

**Comment by UkoeHB** [comment]
I have an outline of the address generation workflow, but won't be able to pursue an implementation for a while. If someone else wants to pick this up from my notes, I am happy to collaborate.

**Comment by woodser** [comment]
Note that efficient multisig creation is more an optimization than necessity now for Haveno.

The protocol will lock both traders into multisig with only 1 output with or without efficient multisig.

**Comment by UkoeHB** [comment]
A [semi-stable branch](https://github.com/UkoeHB/monero/tree/multisig_addr_v2_boost) to resolve this issue is prepared. It is waiting on [this PR](https://github.com/monero-project/monero/pull/7877).

**Comment by erciccione** [comment]
PR: https://github.com/monero-project/monero/pull/8203

**Comment by NorrinRadd** [comment]
@woodser is this still open?

**Comment by woodser** [comment]
This hasn't been implemented, but closing this as stale and since the Haveno no longer requires it for spam, since the traders sign a penalty tx with the arbitrator.
