### ISSUE TITLE
Build installers using GitHub Actions [1 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#862]
Currently installers must be manually built for Linux, macOS, and Windows by following [these instructions](https://github.com/haveno-dex/haveno/blob/master/desktop/package/README.md).

This issue requests automatically building the installers in GitHub Actions, so the installers are created artifacts for each platform.

See [this guide](https://dev.to/sualeh/how-to-create-platform-specific-installers-for-your-java-applications-from-github-actions-2c15) for more information.

**Comment by niyid** [comment]
Hello. I will handle this.

**Comment by woodser** [comment]
Thanks @niyid. In the interest of time, this bounty will be awarded to whoever completes it first, with installers built for Linux, macOS, and Windows x86_64.

**Comment by niyid** [comment]
Is this a duplicate issue or are they just related?

https://github.com/haveno-dex/haveno/pull/864

**Comment by Jabster28** [comment]
> Is this a duplicate issue or are they just related? #864
oh, I didn't see you were working on it as well, sorry :sweat_smile:

**Comment by woodser** [comment]
Thanks @Jabster28. I've merged the PR in order to fully test it.

The installers are successfully built, so that's great.

I was only wondering if the installers can be built as part of the current CI workflow, instead of adding a new workflow, since the CI workflow already builds for Linux, macOS, and Windows. The installers could be built and uploaded as part of that?

**Comment by Jabster28** [comment]
That's fine, I was going to use it initially but it got convoluted quickly with the platform-specific dependencies and shells etc. I think I've done it well (it's in my fork, let me know if i should make another PR, .diff is also below) but I'm not 100% sure if the conditional "Move Releases" sections at the bottom was the best way of dealing with different shells. Let me know if there's any other issues.

Diff:
```diff
diff --git a/.github/workflows/artifacts.yml b/.github/workflows/artifacts.yml
deleted file mode 100644
index fb45e8f2..00000000
--- a/.github/workflows/artifacts.yml
+++ /dev/null
@@ -1,108 +0,0 @@
-name: Build Haveno Installers
-
-on:
-  push:
-    branches:
-      - master
-
-jobs:
-  build-linux:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up JDK
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'
-          java-version: '21'
-
-      - name: Install dependencies
-        run: |
-          sudo apt update
-          sudo apt install -y rpm
-
-      - name: Build Haveno Installer for Linux
-        run: |
-          ./gradlew clean build --refresh-keys --refresh-dependencies
-          ./gradlew packageInstallers
-        working-directory: .
-
-      - name: Move Release Files
-        run: |
-          mkdir ${{ github.workspace }}/release
-          mv desktop/build/temp-*/binaries/haveno-*.rpm ${{ github.workspace }}/release
-          mv desktop/build/temp-*/binaries/haveno_*.deb ${{ github.workspace }}/release
-          mv desktop/build/temp-*/binaries/desktop-*.jar.SHA-256 ${{ github.workspace }}/release
-
-      - uses: actions/upload-artifact@v2
-        with:
-          name: HavenoInstaller-linux
-          path: ${{ github.workspace }}/release
-
-
-  build-macos:
-    runs-on: macos-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up JDK
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'
-          java-version: '21'
-
-      - name: Build Haveno Installer for macOS
-        run: |
-          ./gradlew clean build --refresh-keys --refresh-dependencies
-          ./gradlew packageInstallers
-        working-directory: .
-
-      - name: Move Release Files
-        run: |
-          mkdir ${{ github.workspace }}/release
-          mv desktop/build/temp-*/binaries/Haveno-*.dmg ${{ github.workspace }}/release
-          mv desktop/build/temp-*/binaries/desktop-*.jar.SHA-256 ${{ github.workspace }}/release
-
-      - uses: actions/upload-artifact@v2
-        with:
-          name: HavenoInstaller-macos
-          path: ${{ github.workspace }}/release
-
-  build-windows:
-    runs-on: windows-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up JDK
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'
-          java-version: '21'
-
-      - name: Install WiX Toolset
-        run: |
-          Invoke-WebRequest -Uri 'https://github.com/wixtoolset/wix3/releases/download/wix314rtm/wix314.exe' -OutFile wix314.exe
-          .\wix314.exe /quiet /norestart
-        shell: powershell
-
-      - name: Build Haveno Installer for Windows
-        run: |
-          ./gradlew clean build --refresh-keys --refresh-dependencies
-          ./gradlew packageInstallers
-        working-directory: .
-
-      - name: Move Release Files
-        run: |
-          mkdir ${{ github.workspace }}/release
-          Move-Item -Path desktop\build\temp-*/binaries\Haveno-*.exe -Destination ${{ github.workspace }}/release
-          Move-Item -Path desktop\build\temp-*/binaries\desktop-*.jar.SHA-256 -Destination ${{ github.workspace }}/release
-        shell: powershell
-
-      - uses: actions/upload-artifact@v2
-        with:
-          name: HavenoInstaller-windows
-          path: ${{ github.workspace }}/release
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index 89e9e5d0..403a1ed7 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,3 +31,42 @@ jobs:
         with:
           name: cached-localnet
           path: .localnet
+      - name: Install dependencies
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        run: |
+          sudo apt update
+          sudo apt install -y rpm
+      - name: Install WiX Toolset
+        if: ${{ matrix.os == 'windows-latest' }}
+        run: |
+          Invoke-WebRequest -Uri 'https://github.com/wixtoolset/wix3/releases/download/wix314rtm/wix314.exe' -OutFile wix314.exe
+          .\wix314.exe /quiet /norestart
+        shell: powershell
+      - name: Build Haveno Installer
+        run: |
+          ./gradlew clean build --refresh-keys --refresh-dependencies
+          ./gradlew packageInstallers
+        working-directory: .
+      - name: Move Release Files on Unix
+        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
+        run: |
+          mkdir ${{ github.workspace }}/release
+          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
+            mv desktop/build/temp-*/binaries/haveno-*.rpm ${{ github.workspace }}/release
+            mv desktop/build/temp-*/binaries/haveno_*.deb ${{ github.workspace }}/release
+          else
+            mv desktop/build/temp-*/binaries/Haveno-*.dmg ${{ github.workspace }}/release
+          fi
+          mv desktop/build/temp-*/binaries/desktop-*.jar.SHA-256 ${{ github.workspace }}/release
+        shell: bash
+      - name: Move Release Files on Windows
+        if: ${{ matrix.os == 'windows-latest' }}
+        run: |
+          mkdir ${{ github.workspace }}/release
+          Move-Item -Path desktop\build\temp-*/binaries\Haveno-*.exe -Destination ${{ github.workspace }}/release
+          Move-Item -Path desktop\build\temp-*/binaries\desktop-*.jar.SHA-256 -Destination ${{ github.workspace }}/release
+        shell: powershell
+      - uses: actions/upload-artifact@v2
+        with:
+          name: HavenoInstaller-${{ matrix.os }}
+          path: ${{ github.workspace }}/release
```

**Comment by woodser** [comment]
Awesome, looks good to me. The current build.yml is using actions/upload-artifact@v3, if possible to preserve that?

Please open a new PR for final testing.

I've replied on Matrix. Hopefully you can see my messages there?

**Comment by Jabster28** [comment]
It should, yeah, release notes say it's just a different Node version. I haven't seen anything on Element, but I'm not really experienced with Matrix. Was it on `haveno-dev`?

**Comment by woodser** [comment]
Incredible, it seems to be working great.

I replied to the DMs you sent, but Matrix is having problems so people aren't able to see my messages, but rest assured I do see your messages. Please feel free to DM an address for payment :)

**Comment by woodser** [comment]
@Jabster28 I see your DM but I'm not able to reply. Please feel free to post your address.

**Comment by woodser** [comment]
Payment sent.

I think we'd actually want to create a flatpak.

**Comment by woodser** [comment]
@Jabster28 We can put a small bounty on building to flatpak if you're interested.

**Comment by Jabster28** [comment]
I don't have any experience with creating flatpaks, but I'll see what I can do. They tend to have better compatibility, though, so there's a lower chance that it references libs that only I have installed etc. I'll try and fix #865 first since that should be trivial.

**Comment by k4r4b3y** [comment]
@Jabster28 is there an update on the AppImage build for Haveno?

**Comment by Jabster28** [comment]
@k4r4b3y woodser suggested switching to a Flatpak which I have a patch for (i think the appimage one is saved somewhere too), but I was planning to wait until we've decided on a good way of dealing with binaries and where to draw the line of what the haveno devs do and what the network maintainers do, see #931

**Comment by k4r4b3y** [comment]
@Jabster28 check out this message on another issue thread: https://github.com/haveno-dex/haveno/issues/270#issuecomment-2294807880

If flatpak's require `sudo` for initial install, this can be a problem for TailsOS and Qubes-Whonix users.  An AppImage is just a "download-and-run" solution and would be a better fit for TailsOS and Qubes-Whonix users.

**Comment by woodser** [comment]
> @k4r4b3y woodser suggested switching to a Flatpak which I have a patch for (i think the appimage one is saved somewhere too), but I was planning to wait until we've decided on a good way of dealing with binaries and where to draw the line of what the haveno devs do and what the network maintainers do, see #931

It would be great to add support for both Flatpak and AppImage to the official Haveno repo. Third party networks running on mainnet would be responsible to create their own Flatpak or AppImage for distribution.

Ideally creation of the Flatpak and AppImage would be part of the existing [GitHub Actions](https://github.com/haveno-dex/haveno/blob/master/.github/workflows/build.yml#L53), which automatically creates the installers for macOS, Windows, .deb, and .rpm.

Third party networks can post these installers for download, which users can verify directly against the build from GitHub Actions for integrity.

**Comment by woodser** [comment]
@Jabster28 Opened a bounty to support building AppImage: https://github.com/haveno-dex/haveno/issues/1222

**Comment by woodser** [comment]
@Jabster28 Added a bounty to building Flatpak as well: https://github.com/haveno-dex/haveno/issues/1223
