### ISSUE TITLE
CI tests are failing [0.25 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#878]
This issue requests fixing the CI tests, which recently started failing for mac without introducing any changes, suggesting a problem separate from Haveno's repo:

<img width="637" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/8f75ac41-74b9-4e89-ba57-de19fdbba712">

**Comment by craig-shave** [comment]
Can you please provide the logs?

**Comment by woodser** [comment]
Here are the logs from the CI run: https://github.com/haveno-dex/haveno/actions/runs/8950804026/job/24586488107

Otherwise I don't know how to access the log files?

**Comment by craig-shave** [comment]
**The Gradle Terms of Service have not been agreed to.**

For _example_, if you can set an environment variable agreeing to the terms of service like follows:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Agree to Gradle Terms of Service
      run: echo "org.gradle.acceptEnterpriseTos=true" >> ~/.gradle/gradle.properties
    - name: Run Gradle
      run: ./gradlew build


Let me known if that does it!

**Comment by Jabster28** [comment]
@craig-shave, I tried your suggestion in https://github.com/Jabster28/haveno/commit/b9eb40caa0a138b9899c86b7e8cdd556114e7535, but that didn't seem to work.

> Otherwise I don't know how to access the log files? @woodser 

It looks like some of the unit tests are failing - I added an upload stanza for the test reports and downloading them (https://github.com/Jabster28/haveno/actions/runs/9004316789/artifacts/1484626679) shows this:

![Screenshot 2024-05-08 at 16-27-06 Test results - GuiceSetupTest](https://github.com/haveno-dex/haveno/assets/29015942/9f554157-d985-4644-9cb5-08e47676a918)

**Comment by woodser** [comment]
Fixed by https://github.com/haveno-dex/haveno/pull/892

@Jabster28 Please send an address for bounty payout.
