### ISSUE TITLE
Stuck on first window depend on language.

### ISSUE THREAD

**Issue by Cyrix126** [haveno-dex/haveno#912]
System tested: 
KDE Neon installed from release 20240514-1438.
Artix rolling

with
LANG= fr_FR.UTF-8

Like title imply, and maybe related to https://github.com/haveno-dex/haveno/issues/905 but not with same symptom (it doesn't crash at startup), Haveno first window will never switch to the main UI and will stay stuck even after synced and finding peers. You can change tor settings but you won't be able to close the window loading after a while without sending a SIGKILL signal.

Changing the LANG env variable to LANG=en_US.UTF8 or LANG=de_DE.UTF-8 after deleting the local data directory of Haveno make the problem disappear.

**Comment by Cyrix126** [comment]
If starting with fresh local data on en_US.UTF-8 and then without deleting the local data and starting with fr_FR.UTF-8, I can get to the main UI.

**Comment by Cyrix126** [comment]
If I start it first with fr_FR, kill it, restart it with en_US without removing local data,  it will work with FR translations

**Comment by preland** [comment]
Question: Did you manually set the language before your first run, or did it determine the language based on your system's settings? (Important, as Haveno might be using a now-deprecated language constructor)

**Comment by Cyrix126** [comment]
> Question: Did you manually set the language before your first run, or did it determine the language based on your system's settings? (Important, as Haveno might be using a now-deprecated language constructor)

It is determining from system settings, I did not changed it on first run. When the computer start, the LANG env is not set to english.
