### ISSUE TITLE
Update Tor [0.3 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#914]
This issue requests updating tor to the latest binary, by updating the relevant repos:

- https://github.com/haveno-dex/tor-binary
- https://github.com/haveno-dex/netlayer
- https://github.com/haveno-dex/haveno/pull/794/files (previous PR updating tor in haveno repo)

**Comment by preland** [comment]
Is this issue resolved?

**Comment by woodser** [comment]
Resolved. :) Please send an address.

**Comment by woodser** [comment]
I can see your messages but cannot reply. Feel free to DM.
