### ISSUE TITLE
New offer gets cancelled when funds are coming outside haveno wallet base account

### ISSUE THREAD

**Issue by privacyOG** [haveno-dex/haveno#920]
When making a new offer and funds are being transfer from outside the haveno wallet base account it will cancel the offer once the confirmations are finished. The funds end being stuck in the haveno wallet but as they are not in base account I not sure if there is way of moving them or use them

**Comment by woodser** [comment]
> funds are being transfer from outside the haveno wallet base account

I'm not sure exactly what you mean. Are you funding the offer by manually transferring funds from an external wallet? Or are you funding the wallet from your Haveno wallet?

**Comment by woodser** [comment]
If you can provide your log files, it would be helpful. It might have simply timed out creating the offer after the funds were available, in which case they're in your Haveno wallet and available for withdraw.

**Comment by privacyOG** [comment]
Your right i just looked at my logs and its was a time out just happened at exact moment the confirmation finished. Later on those funds became available again for me to use
