### ISSUE TITLE
Haveno uses new obfs4proxy renamed lyrebird

### ISSUE THREAD

**Issue by boldsuck** [haveno-dex/haveno#927]
Background:
The original obfs4proxy has ceased development, The Tor Project has forked it and renamed it to lyrebird.

Client side torrc configuration:

```
## obfs4proxy configuration
- ClientTransportPlugin obfs2,obfs3,obfs4,scramblesuit exec ./PluggableTransports/obfs4proxy
+ ClientTransportPlugin obfs4 exec ./PluggableTransports/lyrebird
```
[gitlab.tpo Pluggable-Transports lyrebird](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird)
[Debian Bug#1063423](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1954430.html)

This is part of https://github.com/haveno-dex/haveno/issues/914#issue-2298237719
https://github.com/haveno-dex/netlayer

**Comment by preland** [comment]
Does this rename break the current obfs4 implementation in Haveno? What I am mainly looking at is this: https://github.com/haveno-dex/haveno/blob/master/p2p/src/main/java/haveno/network/p2p/network/DefaultPluggableTransports.java#L32

I'm just trying to understand whether the change needed is more on a logic level or on a cosmetic level "ie displayed strings"

**Comment by boldsuck** [comment]
No, nothing has changed on the bridgelines.
Only the name of the binary has changed. Which is currently already in Haveno.
Linux: `~/.local/share/Haveno/xmr_mainnet/tor/PluggableTransports/lyrebird`

If I haven't overlooked anything, these are just these 3 config files that need to be changed:
https://github.com/haveno-dex/netlayer/blob/master/tor.native/src/main/resources/native/linux/torrc.native
https://github.com/haveno-dex/netlayer/blob/master/tor.native/src/main/resources/native/osx/torrc.native
https://github.com/haveno-dex/netlayer/blob/master/tor.native/src/main/resources/native/windows/torrc.native

[obfs2,obfs3,scramblesuit](https://support.torproject.org/glossary/obfs3/) is vulnerable & not supported anymore.

**Comment by preland** [comment]
A PR is currently open on netlayer, which implements the fixes suggested here

**Comment by woodser** [comment]
I merged that PR, so the netlayer hash is ready to be updated in the haveno repo.

**Comment by woodser** [comment]
Hoping to include this in the next update @preland.

**Comment by preland** [comment]
On it

**Comment by woodser** [comment]
Fixed with https://github.com/haveno-dex/netlayer/pull/5 and https://github.com/haveno-dex/haveno/pull/955.
