### ISSUE TITLE
Minor issue to change the default node port from (bitcoins) 8333 to Monero default port 18089

### ISSUE THREAD

**Issue by privacyOG** [haveno-dex/haveno#928]
Inside the UI on the network menu option when you select Monero custom node its says the port can be ommitted if its default 8333 which is bitcoin port. If this can be changed to Monero default node port would be appreciated.

**Comment by boldsuck** [comment]
Notice:
This **'Use custom Monero nodes'** config means P2P nodes. Corresponding command line option: `--xmrNodes=`
Monero peer-to-peer network port is: 18080 & Monero (.onion) Hidden Service P2P nodes have usualy port: 18083

An RPC node (wallet-to-node interface) can be changed with the commandline option `--xmrNode=`.
Or if necessary with `--xmrNode=  --xmrNodeUsername=  --xmrNodePassword=`

The latter options can also be added in the config file:
- Linux: ~/.local/share/Haveno/haveno.properties
- macOS: ~/Library/Application Support/Haveno/haveno.properties
- Windows: ~\AppData\Roaming\Haveno\haveno.properties

[Haveno-desktop options](https://gist.github.com/boldsuck/5fb0d6a58e2a675abfe4d7a266b66da9)

**Comment by woodser** [comment]
Fixed in #932
