### ISSUE TITLE
Loss of funds possible when restoring wallet

### ISSUE THREAD

**Issue by Nothin2CHere** [haveno-dex/haveno#929]
This issue is pretty big, and has a pretty high likelihood of losing funds as I lost 0.5XMR.

I sent a small amount of XMR to my first created wallet when running Haveno, deleted everything and reloaded which then recreated another walllet/seed, closed out haveno replaced the "wallet" folder contents with my backup and loaded up. I'm guessing the addresses are stored elsewhere this left the addresses from the newly generated folder to still appear in the "Funds" tab and I sent the XMR to the unused address of the now deleted seed.

The reason I only reloaded the wallet folder data is because i kept getting this error when restoring the entirety of the backup:
"Could not open wallet 'haveno_XMR'. Please close Haveno, stop all monero-wallet-rpc processes, and restart Haveno."
Setting the same password and replacing the wallet files with my backups remedied this, but also leaves addresses of the "old" seed in the funds tab to which I sent the 0.5XMR.

There should be a proper way of restoring, that allow you to select the path of which toi restore, closes out haveno, wipes all traces of addresses and restores what you want. 
Would also be nice if on could restore a seed directly rather than having to save/store all the extras.
![Screenshot from 2024-05-17 20-09-30](https://github.com/haveno-dex/haveno/assets/140908756/4696c774-b7f4-40d7-9453-7e0104dd17d1)

**Comment by plowsof** [comment]
a checksum of the keys file could be saved / confirmed on launch

restore (file or mnemonic)/back-up of monero wallet sounds like a useful feature

**Comment by woodser** [comment]
Fixed by #926:

- Fixes the issue restoring from backup by excluding monero binaries so they're reinstalled with correct permissions.
- Fixes the warning popup on startup failure.
- If a new Monero walles is detected, resets the internal state to prevent sending to non-existent addresses and shows a warning popup.
