### ISSUE TITLE
Allow arbitrators to see trade chat when dispte is open

### ISSUE THREAD

**Issue by XMRfamily** [haveno-dex/haveno#938]
Allow arbitrators to see trade chat when dispte is open, this is necessary to help arbitrator make the right decision. Maybe arb cant see chat until dispute is open?

**Comment by shortwavesurfer2009** [comment]
And arbitrators should absolutely not be allowed to see the chat until a dispute is opened. However, at that time, I think it is necessary in order to make the best possible decision.

**Comment by woodser** [comment]
This is supported, by clicking the "More" option in the chat window with the arbitrator to upload the trader chat as a text file:

<img width="579" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/bfbc5fb7-fb47-4fce-aeda-34c1abae33d2">

**Comment by XMRfamily** [comment]
The team wants to know if it's fakeable

**Comment by woodser** [comment]
Actually, I don't see that the chat messages are signed and verified to be correct.
