### ISSUE TITLE
Failed transactions (where abitration ruled in favor of the XMR seller party) appear on the list of trades / transactions

### ISSUE THREAD

**Issue by nihilist001** [haveno-dex/haveno#943]
I made sure that a trade failed and yet it appears on the list of trades, probably not the intended behavior, let me know if thats a valid concern:

![image](https://github.com/haveno-dex/haveno/assets/139641914/7707af85-d8ac-4ff3-a314-a15e0a525f3c)

![image](https://github.com/haveno-dex/haveno/assets/139641914/9e6e2b23-cfae-43a1-8d01-da62e3cdfc22)

In short, the buyer didn't buy anything in this case, he lost the security deposit, yet it still appears

**Comment by preland** [comment]
To make this clear: does the current implementation imply that the transaction succeeded?

**Comment by nihilist001** [comment]
> To make this clear: does the current implementation imply that the transaction succeeded?

Yes, it shows up under the market > trades so i assume it should be only the successful trades

**Comment by preland** [comment]
Yeah that probably isn’t right

What might be more pressing—on one of the pages is an option to export transactions to a CSV. I wonder if the failed trade shows up there 💀

**Comment by woodser** [comment]
Only successful trades are published in the 1.0.6 release: https://github.com/haveno-dex/haveno/commit/14d17023a87cd276a6f0c315924734656a395119
