### ISSUE TITLE
Do not allow local network IPs without turning tor off.

### ISSUE THREAD

**Issue by shortwavesurfer2009** [haveno-dex/haveno#945]
Currently, if you go into Settings, Network Info, and switch your Monero node to a local IP address such as 192.168.x.x or 10.0.x.x Without first setting the Monero network to never use tor you can end up in a state where you are not able to load the user interface to fix the problem and must fix it from the command line. Also, whenever these radio buttons are changed, you get a prompt about needing to shut down the application to make the changes stick and that can get kind of annoying. It might be better to replace that with an apply settings button once you are done setting things the way you want them that would then tell you to shut down the application

Edit: Another thing you could do is allow the network info screen to appear even if there is an issue with connecting to the Monero network so that it could be fixed in the graphical interface.

**Comment by woodser** [comment]
This issue ought to be resolved in the 1.0.6 release. Please re-open if you continue to have problems.
