### ISSUE TITLE
How to change node from config files?

### ISSUE THREAD

**Issue by satoshinotdead** [haveno-dex/haveno#951]
I'm trying to use Haveno and successfully installed and ran it on the mainnet. However, I misconfigured the node and can no longer access the GUI.

I looked through the folders where Haveno was installed on my system but couldn't find a solution.

Is there a way to change the node configuration without accessing the GUI? Is that even possible?

Thanks for developing this much-needed software. :)

> EDIT: could be related with #949

**Comment by woodser** [comment]
You can set the `--xmrNode=` option on startup.

There's an open issue to either allow the app to startup without a connection or fallback to provided nodes: https://github.com/haveno-dex/haveno/issues/923.
