### ISSUE TITLE
Error occured at task: BuyerPreparePaymentSentMessage

### ISSUE THREAD

**Issue by nihilist001** [haveno-dex/haveno#960]
Hello, just encountered this error when trying to confirm "payment sent" when doing a trade

![image](https://github.com/haveno-dex/haveno/assets/139641914/bee1a936-1f43-45f6-b4a5-f48713073ef8)

log: https://paste.mozilla.org/4OnarYeH/raw

**Comment by woodser** [comment]
I'm looking into the cause.

Does the error still happen if you restart your client?

**Comment by nihilist001** [comment]
issue is resolved after a restart, i think it just lost connection to the daemon

**Comment by woodser** [comment]
Others have reported the same issue so hoping to get to the bottom of it.

In the monero-wallet-rpc.log file within the same application directory, do you see any unusual errors around the same time as these errors in haveno.log:

```
May-24 13:02:18.851 [Thread-19364] WARN  h.c.trade.Trade: Failed to create payout tx, attempt=2/5, tradeId=VACYI7U, error=Cannot invoke "monero.wallet.model.MoneroTxWallet.getIncomingAmount()" because the return value of "monero.wallet.MoneroWallet.getTx(String)" is null
May-24 13:02:24.109 [Thread-19364] WARN  h.c.trade.Trade: Failed to create payout tx, attempt=3/5, tradeId=VACYI7U, error=Cannot invoke "monero.wallet.model.MoneroTxWallet.getIncomingAmount()" because the return value of "monero.wallet.MoneroWallet.getTx(String)" is null
May-24 13:02:29.646 [Thread-19364] WARN  h.c.trade.Trade: Failed to create payout tx, attempt=4/5, tradeId=VACYI7U, error=Cannot invoke "monero.wallet.model.MoneroTxWallet.getIncomingAmount()" because the return value of "monero.wallet.MoneroWallet.getTx(String)" is null
May-24 13:02:35.282 [Thread-19364] WARN  h.c.trade.Trade: Failed to create payout tx, attempt=5/5, tradeId=VACYI7U, error=Cannot invoke "monero.wallet.model.MoneroTxWallet.getIncomingAmount()" because the return value of "monero.wallet.MoneroWallet.getTx(String)" is null
```

**Comment by nihilist001** [comment]
> Others have reported the same issue so hoping to get to the bottom of it.
> 
> In the monero-wallet-rpc.log file within the same application directory, do you see any unusual errors around the same time as these errors in haveno.log:
> 
> ```
> May-24 13:02:18.851 [Thread-19364] WARN  h.c.trade.Trade: Failed to create payout tx, attempt=2/5, tradeId=VACYI7U, error=Cannot invoke "monero.wallet.model.MoneroTxWallet.getIncomingAmount()" because the return value of "monero.wallet.MoneroWallet.getTx(String)" is null
> May-24 13:02:24.109 [Thread-19364] WARN  h.c.trade.Trade: Failed to create payout tx, attempt=3/5, tradeId=VACYI7U, error=Cannot invoke "monero.wallet.model.MoneroTxWallet.getIncomingAmount()" because the return value of "monero.wallet.MoneroWallet.getTx(String)" is null
> May-24 13:02:29.646 [Thread-19364] WARN  h.c.trade.Trade: Failed to create payout tx, attempt=4/5, tradeId=VACYI7U, error=Cannot invoke "monero.wallet.model.MoneroTxWallet.getIncomingAmount()" because the return value of "monero.wallet.MoneroWallet.getTx(String)" is null
> May-24 13:02:35.282 [Thread-19364] WARN  h.c.trade.Trade: Failed to create payout tx, attempt=5/5, tradeId=VACYI7U, error=Cannot invoke "monero.wallet.model.MoneroTxWallet.getIncomingAmount()" because the return value of "monero.wallet.MoneroWallet.getTx(String)" is null
> ```

not sure if this is going to be of any use: https://paste.mozilla.org/vFkDnajp/raw it doesnt seem to contain the error that happened at that time, logs stop at 12:03:03 today in monero-wallet-rpc.log
