### ISSUE TITLE
Suggestion: The buyer needs monero to do their first trade

### ISSUE THREAD

**Issue by nihilist001** [haveno-dex/haveno#963]
Hello, we need to be able to onboard haveno users that start with 0 monero easily, either in the app itself or in a separate chat (like bisq does).

i suggest the following (and feel free to comment on it) :

1) new category of trades that are hidden by default: small quantity trades with no security deposit and no arbitration (only one such trade per user to avoid spam)

2) less optimal imo, a chatroom (in matrix for example) where haveno noobs can come up and get their first monero easily, like is done on bisq.

**Comment by shortwavesurfer2009** [comment]
I do not have the link on me at the moment, but I believe there is a CCS to open a Matrix room for exactly this purpose, just like BISQ

**Comment by privacyOG** [comment]
I think the solution is do what Bisq is doing where they go a chat room to get your first BTC ![Screenshot_20240525_173753_Element.jpg](https://github.com/haveno-dex/haveno/assets/102720550/64762ac2-be83-4706-aab8-074063e1dc87)

Its a limited in trade. For more info see the below link: https://bisq.wiki/Getting_your_first_BTC

**Comment by nihilist001** [comment]
its a bit weird to tell the new buyer to not use the haveno dex app at first to get his first monero, there should be an option built in imo. Sure a chatroom is a rudimentary way to do it and at least they remain within the haveno community to get their first monero, but long term i think it should be within the app directly, under special "no security deposit" trades

**Comment by boldsuck** [comment]
The matrix bisq chat for first-time buyers is now in [Bisq2.](https://bisq.wiki/Bisq_Easy)
It's fascinating how many people there ask if and where they can buy XMR. ;-)

**Comment by goatmeal01** [comment]
localmonero allowed listings for brand new buyers who didn't already have crypto or any account history. how did they deal with flaking buyers?

**Comment by shortwavesurfer2009** [comment]
> localmonero allowed listings for brand new buyers who didn't already have crypto or any account history. how did they deal with flaking buyers?

Depends. If the buyer flaked before sending the fiat they refunded the seller from the escrow. If they did a chargeback LM couldnt do anything other than delete the buyers account. That is why a lot of traders would not work with brand new buyers at all or would accept extremely small amounts from new accounts.

**Comment by goatmeal01** [comment]
> > localmonero allowed listings for brand new buyers who didn't already have crypto or any account history. how did they deal with flaking buyers?
> 
> Depends. If the buyer flaked before sending the fiat they refunded the seller from the escrow. If they did a chargeback LM couldnt do anything other than delete the buyers account. That is why a lot of traders would not work with brand new buyers at all or would accept extremely small amounts from new accounts.

I would be fine with that. Sellers should be allowed to have separate small amount listings for irreversible payment methods like cash in mail and no security deposit if they are willing to accept the risk. this would be the easiest way for new users to get onboarded.

**Comment by woodser** [comment]
Duplication of https://github.com/haveno-dex/haveno/issues/999
