### ISSUE TITLE
Clicking offer in Market view navigates to wrong screen [0.5 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#974]
Currently, clicking an offer in the Market view does not navigate to the correct screen.

For example, clicking a Bitcoin or other non-fiat offer navigates to the fiat screen:

<img width="872" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/edd3053c-5308-40c0-b67a-b156325af9df">

<img width="1004" alt="image" src="https://github.com/haveno-dex/haveno/assets/13068859/0ed552ad-7baf-4e3d-96cb-aa62c8414e0f">

This issue requests fixing all navigation linking.

Bounty goes to the first working solution.

Please test your solution to confirm the links are working:

- Clicking a fiat offer should go to Buy/Sell > Monero > with the correct fiat currency selected
- Clicking a Bitcoin offer should go to Buy/Sell > Bitcoin
- Clicking other offers should go to Buy/Sell > Other > with the correct asset selected (e.g. BCH, ETH, LTC, XAU, XAG, goldback)

**Comment by preland** [comment]
👍

**Comment by preland** [comment]
Funny; looks like the code was never originally designed to navigate to the proper screen; the current design will only navigate to one of 3 options (although it might actually only be 2, as BTC should be one of those 3 ;)

**Comment by niyid** [comment]
@woodser I have a PR on this. You might as well assign.

**Comment by woodser** [comment]
@niyid The links in your PR are not working.

The bounty remains open to the first working solution.

**Comment by preland** [comment]
(Hint: the issue isn't in that function, though idk where it actually is ;)

It seems like it'll spontaneously begin working after some time for some reason, so I'm guessing it has something to do with it not getting initialized properly.
