### ISSUE TITLE
Add additional information textbox for Australia PayID payment method

### ISSUE THREAD

**Issue by privacyOG** [haveno-dex/haveno#976]
When creating a offer using the PayID payment method there is no communication method textbox or additional information textbox, I believe at very least a additional information textbox would be need so one could put "terms of the trade" for example: request when taker makes payment to put first 6 string characters of the offer ID into payment description to make idetifying easier and or send a screenshot of transcation showing reciept number and send to following address, having this helps to fight any charge back claims.

**Comment by woodser** [comment]
Added in https://github.com/haveno-dex/haveno/pull/994
