### ISSUE TITLE
haveno fails to take an offer (probably due to arbitrator not being available)

### ISSUE THREAD

**Issue by nihilist001** [haveno-dex/haveno#978]
error1: (which im now getting consistently after trying a few times) -> could it be because the arbitrator that was chosen by the maker of the trade is not available ?  (it shows the error after like 10 seconds after trying to take the offer, definitely not a tor timeout issue)
![image](https://github.com/haveno-dex/haveno/assets/139641914/346a6419-b4ad-4f84-b9e5-1b27e6bf2acd)
haveno.log: https://paste.mozilla.org/sacEU3h9/raw

error2: and after restarting haveno with different tor bridges (this one is probably just tor being slow, u can discard it i think)
![image](https://github.com/haveno-dex/haveno/assets/139641914/bbd4080c-089f-438b-aac6-2c4a47ed933e)
haveno.log: https://paste.mozilla.org/MFaQutKn/raw

anyway, back to error 1: if this is indeed due to the arbitrator not being available, i think the offer should not appear in the first place, until both the maker and the arbitrators are both online. (not sure what the intended behavior is supposed to be)

**Comment by woodser** [comment]
Fixed with https://github.com/haveno-dex/haveno/pull/992
