### ISSUE TITLE
it *may* be possible to infer network location

### ISSUE THREAD

**Issue by shortwavesurfer2009** [haveno-dex/haveno#983]
So I just happen to be looking, and I am in the New York time zone, but yet I do not see the date change until six or seven hours after midnight local time here. Which, if correct, may be putting the seed nodes in a place like Hawaii, which would be about six hours behind New York. If this is true, then this should really be fixed and switched to UTC time instead.

**Comment by woodser** [comment]
> I do not see the date change until six or seven hours after midnight

Where are you seeing the differing time? My logs are based on local time with 24 hour clock.

**Comment by shortwavesurfer2009** [comment]
In trades tab

**Comment by haveno-user** [comment]
On linux, I can make my haveno-desktop logs print in UTC by prepending TZ=UTC when running it from a terminal.

I find it desirable to log in UTC, so if I need to publicly post a log the timezone doesn't give any clues as to my location.

Maybe the seed nodes should be run with TZ=UTC as well.
