### ISSUE TITLE
stagenet has no arbitrators available

### ISSUE THREAD

**Issue by haveno-user** [haveno-dex/haveno#986]
This makes many kinds of testing impossible unless we go trade with ourselves on Reto mainnet using real money.

[EDIT]
I see Revolut is used as a default payment account type for testing as it doesn't require any information besides a user name.

Trying to take the one Revolut offer which is up,
> This offer cannot be taken because the arbitrator's signature is invalid

`[JavaFX Application Thread] WARN  haveno.core.offer.OfferFilterService: No arbitrator is registered with offer's signer. offerId=gY3AyR-81a64f7a-be79-45a7-9be2-640768ba4ca2-106, arbitrator signer=ywoag7j4ot4kpmtiv274y34vqbkrhsvi3bdrb2j2vxcjzxkolsbziwad.onion:7777, accepted arbitrators=[]`

**Comment by woodser** [comment]
Looks like the stagenet seed nodes forgot about the arbitrator, which happens when they restart too close to each other. I've rebooted the network so the seed nodes restart at different times. The arbitrator is available and working now. Thanks again for reporting.
