### ISSUE TITLE
Building fails because of missing libmonero-cpp.so

### ISSUE THREAD

**Issue by pittybitty** [haveno-dex/haveno#995]
I have tried to compile haveno for quite a while but the build process always fails as it seems that libmonero-cpp.so is missing. libmonero-cpp.so is not contained in the haveno files, so I have compiled them manually from the monero-java project, but unfortunately it is not clear where to put the file within the haveno folder as the docs are not giving any information about this problem. Compiling has been tried on Ubuntu 22.04. What can be done to finish the build process? Here are the logs from the JRE:

###
###
###
###
###
### See problematic frame for where to report the bug.
###

**Comment by woodser** [comment]
This looks like an error which occurs at runtime. 

Are you running Haveno with `--useNativeXmrWallet=true`? Otherwise the native libraries are not used.

If not, what is the exact error when building with `make`?

Can you include the contents of the core dump?

> libmonero-cpp.so is not contained in the haveno files

The libmonero-cpp.so file is bundled in monero-java.jar and loaded at runtime for your specific platform.

Please note that using the native libraries is experimental and not well tested in Haveno, so issues are expected.

**Comment by pittybitty** [comment]
Starting haveno with `--useNativeXmrWallet=true` isn't possible for me because the build process fails at around 31%, so I am not able to start haveno at all. I have added my core dump so you can have a closer look at this problem. 
[Uploading hs_err_pid1883172.log…]()

**Comment by woodser** [comment]
Can you try building from this PR? https://github.com/haveno-dex/haveno/pull/998

For example:
```
cd ~/git/haveno
git fetch origin
git pull --rebase origin pull/998/head
./gradlew build --refresh-keys --refresh-dependencies
```

**Comment by pittybitty** [comment]
I have tried to build haveno within a fresh download by using

`git fetch origin`
`git pull --rebase origin pull/998/head`
`./gradlew build --refresh-keys --refresh-dependencies`

but the libmonero-cpp.so error persists. Building still fails around 31% while testing the haveno core module.

[hs_err_pid1903100.log](https://github.com/user-attachments/files/15597448/hs_err_pid1903100.log)

**Comment by woodser** [comment]
As a workaround in the meantime, you should be able to build Haveno using `make skip-tests`, so that the tests do not try to load the native library.

**Comment by pittybitty** [comment]
When I do `make skip-tests`it seems as if the build process is going to successfully finish but when I try to start the haveno desktop app with `./haveno-desktop` I get a similar error as in the building process with `make`.

> 
> A fatal error has been detected by the Java Runtime Environment:
>
>  SIGILL (0x4) at pc=0x00007e2e8b1532b0, pid=1937779, tid=1937826
>
> JRE version: OpenJDK Runtime Environment (21.0.2) (build 21.0.2-internal-adhoc.alex.openjdk-21-21.0.213)
> Java VM: OpenJDK 64-Bit Server VM (21.0.2-internal-adhoc.alex.openjdk-21-21.0.213, mixed mode, tiered, compressed >oops, compressed class ptrs, g1 gc, linux-amd64)
> Problematic frame:
> C  [libmonero-cpp.so+0xf532b0]  sc_mul+0x17b0
>
> Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c >-d%d -P%P -u%u -g%g -- %E" (or dumping to /home/alex/haveno/core.1937779)
>
> If you would like to submit a bug report, please visit:
>   https://bugreport.java.com/bugreport/crash.jsp
> The crash happened outside the Java Virtual Machine in native code.
> See problematic frame for where to report the bug.

**Comment by woodser** [comment]
Should be fixed now with https://github.com/haveno-dex/haveno/pull/1003, if you can try that PR.

It lazy loads the native libraries until they're used, so they're not loaded when building the tests or starting the application without them applied.

The question remains why loading libmonero-cpp.so is segfaulting on your system, which can be investigated separately. Was curious if you're on x86_64 or ARM64?

**Comment by pittybitty** [comment]
When I use

`git pull origin pull/1003/head`
`./gradlew build --refresh-keys --refresh-dependencies`

the build process finishes and I can start the desktop app by using `./haveno-desktop`. This bug can be seen as solved and the issue can be closed. Many thanks for your help! By the way my system has an x86_64 architecture.
