### ISSUE TITLE
Wallet backup fails on Windows

### ISSUE THREAD

**Issue by gavinbarnard** [haveno-dex/haveno#996]
Repro steps:

1. Open Haveno
2. Goto Account tab
3. Goto Backup under account
4. Select backup location  "Z:\haveno-backup" an NFS mount I have full read/write permissions to
5. Backup Now

log file:
```
Jun-05 00:45:44.421 [JavaFX Application Thread] ERROR h.d.m.a.c.b.BackupView: C:\Users\<user>\AppData\Roaming\Haveno-reto\xmr_mainnet\wallet\haveno_XMR.keys (The process cannot access the file because it is being used by another process) 
```

Screenshot:
![wallet fails to backup](https://github.com/haveno-dex/haveno/assets/20960742/0fe09dcc-0634-44f5-848c-fa3ee9351cee)

The backup location also does not stay saved.
I will set it to Z:\\haveno-backup and after the failure it will list as C:\\Users\\<user>

Currently I have to shutdown the Haveno services to make a backup of the wallet directory.

**Comment by woodser** [comment]
Fixed with https://github.com/haveno-dex/haveno/pull/997
